### ISSUE TITLE
MongoDB aggregation throws an error when a single timestamp has too many documents

### ISSUE THREAD

**Issue by 4upz** [cloud-carbon-footprint/cloud-carbon-footprint#1010]
When pulling while using the MongoDB cache option, an error is sometimes thrown whenever the aggregation results in combining too much data into a single document with the shared timestamps. This is most likely due to the resulting document's size being too large due to the array. Example of error:

```bash
[Cache] warn: There was an error getting estimates from MongoDB: PlanExecutor error during aggregation :: caused by :: BSONObj size: 26795582 (0x198DE3E) is invalid. Size must be between 0 and 16793600(16MB) First element: timestamp: new Date(1656633600000)
```
We need to investigate the boundary or estimated number of documents that this typically causes, and investigate a way to modify the aggregation function to handle this size

**Comment by ccasher** [comment]
Potential solution:
Include `{field_for_group:{$exists:true}}` in $match stage of the aggregate pipeline to make sure each document correctly contains ids or other necessary fields.

Source:
https://stackoverflow.com/questions/22550390/bsonobj-size-error-in-mongodb
