### ISSUE TITLE
Recommendations for GCP hangs if permission is missing

### ISSUE THREAD

**Issue by camtittle** [cloud-carbon-footprint/cloud-carbon-footprint#1014]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

When fetching GCP recommendations for the Recommendations page, the API request hangs if the GCP service account does not have the required permissions (or if any error other than a quota exceeded error occurs). Debugging it a bit, it looks like the culprit is the while loop in the `getRecommendationsForRecommenderIds` function in `packages/gcp/src/lib/ServiceWrapper.ts`. It gets stuck in a loop if the GCP client returns an error other than quota exceeded error.

It would also be useful to log out errors received from the GCP client at this point.

- **Operating System:**
  - 
- **Browser:**
  - 

### Expected Behavior

An error message is logged to the API process console and an error response returned to the client.

### Actual Behavior

The page hangs and the backend gets stuck in a loop making calls to the GCP.

### To Reproduce

- Add GCP credentials to API env file, which are missing permissions for the Recommender API, or has the Recommender API disabled
- Try and load the Recomendations page

### Additional Information

© 2021 Thoughtworks, Inc.

**Comment by 4upz** [comment]
Sorry @camtittle, I realized that we never provided a verbal update for this. You may have noticed that we added this to our project board and our planning to implement a fix as soon as we can. We appreciate you calling this out! 

If you're interested in tackling this issue, you're welcome to do so and we're happy to provide support. Otherwise, we'll post any further updates from our end here.

**Comment by ccasher** [comment]
hi @camtittle i just pushed up a fix for this [here](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/commit/45143922722ebcaaecbcdb55e4f185a949e83940). It was a bit difficult to replicate your error. Could you please either provider a list of all the Recommender permissions you currently have enabled in your service account, or you could just test this fix and let us know if it resolved your issue. Thanks!

**Comment by 4upz** [comment]
Was able to review and confirm the fix for this is working
