### ISSUE TITLE
Standardizing usage units in Lookup Table

### ISSUE THREAD

**Issue by 4upz** [cloud-carbon-footprint/cloud-carbon-footprint#1017]
- Remove usageUnit column in LUT output
- Add documentation that clarifies that LUT coefficients should be treated as hourly units

Originated from this Google Group discussion: https://groups.google.com/g/cloud-carbon-footprint/c/xfXD0s_THYg

**Comment by HankLeo** [comment]
@4upz 
Thanks for the maintenance of this LUT function. But I'm just a little bit confused about the mentioning of the MD:
For each service categorization, here are the standard usage units that the lookup table results represent and how you should multiply your usage amount:
- Compute: _Hours_
- Storage: _Terabyte-hours_
- Memory: _Gigabyte-hours_
- Networking: _Gigabytes_

So how should I use the usageAmount to multiply the LUT output? For example:
I have such usage data:
| product_region    | line_item_product_code | line_item_usage_type | pricing_unit | line_item_line_item_type | line_item_usage_amount
| -------- | ------- | -------- | ------- | -------- | ------- |
| us-west-2 | AmazonS3 | USW2-TimedStorage-ByteHrs | GB-Hours | Usage | 0.689

In this case, should I use 0.689 * lookupTableOutput.kilowattHours? Or 0.689 / 1000 * lookupTableOutput.kilowattHours? I want to know whether I need convert the usageAmount to TB-Hours again.

And I suppose the lookupTableOutput.co2e is in MT, but not KG, am I right?
