### ISSUE TITLE
Invalid 'main' field in '@cloud-carbon-footprint\core\dist\package.json'

### ISSUE THREAD

**Issue by abeggchr** [cloud-carbon-footprint/cloud-carbon-footprint#1037]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **@cloud-carbon-footprint\core:**
  - 0.17.0
- **@cloud-carbon-footprint\azure:**
  - 1.1.0
- **Node:**
  - 18.10.0
  
### Expected Behavior

The `@cloud-carbon-footprint\core` package can be used in another project by using `$ npm install --save @cloud-carbon-footprint/core` as described in the [README](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/core/README.md)

### Actual Behavior

Using the `@cloud-carbon-footprint\core` in a project yields the following warning:

```
(node:21472) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\...\node_modules\@cloud-carbon-footprint\core\dist\package.json' of 'dist/index.js'. Please either fix that or report it to the module author
```

The same warning also appears when using the `@cloud-carbon-footprint\core` in a React application.
Note that warning does not appear for the also installed `@cloud-carbon-footprint\azure`

### To Reproduce

Here's an example repository:

```sh
$ git clone https://github.com/abeggchr/cloud-vs-premise.git
$ npm install
$ npm run test
```

Steps to create the example repository:
* Setup a project with a basic vitest test ([example](https://github.com/vitest-dev/vitest/tree/main/examples/basic))
* Install `npm install --save @cloud-carbon-footprint/core`
* Import classes from the core library to the basic test
* Run the tests `npm run test`

**Comment by 4upz** [comment]
Thanks for calling this out @abeggchr! Should be fixed with [5ab78b4](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/commit/5ab78b4ce879a87afc865aadcf11b02cabd053f1) and will be included in the next release.
