### ISSUE TITLE
Big Azure estimations never finish due to error in rate limit retry

### ISSUE THREAD

**Issue by NicolasBissig** [cloud-carbon-footprint/cloud-carbon-footprint#1058]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success. **I have found #1022, which could cover this bug as well, but to fix this bug, not all changes in that issue are required. If this is not wanted, feel free to close :)**

### Issue Details

- **Operating System:**
  - Ubuntu 22.04.1 LTS x86_64
- **Browser:**
  - no browser, but CLI 

### Expected Behavior

When I fetch large amounts of Azure data, in my context a year worth of estimates for one Azure subscription using `yarn start-cli --startDate 2022-01-01 --endDate 2023-01-01`, I want to eventually be able to view this data, even if this takes a very long time.

### Actual Behavior

When fetching one month of usage data, rate limit errors occur, but eventually the estimation finishes and I am able to view the data.
When I query a year worth of data, rate limits occur and even after waiting multiple hours in a (CLI has been run in a CI pipeline) the estimations never finish, and no feedback is given, except for rate limit errors.

### To Reproduce

Query a big amount of Azure data at once, sadly I cannot give concrete numbers.

### Screenshots

Log results of querying one month, where after rate limit errors the CLI was able to recover:
![image](https://user-images.githubusercontent.com/21075964/219799420-d12a0b65-bcc9-49a0-9c47-244d1630a073.png)

Log results of querying one year, where after rate limit errors the CLI was never able to recover:
![image](https://user-images.githubusercontent.com/21075964/219800514-b3d4a8cc-8529-4c27-a0f5-200b3f4fc738.png)

### Additional Information

I have taken a look at the code myself, and it seems that the rate limit error handling implementation has a flaw at the moment:

> estimations can only be finished, if the requested time frame is possible to be queried at once without hitting a rate limit.

There exists a [recursive call to the fetch method](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/azure/src/lib/ConsumptionManagement.ts#L329), without changing parameters. This causes the rate limited query to be executed without changes, and if the query is too big to finish without hitting rate limits, cause an infinite loop.

I suggest the following changes:

- [ ] implement a maximum retry mechanism, even if it set very high, to avoid infinite loops, and provide feedback to the user
- [ ] provide the possibility to split the queried time range into smaller ranges, and only query these
- [ ] the splitting should be optional, and be configurable as days that should be queried at once

If I misunderstood something in the code, please correct me!

I have implemented these suggestions myself, and I am now able to query one year worth of data.
If these suggestions are something you would want for CCF, I will create a pull request soon, after performing more tests and cleaning up a bit.
At the moment, I am not able to provide all the changes requested in #1022, but maybe this provides a basis for this issue? For my company at least, this is a critical issue.

Hope this helps! 

© 2021 Thoughtworks, Inc.

**Comment by 4upz** [comment]
@NicolasBissig thanks for investigating this! Your insights are really appreciated. It seems that we have only accounted for the number of rate limits for concurrent requests rather than the limit of an individual request. That's possibly what led to the bug.

I think your proposed changes all make sense and that we can move forward with them. I'd be happy to take a look at your PR once it's ready! Thanks again!

**Comment by NicolasBissig** [comment]
@4upz I performed more internal testing and the proposed changes in #1059 work.
However, I only tested on one subscription, as only one is available to me at the moment.

**Comment by 4upz** [comment]
Awesome, thanks @NicolasBissig! I'll give it a review as soon as I can! Our current internal setup includes multiple subscriptions, so I'm happy to test how it performs.
