### ISSUE TITLE
Update regions to include variations for Azure

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#106]
**Context:**
For our implementation of Azure, we need to use the region to determine how to convert energy to Co2e. Azure does not have a consistent naming of these regions, so we need to add the variations into the codebase.

- [x] Deploy in any regions we do not currently have subscriptions in
- [x] All variations of Azure regions should be included in the codebase
- [ ] Update methodology to include emissions factors for Azure (suggested edits in google doc and then make those changes in codebase)

**Comment by dtoakley-tw** [comment]
For now, I've added the additional regions that ThoughtWorks use, and any others we can infer from the syntax of those. I've also added the list to the methodology, with a note about it being a subset of regions.

**Comment by ericksod** [comment]
Methodology looks good - moved back to update the md file with the changes
