### ISSUE TITLE
[API] [Question] : can i split my AWS estimates by instance type like i do for tags ?

### ISSUE THREAD

**Issue by capybarbu** [cloud-carbon-footprint/cloud-carbon-footprint#1073]
Hi there,

I'm using API with success, and I'm trying to look at the impact of switching to aws graviton instances.
Is there a way to use instance type for grouping like i use user tags ?

Thank you !

**Comment by 4upz** [comment]
Hi @capybarbu 

Thanks for reaching out and using CCF! As of right now, there isn't a way to split/group estimates by instance type. The API currently does not include this information in the response given, and they're only used when calculating estimates behind the scenes.

If the community sees value in exposing this in the resulting response, we're happy to discuss and explore it -- or even review a PR if someone wishes to tinker with it! For right now, you may have to utilize AWS user tags to apply tags to each instance you wish to assist in your comparison.
