### ISSUE TITLE
Hardcoded PUE and Carbon Emission Factor values for each of the cloud provider

### ISSUE THREAD

**Issue by shreyansh-24** [cloud-carbon-footprint/cloud-carbon-footprint#1076]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  -  Windows 10 
- **Browser:**
  - Chrome 

### Actual Behavior

We see that AWS_CLOUD_CONSTANTS has PUE value, regional carbon emission factor which are hardcoded for each of the cloud provider.
If we are using the footprint API for getting the carbon emission details for last year or last but one year, can the output be misleading as some these constant values dont represent that time PUE or emission factor values. 
Please clarify.

**Comment by ericksod** [comment]
Hi @shreyansh-24!
You are correct that right now these are static.
We do have issue #946 in analysis to consider making these dynamic.
If you are interested in working on it, please let us know!
