### ISSUE TITLE
Multi Tenancy Support for the cloud carbon footprint tool

### ISSUE THREAD

**Issue by shreyansh-24** [cloud-carbon-footprint/cloud-carbon-footprint#1083]
- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - Windows 10 (1803) 
- **Browser:**
  -  Chrome

### Expected Behavior

As mentioned in the docs, we can give environment variables in the .env file for api, client and cli for a single single cloud provider account for AWS, AZURE and GCP.  If we want to deploy it on a server and let's say we want to generate this footprint+emission+recommendation data for 10 different organisations having multiple accounts, do we currently have any functionality to get the same? Or do we have any process to support multi-tenancy within the tool?

### Actual Behavior

Currently, after putting cloud provider creds in .env, we get the emission and other data on api endpoints.

### To Reproduce

Running the tool by providing Cloud provider credentials

### Additional Information

Looking for a solution to run the tool for multiple AWS/AZURE/GCP accounts at once.

**Comment by ericksod** [comment]
Hi @shreyansh-24,
Currently we do not support multiple accounts per cloud provider.
Perhaps [this discussion thread](https://groups.google.com/g/cloud-carbon-footprint/c/nQeP1mAnu-U) will provide some insight or ideas.
Cheers!
