### ISSUE TITLE
Add Documentation for Azure Rate Limits and Chunking Configurations

### ISSUE THREAD

**Issue by 4upz** [cloud-carbon-footprint/cloud-carbon-footprint#1090]
We've added features to requests each subscription for Azure in chunked days to minimize the occurrences of rate limits for a single subscription. Rate limits still remain a common occurrence while we are working on optimizations. We should document both of these on the microsite so that information surrounding rate limits and our retry logic is accessible, in addition to the chunk configurations that can be used to get around them.

**Comment by camcash17** [comment]
LGTM!
