### ISSUE TITLE
Recommendation Details attribute not present for Azure recommendations json response

### ISSUE THREAD

**Issue by shivansh-0808** [cloud-carbon-footprint/cloud-carbon-footprint#1104]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  Windows 10 (1803) 
- **Browser:**
  Chrome / Edge

### Expected Behavior

JSON response for Azure recommendation should have recommendationDetail attribute which provides valid description of the recommendation

### Actual Behavior

recommendationDetail attribute is missing in Azure unlike AWS where we have this attribute in JSON response

### To Reproduce

while hitting /recommendations api in browser , recommendationDetail attribute is missing for Azure

**Comment by 4upz** [comment]
Hi @shivansh-0808 , Azure recommendations are currently in early release and only supporting rightsizing and shutdown recommendation types. However, there may be a chance that some rightsizing types are slipping through under different type alias causing the details to be missing. 

I noticed this on my end for `SkuChange` rightsizing recommendations. We can make a task to address this, but for more clarity -- can you provide a list of recommendation types that you are seeing missing details for?

**Comment by shivansh-0808** [comment]
"cloudProvider": "AZURE",
"accountId": "",
"accountName": "",
"region": "",
"recommendationType": "SkuChange",
"kilowattHourSavings": ,
"resourceId": "",
"instanceName": "",
"co2eSavings": ,
"costSavings": 

So these are the attributes which i can currently see under Azure recommendations JSON response ..and recommendationType is SkuChange for all of the objects in my case.

---------------------------------------------------

And for AWS recommendations JSON response , we have these attributes as below :
      "cloudProvider": "AWS",
      "accountId": "",
      "accountName": "",
      "region": "",
      "recommendationType": "",
      "**recommendationDetail**": "Modify instance: rac2. Update instance type r5.2xlarge to r5.large",
      "kilowattHourSavings": ,
      "resourceId": "i",
      "instanceName": "",
      "co2eSavings": ,
      "costSavings": 

Here if we see , we have an additional attribute **recommendationDetail** which is an important information for our furthur implementation. 
So i wanted to know when we can have the **recommendationDetail** attribute in Azure recommendations JSON response

**Comment by 4upz** [comment]
@shivansh-0808 Thanks for clarifying. It looks like this is indeed occurring for SkuChange recommendation types, and needs to be added to the code as an alias for Rightsizing recommendations so that the recommendation details are properly built. 

We will add this to our project board so we can implement a fix soon. If you're using the cloned version of the CCF, then you can pull down the changes as soon as we commit them which we will update in this ticket. If using the Create-App version, we'll try to have a fix out before our next bi-weekly release which should be the end of next week.

**Comment by 4upz** [comment]
Fixed with https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/commit/9340ca33a096a3fa18259dd4bd3c61c6260c9a25 and will be included in the next release.
