### ISSUE TITLE
Update mock emissions data to match cloud constants

### ISSUE THREAD

**Issue by camcash17** [cloud-carbon-footprint/cloud-carbon-footprint#1106]
Emissions factos in the mockdata.json file should match exactly what we have listed as cloud constants / coefficients.

**Comment by ashutoshkrris** [comment]
Hi @camcash17 
I'd like to work on the issue, could you elaborate more?

**Comment by camcash17** [comment]
Hi @ashutoshkrris, we basically just want to take the following emissions factor data:
- [AWS](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/5c2982efb0b72313743827757a896ffca57befff/packages/aws/src/domain/AwsFootprintEstimationConstants.ts#L154)
- [GCP](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/5c2982efb0b72313743827757a896ffca57befff/packages/gcp/src/domain/GcpFootprintEstimationConstants.ts#L184)
- [AZURE](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/5c2982efb0b72313743827757a896ffca57befff/packages/azure/src/domain/AzureFootprintEstimationConstants.ts#L145)

and use these values to update the mockdata.json emissions factor values located [here](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/5c2982efb0b72313743827757a896ffca57befff/packages/client/stub-server/mockData.json#L2).

**Comment by ashutoshkrris** [comment]
Thanks for assigning this to me, @camcash17 
Please let me know if my below understanding is correct:

So, suppose this is one of the emissions:
```json
{
      "region": "us-east-1",
      "mtPerKwHour": 0.0004545
}
```
In the above, the value of `mtPerKwHour` is the sum of emission factor values of `us-east-1` in all the three mentioned providers?

**Comment by camcash17** [comment]
Thanks for working on this @ashutoshkrris! Each region should be cloud specific, so `us-east-1` is actually an AWS region and `us-east1` is a GCP region for example.

**Comment by ashutoshkrris** [comment]
Ahh, got it!
Missed that, thanks for the help.

**Comment by ashutoshkrris** [comment]
@camcash17 
Just another quick question.
I can see that there are two emissions for unknown - `Unknown` and `unknown`. However, for all of the three providers, we have values of unknown.
Could you elaborate on this?

**Comment by camcash17** [comment]
Good question. For this case, I would just take the average among them!

**Comment by ashutoshkrris** [comment]
Thanks @camcash17 
Also, I was wondering, since the mockData.json file doesn't contain all the coefficients/constants from the three providers.
So, am I required to add all the others too, or just update the values of whatever exist in the mockData as of now?

**Comment by camcash17** [comment]
I would suggest only updating the values of existing regions, as the mockdata only references those.

Apologies for not including all of this information up front!
