### ISSUE TITLE
Adds support for Azure MCA accounts to filter consumption management API properly

### ISSUE THREAD

**Issue by camcash17** [cloud-carbon-footprint/cloud-carbon-footprint#1113]
For MCA accounts, the $filter param isn't supported. See the documentation here to see how the call needs to be modified in order to use the correct parameters to set the time range:

[Manage Azure costs with automation - Microsoft Cost Management | Microsoft Learn](https://learn.microsoft.com/en-us/azure/cost-management-billing/costs/manage-automation#get-usage-details-for-a-scope-during-specific-date-range)

Since the subscription is under a MCA account and it is not recognizing the $filter inputs, it is returning only the data for the current billing period.

More information regarding API behavior based on date ranges sent in (and also mentions limitations):

[Azure Consumption REST APIs | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/consumption/#working-with-billing-periods-and-date-ranges)

So apparently the new MCA agreement calls would look like this - 

GET [https://management.azure.com/{scope}/providers/Microsoft.Consumption/usageDetails?startDate=2020-08-01&endDate=2020-08-05&$top=1000&api-version=2019-10-01](https://management.azure.com/%7Bscope%7D/providers/Microsoft.Consumption/usageDetails?startDate=2020-08-01&endDate=2020-08-05&$top=1000&api-version=2019-10-01)

**Comment by mountainaireman** [comment]
I'd like to claim this enhancement.

**Comment by 4upz** [comment]
Closing this as it will be fixed as part of #1175
