### ISSUE TITLE
Cash amount error in recommendation

### ISSUE THREAD

**Issue by bgauchon-reply** [cloud-carbon-footprint/cloud-carbon-footprint#1138]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
Amazon linux 2
- **Browser:**
Irrelevant

### Expected Behavior

Have right prices in actual behavior

### Actual Behavior

My billing from aws is like 2k/month . recommendations shows last 30 days as 40k/month
I encounter a message missing data from the past 30 days, but data is present in athena and cache file

```
[root@ip-10-0-0-147 cloud-carbon-footprint]# for i in {1..9} ; do echo "2023-04-0$i" ; grep "2023-04-0$i" packages/api/estimates.cache.day.json | wc -l ; done
2023-04-01
1
2023-04-02
1
2023-04-03
1
2023-04-04
1
2023-04-05
1
2023-04-06
1
2023-04-07
1
2023-04-08
1
2023-04-09
1
[root@ip-10-0-0-147 cloud-carbon-footprint]# for i in {0..9} ; do echo "2023-04-1$i" ; grep "2023-04-1$i" packages/api/estimates.cache.day.json | wc -l ; done
2023-04-10
1
2023-04-11
1
2023-04-12
1
2023-04-13
1
2023-04-14
1
2023-04-15
1
2023-04-16
1
2023-04-17
1
2023-04-18
1
2023-04-19
1
[root@ip-10-0-0-147 cloud-carbon-footprint]# for i in {0..9} ; do echo "2023-04-2$i" ; grep "2023-04-2$i" packages/api/estimates.cache.day.json | wc -l ; done
2023-04-20
1
2023-04-21
1
2023-04-22
1
2023-04-23
1
2023-04-24
1
2023-04-25
1
2023-04-26
1
2023-04-27
1
2023-04-28
1
2023-04-29
1
[root@ip-10-0-0-147 cloud-carbon-footprint]# for i in {0..1} ; do echo "2023-04-3$i" ; grep "2023-04-3$i" packages/api/estimates.cache.day.json | wc -l ; done
2023-04-30
1
2023-04-31
0
[root@ip-10-0-0-147 cloud-carbon-footprint]# for i in {0..9} ; do echo "2023-05-0$i" ; grep "2023-05-0$i" packages/api/estimates.cache.day.json | wc -l ; done
2023-05-00
0
2023-05-01
1
2023-05-02
1
2023-05-03
1
2023-05-04
1
2023-05-05
1
2023-05-06
1
2023-05-07
1
2023-05-08
1
2023-05-09
1
[root@ip-10-0-0-147 cloud-carbon-footprint]# grep "2023-05-10" packages/api/estimates.cache.day.json | wc -l
1
[root@ip-10-0-0-147 cloud-carbon-footprint]# grep "2023-05-11" packages/api/estimates.cache.day.json | wc -l
1
```

### To Reproduce

Don't know how to reproduce, happens every time I do a fresh install

### Screenshots

![image](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/assets/95037350/6582c968-d802-470f-a8c4-6e6e2857ae32)

**Comment by 4upz** [comment]
Hi @bgauchon-reply thanks for opening this issue! We will mark this potential bug and investigate it further to see if we can replicate/identify any potential bugs in the calculation method. One thing to point out is that any discounts or savings plans applied can potentially affect the cost forecast you see here vs the final amount you may see in AWS. However, the discrepancy shown here does seem to be pretty large.

As for the missing dates, the message is only making you aware that there are a few days missing from the last 30 day range from the current date that you are viewing the dashboard. You can verify these dates using the dropdown in that same warning box. However, we are actively working to overhaul this feature -- so feel free to check out our project board regarding additional updates: https://github.com/orgs/cloud-carbon-footprint/projects/4/views/4

We'll drop updates regarding the calculations here as we continue to look into it!

**Comment by bgauchon-reply** [comment]
Hello, we found an issue in ```packages/client/src/utils/helpers/transformData.t``` where the comma/point is stripped inducing wrong recommendations.
As another effect we still have to investigate, recommendations states "last 30 days", but amount reported is based on the datarange you may set in main tab / app .env file

**Comment by 4upz** [comment]
@bgauchon-reply Thanks for the update! We can look into that as well. Can you provide an example of an incorrect recommendation resulting from this issue? Feel free to mask any sensitive information.

As for the "last 30 days" of recommendations, the forecast component should be using logic that searches for the last 30 days of data from that configured date range, beginning from today's date. That's why the error in the screenshot occurs, as it warns you if your configured date range is missing days that could affect accuracy. If your date range does not include any data from the last 30 days, then the Forecast will not show and will display a warning that you will need to adjust your range. 

Feel free to confirm if you're not experiencing this along with an example of the date range, current date, and grouping method you're trying.

**Comment by kevinmonvoisin-reply** [comment]
Hi @4upz, below you will find an example of incorrect recommendation:
![image](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/assets/121902923/3bce4355-bf7d-43c3-972a-a0574b46c413)


---

Here, you will find an example of correct recommendation by removing the line that strips the comma/point
![image](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/assets/121902923/706b2e77-74c7-48cf-96cf-89e68fee0a61)

**Comment by bgauchon-reply** [comment]
@kevinmonvoisin-reply
Can you provide a PR for this on the project for both fix you implemented on our packaging ?

**Comment by kevinmonvoisin-reply** [comment]
PR opened here: https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/1155

**Comment by 4upz** [comment]
Thanks for the example @kevinmonvoisin-reply! For more context, I think this was caused partly by a wider related issue with support needed for handling non-USD currencies in the UI. We plan on investigating that some more and addressing it soon as part of https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/1154, which should remove certain bugs such as the wrong currency symbol shown in the screenshot along with any other related formatting issues.

As for this specific issue you're seeing, we appreciate the PR and will give it a review soon!

**Comment by 4upz** [comment]
Completed as part of #1155
