### ISSUE TITLE
 Cannot read properties of undefined (reading 'close')

### ISSUE THREAD

**Issue by HainesFree** [cloud-carbon-footprint/cloud-carbon-footprint#1166]
## Here is my steps:

- git clone repo  -- successfully
- modified the .env file related aws configure in src/packages/api/.env (I only use aws,and i donot care Azure,GCP) 
- yarn install -- successfully
- yarn run start -- error

## Error Msg Details:
`[1] 2023-06-14T10:20:19.931Z [server] info: Cloud Carbon Footprint Server listening at http://localhost:4000 
[1] 2023-06-14T10:24:00.791Z [api] info: Regions emissions factors API request started 
[1] 2023-06-14T10:24:00.804Z [api] info: Footprint API request started. 
[1] 2023-06-14T10:24:00.811Z [Cache] info: Using mongo database... 
[1] 2023-06-14T10:24:00.825Z [Cache] warn: There was an error getting missing dates from MongoDB: ENOENT: no such file or directory, open '/keys/mongodb-certificate.pem' 
[1] 2023-06-14T10:24:00.827Z [Cache] warn: There was an error getting estimates from MongoDB: ENOENT: no such file or directory, open '/keys/mongodb-certificate.pem' 
[1] 2023-06-14T10:24:00.838Z [api] error: Unable to process footprint request.TypeError: Cannot read properties of undefined (reading 'close')`

## The modified details about aws configure of .env attached here:
`
#AWS
#Variables needed for both estimation approaches with AWS:
AWS_TARGET_ACCOUNT_ROLE_NAME= "Operations"
#e.g. ccf-app)
#Variables needed for the Billing Data (Holistic) approach with AWS:
AWS_USE_BILLING_DATA=true
#Optionally set this variable if you want to include or not include from estimation request - defaults to true.
AWS_INCLUDE_ESTIMATES=true
AWS_ATHENA_DB_NAME="ccf-xxx"
AWS_ATHENA_DB_TABLE="democur_xxx"
AWS_ATHENA_REGION= "cn-north-1"
AWS_ATHENA_QUERY_RESULT_LOCATION="s3://cur-cff-xxx"
AWS_BILLING_ACCOUNT_ID="281167xxxxxx"
AWS_BILLING_ACCOUNT_NAME= "ACCOUNT_xxx"

#Cost allocation tags used to group resources, see https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/cost-alloc-tags.html
AWS_RESOURCE_TAG_NAMES=[] # eg. ["user:Environment","user:CostCenter","aws:CreatedBy"]

#Variables needed for the Cloud Usage API (Higher Accuracy) approach with AWS:
AWS_ACCOUNTS=[{"id":"281167xxxxxx","name":"ACCOUNT_xxx"}]

#Optionally set this to "GCP" or "AWS" if your application is deployed to AWS or GCP.
AWS_AUTH_MODE= "AWS"`

**Any ideas? I am really looking forward to your response. Thanks!**

**Comment by 4upz** [comment]
Hi @HainesFree, your configurations for AWS look fine. Did you add any cache-related configurations to your `.env` file? 

It looks like the error references MongoDB-related issues that seem to be auth-related when looking closely at the following lines:

`ENOENT: no such file or directory, open '/keys/mongodb-certificate.pem'`

`[Cache] warn: There was an error getting estimates from MongoDB: ENOENT: no such file or directory, open '/keys/mongodb-certificate.pem'`

If you do have MongoDB configured, you may want to double check that your `MONGODB_URI` value is correct and that it includes a valid path to your auth certificate file.

**Comment by HainesFree** [comment]
Hi @4upz I'm very happy to have received your response. With your help, the problem has been solved! 
Meanwhile, I have another question: if I want to get Rightsizing Recommendation Data, I need to use AWS Cost Explore service. So how to integrate AWS Cost Explore with the cloud carbon footprint project? Which files in the ccf source code do I need to modify?
For example, do I need to modify the .env file? Is there any documentation on integrating with AWS Cost Explore? I would really appreciate your reply. Thanks!"

**Comment by HainesFree** [comment]
I'm very happy to have received your response. With your help, the problem has been solved! 
Meanwhile, I have another question: if I want to get Rightsizing Recommendation Data, I need to use AWS Cost Explore service. So how to integrate AWS Cost Explore with the cloud carbon footprint project? Which files in the ccf source code do I need to modify?
For example, do I need to modify the .env file? Is there any documentation on integrating with AWS Cost Explore? I would really appreciate your reply. Thanks!"

**Comment by 4upz** [comment]
@HainesFree That's great to hear! Glad I could help. I will go ahead and close this issue since the problem has been resolved, but happy to still address any follow-up questions.

If you want to enable recommendations, no modifications are needed. You simply need to ensure that the AWS account that you have configured has the proper permissions to access Cost Explorer data. You can read more about in our documentation [here](https://www.cloudcarbonfootprint.org/docs/recommendations#rightsizing-recommendations). 

The only time you would need to modify any file is if you wish to tweak different recommendations-related configurations in your API or CLI's `.env` file. If you're curious about what those are, they should also be covered in the documentation. Hope that helps!
