### ISSUE TITLE
Syntax error in GCP Query when using multiple tags

### ISSUE THREAD

**Issue by mgriffin-scottlogic** [cloud-carbon-footprint/cloud-carbon-footprint#1205]
- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - Windows 10 (22H2)
- **Browser:**
  - Chrome

### Expected Behavior

When specifying the following environment variable:
`GCP_RESOURCE_TAG_NAMES=["tag:project", "tag:environment"]`
The api is able to successfully complete estimations for GCP data

### Actual Behavior

An error is generated which results in a 500 error (local filepath removed):
```
[1] 2023-08-11T10:38:38.414Z [api] error: Unable to process footprint request.Error: BigQuery create Query Job failed. Reason: invalidQuery, Location: query, Message: Syntax error: Unexpected keyword ON at [23:26]
[1]     at BillingExportTable.createQueryJob (...\cloud-carbon-footprint\packages\gcp\src\lib\BillingExportTable.ts:699:13)
[1]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at BillingExportTable.getUsage (...\cloud-carbon-footprint\packages\gcp\src\lib\BillingExportTable.ts:671:22)
[1]     at BillingExportTable.getEstimates (...\cloud-carbon-footprint\packages\gcp\src\lib\BillingExportTable.ts:92:23)
[1]     at Object.getCostAndEstimates (...\cloud-carbon-footprint\packages\app\src\App.ts:81:27)
[1]     at async Promise.all (index 0)
[1]     at getEstimatesForMissingDates (...\cloud-carbon-footprint\packages\app\src\Cache.ts:119:11)
[1]     at App.descriptor.value (...\cloud-carbon-footprint\packages\app\src\Cache.ts:71:24)
[1]     at FootprintApiMiddleware (...\cloud-carbon-footprint\packages\api\src\middleware.ts:59:31)
```

### To Reproduce

Specify the given environment variable in your `packages/api/.env` file, along with valid environment variables to connect to a GCP account. The tags specified do not need to exist and your cache should either be empty or not cover the period set in `packages/client/.env` (`REACT_APP_START_DATE` & `REACT_APP_END_DATE`). Run `yarn start` and wait for the browser to request data.

### Additional Information

I have a local fix for this in `packages/gcp/src/lib/BillingExportTable.ts` but it doesn't break any tests by changing the query produced. I'm not sure what would be the preferred way to test this as validating the entire query passed to `mockCreateQueryJob` seems like it would be overly brittle and sensitive to further changes. I'm really interested in validating the output of `BillingExportTable.buildTagQuery`, which is a private function. Would it be acceptable to make this a public method to test in isolation? If not, what would be your preference in how to approach it?

**Comment by mgriffin-scottlogic** [comment]
I've also discovered a few more issues with querying project and resource labels, which I don't know whether they could be rolled into the same fix or would want separate issues (tagNamesToQueryColumns results are used in wrong order, 'project.label' is used instead of 'project.labels' in buildTagQuery and the joins are always done on tags.key not ${columnName}.key).

**Comment by 4upz** [comment]
@mgriffin-scottlogic Thanks for opening this issue!

I'm having a bit of trouble replicating it on my end, as I seem to still be able to get estimates when using multiple configured tags when both using the `tag:` prefix or a combination of multiple tag, labels, or project label prefixes. However, the error that you have copied definitely makes it seem like an error resulting from generated query.

Feel free to open a PR with your proposed changes, perhaps it'll further illustrate the issue. You're welcome to also make the functions public if it makes testing easier. We did a similar thing for AWS' tag builder, but skipped it for this one since we thought the cases were covered by modifying the preceding test cases. You're welcome to include the project and resource labels into the same fix, as long as  the commits are properly separated.

**Comment by mgriffin-scottlogic** [comment]
Hmm, that's interesting that you don't see a problem - I don't know much about GCP/BigQuery but could there possibly be some different version/mode where it allows the format? Looking at the generated query it seemed to have a problem with:

`ON tags.key = "project" OR ON tags.key = "environment"`

But it was fine if I changed it to:

`ON tags.key = "project" OR tags.key = "environment"`

I'll have a look at the AWS tag builder and see about starting a PR, thanks 🙂

**Comment by 4upz** [comment]
@mgriffin-scottlogic Sorry about that, I was finally able to replicate it. That was a configuration error on my part. I'm indeed seeing the same thing with the second "ON" being included for the next tag. 

I think your solution will do the trick. Looking forward to your PR! 🚀
