### ISSUE TITLE
CLI tries to create .csv file with invalid characters on Windows

### ISSUE THREAD

**Issue by mgriffin-scottlogic** [cloud-carbon-footprint/cloud-carbon-footprint#1208]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - Windows 10 (22H2)
- **Browser:**
  - Chrome

### Expected Behavior

When using the cli to output a .csv file, it should work on any OS

### Actual Behavior

On Windows, the filename includes the time, with hours, minutes and seconds separated with colons (:). This is an invalid character for Windows file names, and results in the following confusing message when attempting to write: `ENOENT: no such file or directory, open 'C:\output_folder\results-2020-08-05-20:41:31.csv'`

### To Reproduce

Either use CLI on Windows or run `yarn test` from the root directory, `packages\cli\src\__tests__\csv.test.ts` will be one of the failing tests.

### Additional Information

This is one of the failing tests that prevents me from going through the full pre-commit verification process when making Pull Requests.

**Comment by 4upz** [comment]
Should be fixed with https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/commit/34bbb79aebeb29a518d114c94332283b00e287f9 and is queued for the next release. @mgriffin-scottlogic Thanks for bringing this up! If you notice any other Windows-related issues, or anything else in general, please don't hesitate to let us know
