### ISSUE TITLE
Application giving 404 error

### ISSUE THREAD

**Issue by sonakp** [cloud-carbon-footprint/cloud-carbon-footprint#1233]
### Preflight Checklist

- [ ] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - 
- **Browser:**
  - 

### Screenshots
We download the application and locally installed it using the steps giving in the official document. We are using the AWS cloud for the carbon emission footprint. The keys are having correct permissions.
When i run the application using yarn start command and open the application using http://localhost:3000,it is routing to error page
and the application is not working. Please can you help with the application.

![image](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/assets/33562103/50540613-fa04-469d-b8e2-d29fc0a441a7)

### Additional Information

© 2021 Thoughtworks, Inc.

**Comment by camcash17** [comment]
Hi @sonakp, thanks for raising this issue! Would you mind restarting the application using two separate terminal windows, running `yarn start-api` in one and `yarn start-client` in the other? When looking at the API terminal window, you may get a more specific error message that you could share here!

**Comment by sonakp** [comment]
Hi @camcash17 , attaching the screenshot .I don't see any error in the API terminal window .Please find it below.

![image](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/assets/33562103/5ef43874-925e-4a09-afd5-86a54c637c68)

![image](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/assets/33562103/f28cd646-4378-47c9-8eb9-65183bac71ab)

Thanks&Regards,

**Comment by sonakp** [comment]
Hi @camcash17 , I don't see any error for API terminal window. Please find the screenshot below.

![image](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/assets/33562103/acf8a0c4-fb5a-469f-94f9-985e3f2ebf33)


![image](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/assets/33562103/508c7573-74eb-41b9-b3ba-ee34d19740d1)


Thanks&Regards

**Comment by camcash17** [comment]
Interesting... just as a sanity check, could you please try removing the `/error` path from the browser url and reloading just `localhost:3000`?

Also, you could try the URL - `http://localhost:4000/api/footprint?start=YYYY-MM-DD&end=YYYY-MM-DD&groupBy=day`
(replace the dates with your actual dates, maybe try `start=2023-08-29&end=2023-08-30`)

**Comment by sonakp** [comment]
I removed the /error and tried ,but it redirects to /error page . 

The URL -http://localhost:4000/api/footprint?start=2023-08-29&end=2023-08-30)&groupBy=day does return data when i try from the web browser . 

Another thing , does the "yarn start-client" run on port 4000,in my case i have another application running on that due to which this opens up on 4001 ,but that should not be problem i think.

Thanks&Regards

**Comment by camcash17** [comment]
The API runs on port 4000, and the client runs on port 3000. When you have both running in separate terminal windows and load the client in the browser on http://localhost:3000, when you are directed to the error route, are you able to see an error message in either terminal window?

**Comment by sonakp** [comment]
No i don't see any error . The above screenshot show the same .

**Comment by camcash17** [comment]
I'm wondering if it may have something to do with the fact that your API is running on port 4001 instead of 4000. Would you mind trying to kill any running process? Can try `killall node`, then restart both.

**Comment by sonakp** [comment]
I tried "taskkill /im node" ,it gave the error "ERROR: The process "node" not found". Even after i stop the other application running on nginx at port 4000 and run the command "yarn start-api" it defaults to port 4001 port . Below is the screenshot of the same. Can you help with some link of video recording of the installation.

![image](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/assets/33562103/9e8a974d-4bc7-42da-aafa-a06dcf5b48e6)

**Comment by camcash17** [comment]
Thanks @sonakp! You'll notice that in our `api/server.ts` [file](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/4e5a17e29335e6b42da8e42ad6cf2bab8704b874/packages/api/src/server.ts#L19), we have `const port = process.env.PORT || 4000`. Also, in the `client/package.json` [file](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/4e5a17e29335e6b42da8e42ad6cf2bab8704b874/packages/client/package.json#L53), we have defined, `"proxy": "http://localhost:4000"` to communicate with the API.

You said you were able to see data at the endpoint: `http://localhost:4000/api/footprint?start=2023-08-29&end=2023-08-30)&groupBy=day`, which would suggest this server is listening on port 4000.

Could you please check to see if you have configured a `PORT` env variable globally?

**Comment by camcash17** [comment]
Closing this for now as the conversation has gone stale. Please reach out for more questions!
