### ISSUE TITLE
Updates Electricity Maps Calculation

### ISSUE THREAD

**Issue by ccasher** [cloud-carbon-footprint/cloud-carbon-footprint#1266]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Currently in the Electricity Maps calculation, we have the wrong conversion of the carbon intensity for grams to metric tons. Instead of dividing by 1000, we need to divide by 1000000, or e-6.

- **Operating System:**
  - 
- **Browser:**
  - 

### Expected Behavior

The calculation for electricity maps carbon intensity should be correct.

### Actual Behavior

The calculation for electricity maps carbon intensity is off by 3 decimals.

### Additional Information

© 2021 Thoughtworks, Inc.

**Comment by 4upz** [comment]
Should be fixed with https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/commit/44a12fc577c7e4b44e3f185a80bfce9a68eff7df
