### ISSUE TITLE
index.html no longer in /var/www

### ISSUE THREAD

**Issue by PreNoob** [cloud-carbon-footprint/cloud-carbon-footprint#1280]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
- **Container Image:**
`cloudcarbonfootprint/client:release-2023-11-13` 
- **Operating System:**
N/A 
- **Browser:**
N/A

### Expected Behavior
Similar to the `cloudcarbonfootprint/client:release-2023-10-17` image, the image  `cloudcarbonfootprint/client:release-2023-11-13`  should have the  `index.html` present in `/var/www`.

### Actual Behavior
The `index.html` is not present. See comparison below:

```shell
❯ docker run --rm -it --entrypoint ls cloudcarbonfootprint/client:release-2023-10-17 -- "/var/www"
asset-manifest.json  favicon.ico          index.html           robots.txt           static

❯ docker run --rm -it --entrypoint ls cloudcarbonfootprint/client:release-2023-11-13 -- "/var/www"
App.d.ts             Config.js.map        Root.js              common               lib.d.ts             setupTests.d.ts
App.js               ConfigLoader.d.ts    Root.js.map          index.d.ts           lib.js               setupTests.js
App.js.map           ConfigLoader.js      Types.d.ts           index.js             lib.js.map           setupTests.js.map
Config.d.ts          ConfigLoader.js.map  Types.js             index.js.map         package.json         utils
Config.js            Root.d.ts            Types.js.map         layout               pages

```

### To Reproduce
`docker run --rm -it --entrypoint ls cloudcarbonfootprint/client:release-2023-11-13 -- "/var/www"`

### Screenshots
See above

### Additional Information
See above

© 2021 Thoughtworks, Inc.

**Comment by 4upz** [comment]
Hi @PreNoob thanks for opening this issue. There was an issue with this release that was fixed with the latest release as noted in #1272. This served as a nice reminder that the image could still be pulled, so we removed this release tag from DockerHub. For continued use, please use the latest image or a prior release
