### ISSUE TITLE
CCF returns different carbon emission values for the readings taken on different days

### ISSUE THREAD

**Issue by PadmarajBhat** [cloud-carbon-footprint/cloud-carbon-footprint#1293]
- [ x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  Windows 10 (1803) 
- **Browser:**
  Microsoft Edge

### Expected Behavior

CCF should return same carbon estimation for a period . Even after multiple restart of the server, the json cache should yield same carbon emission for the past dates.

### Actual Behavior

Carbon usage chart shows different values for the same observation period for 2 readings taken on 2 different days. 

i.e. Emission period : Nov 2023
Emission Noted Date : 29 Nov 2023
Cumulative Carbon Emission: 3.1 metric tons (for 29 days)

Emission period: Nov + 13 days of Dec 
Emission Noted Date: 13 Dec 2023
Cumulative Carbon Emission:  2.9 metric tons (for 45 days.)

### To Reproduce

Run CCF on 2 different days

### Screenshots
Nov 29 , 2023:
![image](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/assets/29166528/e383051f-0ead-4b62-8111-ae7b7cc34eaf)
![image](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/assets/29166528/18528832-c42d-46a9-a673-515dc5d3d8cd)

Dec 13, 2023:
![image](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/assets/29166528/d0f4f308-1735-40a3-bbcd-6b4e7836f0b9)
![image](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/assets/29166528/ddc17552-6ac2-44ca-a3d5-90ee04dd2a1e)

Dec 29, 2023:
![image](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/assets/29166528/ea78a106-4caa-4efe-b7ee-eed506e5326a)

![image](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/assets/29166528/f02311d2-4e89-4cdb-b30f-52a6c4bcdefe)

**Comment by PadmarajBhat** [comment]
@4upz : Could you please address this issue as well. We have initially escalated these 2 issues over mail. Created the 2nd one just now. Are we missing any configuration ?

**Comment by PadmarajBhat** [comment]
@4upz : Could you please show some light here ? :)

**Comment by 4upz** [comment]
Hi @PadmarajBhat I am looking into replicating this and will share insights soon

**Comment by 4upz** [comment]
Thanks for your patience @PadmarajBhat. This seems to be weird behavior that occasionally occurs as a result of #1281. I was able to replicate it and the cache data remains the same, but the client is aggregating the totals for the results incorrectly due to duplicate values. Although the decrease in the cumulative numbers shown for your first two comparison images is a bit erratic, allow me to work on a fix for that issue and circle back to this one to see if the fix either inherently solves this one or sheds further light on a different issue that may be contributing to this.

**Comment by 4upz** [comment]
We've just pushed up a fix for the client-side bug that we mentioned. Feel free to pull down the recent changes and let us know if you see different behavior.

Your estimate totals displayed in the dashboard should be more consistent, but I'd be interested in knowing if you still see behavior where the cumulative totals are decreasing as you add more days

**Comment by 4upz** [comment]
@PadmarajBhat Closing this for now since I haven't heard back and unable to replicate it after the referenced fix. But feel free to leave a message if you still see this occurring, and I'd be happy to reopen and look at it further.

**Comment by PadmarajBhat** [comment]
@4upz :We have scheduled run of CCF on every month last working day as the tool is capable of pulling only current month data.

Today, we took the latest code and ran CCF. The chart is unusual. Not sure, if the Azure has improved drastically or it is CCF issue. Please comment.

![image](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/assets/29166528/47f355e8-e52e-45ff-b49e-8c650f3faf58)

**Comment by 4upz** [comment]
@PadmarajBhat That's certainly unusual. The issue we discussed above was UI-related but shouldn't have affected your cache or previously stored estimates. If you're sure that you have not modified any Azure services/resources recently that could result in a reduction of usage, then troubleshooting would require additional details/visibility. I would recommend taking a look at the logs of your API. Do you notice any warnings regarding services being skipped during the last request? Or any other errors?

You could also look to see if a service inside of your cache is showing the same drop in numbers between two different dates. This could help verify if these differences are being returned from the Azure API, is occurring during estimation, or on the front-end.

**Comment by PadmarajBhat** [comment]
@4upz : I remember seeing such drastic changes in chart last month also. However, when we restarted the CCF ; the new lower value were generalized for older date. With the new code, no matter how many times we restart it does not change. Chart remains the same.

I think fundamental issue is that 

Nov 29:  average Emission was 0.108 metric ton, 
Dec 29 : 0.072
Jan 31: 0.005 (appr)

Every month average emission is decreasing though there are no changes in the **production** system.  There are  weekend should down operations at **Dev & QA system** but they are very minor part of the total emission. Here, in the chart, average emission itself is low.

**Comment by 4upz** [comment]
@PadmarajBhat Yes, I've noticed the decrease in averages based on your initial post and the most recent image you've posted. It's good that the latest pull has caused numbers for the old data to now be unaffected, but it is unusual that the new numbers are. I think the important part is to isolate which aspects of the application may be contributing to this issue (i.e. azure's api response, estimation logic, cache storage, or dashboard).

Since we're unable to replicate this issue on our end and are also using a different Azure Enterprise account type, I'm a bit limited in ability to troubleshoot on my end. Have you tried any of the recommended troubleshooting steps from my previous message?

**Comment by 4upz** [comment]
@PadmarajBhat Just wanted to give this a friendly bump to see if you've had any luck or a chance to check out my most recent message.

Since this issue is stale, I'll go ahead and close it. I'm happy to open it again if it warrants further investigation
