### ISSUE TITLE
Filename issue on lookup tables

### ISSUE THREAD

**Issue by DiegoDeMauro** [cloud-carbon-footprint/cloud-carbon-footprint#1303]
### Preflight Checklist

- [ ] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - 
- **Browser:**
  - 

Ubuntu Cli

### Expected Behavior

Yarn Create Azure input

### Actual Behavior

Error:

node:internal/modules/cjs/loader:1146   throw err;   ^  Error: Cannot find module './CreateAzureInput.ts' Require stack:

### To Reproduce

Just use Guided install, than try to create the input csv

### Additional Information

the file referenced in Yarn script have a capital C, but the script itself is lower c. renaming it to CreateAzureInput.ts' in cli src folder fixed.

© 2021 Thoughtworks, Inc.

**Comment by 4upz** [comment]
@DiegoDeMauro-Navigator Thanks for calling this out! You're absolutely right, this must've slipped through due to the case insensitivity that Macs have with filenames. S/O to Linux for holding us accountable 😅 

Since it's a straightforward fix, would you be interested in submitting a PR for this?

**Comment by DiegoDeMauro** [comment]
> @DiegoDeMauro-Navigator Thanks for calling this out! You're absolutely right, this must've slipped through due to the case insensitivity that Macs have with filenames. S/O to Linux for holding us accountable 😅
> 
> Since it's a straightforward fix, would you be interested in submitting a PR for this?

Thanks for the quick repply, but unfortunatly I have no idea how to do so. :)

**Comment by 4upz** [comment]
@DiegoDeMauro-Navigator I think Github has some [documentation here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to do. 

But also not a problem if you're unable to, just like to provide opportunities for contributions/credits 🙂. We're happy to push up a fix for this

**Comment by 4upz** [comment]
Fixed with https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/commit/ec34e4d461ff4190002e040bb106d65c9c5965e9
