### ISSUE TITLE
Emission calculation for Azure SaaS services using CCF

### ISSUE THREAD

**Issue by shivansh-0808** [cloud-carbon-footprint/cloud-carbon-footprint#1318]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - 
- **Browser:**
  - 

### Expected Behavior

trying to get the footprint data for all the services that we are using on Azure. CCF Footprint API should provide emission details for all the services running on our Azure cluster .

### Actual Behavior

 While trying to get emission details, we are getting emission data for limited set of resources like Virtual machines, etc. But not able to get the emission data for SaaS services like Azure Event Hub, Azure Blob, Azure cloud elastic etc.

### To Reproduce

try to get footprint details for one of the Azure subscriptions which has both Virtual machines as well as other SaaS services like Azure blob , Azure cloud elastic , etc.

### Additional Information

© 2021 Thoughtworks, Inc.

**Comment by ccasher** [comment]
Hi @shivansh-0808, thanks for submitting this issue! 🫡 Curious to see if you are getting any outputs that might provide additional information (ie is the data being entirely omitted, or are there any error logs? ...etc). We can try to replicate, though unfortunately we have limited access with Azure and are undergoing an API migration so any additional information would be very helpful.

**Comment by shivansh-0808** [comment]
> Hi @shivansh-0808, thanks for submitting this issue! 🫡 Curious to see if you are getting any outputs that might provide additional information (ie is the data being entirely omitted, or are there any error logs? ...etc). We can try to replicate, though unfortunately we have limited access with Azure and are undergoing an API migration so any additional information would be very helpful.

Hi @ccasher , i have replied to google group discussion https://groups.google.com/g/cloud-carbon-footprint/c/U-zptezUSUw , could you please reply to the query.Thanks

**Comment by ccasher** [comment]
Hi @shivansh-0808, could you please provide an example of any services you are seeing that are not supported (feel free to scrub any sensitive data). This issue might be due to a lack of visibility our team has with Azure usage and services, so my best guess is that we aren't able to handle all the Saas services properly and the logic is getting run through our Unknown Estimator.

**Comment by 4upz** [comment]
Hi @shivansh-0808 are you still encountering this issue and have you had a chance to look at @ccasher's last query?

**Comment by 4upz** [comment]
Closing due to the issue being marked as resolved in the Google group discussion
