### ISSUE TITLE
Use nginxinc/nginx-unprivileged for a more secure and hardened container

### ISSUE THREAD

**Issue by lukibahr** [cloud-carbon-footprint/cloud-carbon-footprint#1322]
To run the container in a kubernetes environment, client container must be run with root privileges due to nginx. 
In a secured kubernetes environment, this leads to pods blocked by policies due to security restrictions. 

In general, it is highly recommended to run containers with dropping capabilities to avoid security issues.

## Feature Suggestion
To run the container more securily, I would recommend to use nginxinc/nginx-unprivileged. This requires to use the container image in the Dockerfile in packages/client, as well as setting a valid path to the nginx.pid because we overwrite the nginx default config.

**Describe the solution you'd like**

The Dockerfile for packages/client should look like this:

```Dockerfile
FROM node:18-alpine as build
WORKDIR /app
COPY ./package.json ./package.json
COPY ./build /app/build

RUN yarn install --immutable

FROM nginxinc/nginx-unprivileged:1.25 #use nginxinc/nginx-unprivileged
COPY --from=build /app/build /var/www
CMD ["nginx", "-g", "daemon off;"]
```

The nginx.conf should look like the following:

```conf
events {
}

pid /tmp/nginx.pid; # use custom path to pid *(1)

http {
    server {
        listen 8080; # set port 8080 instead of 80
        include /etc/nginx/mime.types;
        root /var/www;
        index index.html index.htm;
        location /api {
            resolver 127.0.0.11 ipv6=off;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://api:4000$request_uri;
        }
        location / {
            try_files $uri $uri/ =404;
        }
    }
}
```

**Additional context**
I've built and tested the container locally. The image for testing can be found here: docker.io/lukasbahr/ccfclient/latest-amd64

## Possible Implementation
I'll create a MR for this.

**Further reading***
- *(1) https://github.com/nginxinc/docker-nginx-unprivileged?tab=readme-ov-file#troubleshooting-tips
- https://hub.docker.com/r/nginxinc/nginx-unprivileged

**Comment by CodeMartian** [comment]
Closing this based on the PR being merged in.

**Comment by lukibahr** [comment]
@CodeMartian will the updated image be published in dockerhub? Can't find a newer container image than release-2024-02-11

**Comment by 4upz** [comment]
@lukibahr Sorry, container images are published per release. We just did a release over the weekend, so you should see a new image on DockerHub with your changes. Thanks for your patience on this

**Comment by Joleene1234** [comment]
We do not know where to live. Can someone buy us a house?
