### ISSUE TITLE
Configuration options should be documented on microsite

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#177]
## Acceptance Criteria
- [x] When I am on the microsite docs page, I see a section for `Configuration Options` under the `Running Locally` section
- [x] When I am on the microsite docs page, I see the `Performance Configurations` page in the `Configuration Options` section
- [x] When I am on the microsite docs page, I see a page `Configurations Glossary`
- [x] When I click on the `Configurations Glossary` page, I see a list of all the config options and a description of the purpose and how to use them
- [x] Distinguish server side vs client side
- [x] Distinguish billing data vs api approach vars

## Tech Tasks
- [x] Run Changesets, bump any packages that have been updated/changed

**Comment by dtoakley-tw** [comment]
I updated this with a lot more detail: https://www.cloudcarbonfootprint.org/docs/configurations-glossary

Moving to Done.
