### ISSUE TITLE
Compare CCF Azure with results from Sustainability Calculator

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#186]
- [ ] See spreadsheet shared by Mark
- [ ] Determine if we need access to the `underlying data`
- [ ] Determine discrepancies in their scope 3 vs ours

**Comment by dtoakley-tw** [comment]
I've added a new tab in the same spreadsheet called "CCF Emissions for 2021", that shows the top emissions from cloud-carbon-footprint and the % difference with the Sustainability Calculator. They are in the same order of magnitude, which is a good sign, but CCF estimates are higher. Let's discuss @ericksod -- there could me many reasons for this!
