### ISSUE TITLE
Unclear what "Enter GCP account id:" refers to

### ISSUE THREAD

**Issue by steren** [cloud-carbon-footprint/cloud-carbon-footprint#207]
In the yarn interactive setup, it's unclear what is asked by "Enter GCP account id:"

Is it the billing account ID? 
Is it the project ID?

**Comment by dtoakley-tw** [comment]
Hi @steren -- good question/feedback, this is a little confusing. It is the Project ID that your Service Account exists in that has permission to query Billing Data using BigQuery.

I've updated the prompt, and we now have this a bit better documented here: https://www.cloudcarbonfootprint.org/docs/configurations-glossary#variables-needed-for-the-billing-data-holistic-approach-with-gcp

It is still a bit confusing though, as the underlying environment variables are still `GCP_BILLING_ACCOUNT_ID/GCP_BILLING_ACCOUNT_NAME` -- but that will be a larger change that maybe we can handle in a separate issue?

**Comment by dtoakley** [comment]
Closing this one off for now -- we have another issue to rename the env variables!
