### ISSUE TITLE
"Enter BigQuery table name" should probably be "dataset"

### ISSUE THREAD

**Issue by steren** [cloud-carbon-footprint/cloud-carbon-footprint#208]
In the yarn interactive editor, I am asked:
"Enter BigQuery table name"

Should I actually enter the **dataset** name that I configured in https://cloud.google.com/billing/docs/how-to/export-data-bigquery-setup#enable-bq-export ?

**Comment by dtoakley-tw** [comment]
Hi @steren -- thanks for this feedback! The BigQuery table name is determined using three values: _project.dataset.BQ_table_name_ Source: https://cloud.google.com/billing/docs/how-to/bq-examples

I've updated the configuration glossary to specify this, and link to Google's docs: https://www.cloudcarbonfootprint.org/docs/configurations-glossary/#variables-needed-for-the-billing-data-holistic-approach-with-gcp

**Comment by ericksod** [comment]
@steren Closing this for now, but please let us know if you see other improvements, and we can reopen. Thanks!

**Comment by ChrisChinchilla** [comment]
@steren and @dtoakley-tw I hit this same confusion and spent hours trying to figure it out until I found this issue… So I think maybe while the doc linked above is useful, perhaps also the interactive installer needs updating as that's many people's first steps?
