### ISSUE TITLE
Include a replication factor in the Storage estimation

### ISSUE THREAD

**Issue by github-benjamin-davy** [cloud-carbon-footprint/cloud-carbon-footprint#211]
When paying for a certain amount of usable storage we know that the actual volume stored on the cloud provider infrastructure is at least a multiple of this volume due to availability concerns.

For example for AWS we can assume the following:
- S3 - Replication factor: 3 - justification "Designed to sustain the concurrent loss of data in two facilities"
- EBS - Replication factor: 2 - justification "When you create an EBS volume, it is automatically replicated   within its Availability Zone"
- EFS - Replication factor: 3 - justification "By default, every Amazon EFS file system object (i.e. directory,   file, and link) is redundantly stored across multiple AZs for file systems using Standard storage classes"

Hence the storage estimation model could include this factor to get an estimation that is closer to reality (network traffic due to this replication mechanism is another open question).

In this case, 10 GB of usable S3 storage becomes 30 GB of raw storage required to provide the service.

**Comment by ericksod** [comment]
@benjamindavyteads This is great, thanks for pointing it out. I think this can be on our short/medium roadmap, so I've created another ticket with a start of checklist items we'll do https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/232
I'm going to close this one out but feel free to reopen if we missed something or comment on the checklist ticket
