### ISSUE TITLE
[SPIKE] Explore options for improving SEO

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#220]
#### Overview
We would like to do everything we can to ensure our microsite is one of the top options when people are searching for things related to carbon emissions in the cloud.
This ticket will be to research and explore things we may be able to do to improve our SEO, (eg metadata)
## Acceptance Criteria
- [x] Explore options for improving SEO
- [x] Pull out separate tickets for any larger tasks

## Tech Tasks
- [x] Run Changesets, bump any packages that have been updated/changed

## Review Tasks
- [x] eg. specific QA details, update methodology, or update microsite

**Comment by ghost** [comment]
If possible use keywords on each element:

- H1, H2, H3 in order for each content

- Title metadata (shorter than 60 characters)

- Description metadata (one or two full sentences 50–160 characters)
<meta name="description" content="Here is a precise description of my awesome webpage.">

- Keyword metadata (phrase consisting of 1-4 words)

- Relevant descriptive links (with keywords if possible)

- Alt tags on images

- Wrap with <div id=“what-we-are-telling”> every section

- Improve page speed (https://developers.google.com/speed/pagespeed/insights/)

**Comment by dtoakley** [comment]
@roberto-thoughtworks to make a single issue with these items as a checklist.
