### ISSUE TITLE
[SPIKE] GCP Recommendations API

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#238]
#### Overview
With our ultimate aim of helping organizations to reduce their carbon impact from the cloud, we would like to begin exploring the different resources available for generating recommendations. This card explores the GCP api.
## Checklist
- [x] Test out GCP recommendation api with internal data
- [x] What options do we have - can we run it for specific accounts? specific services? regions?
- [x] What categories of recommendations will it give us?
- [x] Document on how we can use this recommendations API
- [x] Test out the GCP recommendations API with a broader set of projects
- [ ] How can we calculate the carbon impact and cost savings?
- [ ] Are there other GCP related recommendations options?

## Review Tasks
- [ ] eg. specific QA details, update methodology, or update microsite

Documentation:
Please create a new doc in the Spikes folder (or add on to the AWS existing doc)

**Comment by ccasher** [comment]
https://docs.google.com/document/d/1cnbuk0SZJ6mTdagienWkt5bv1G3BbULqzmhRvh0BazE/edit

**Comment by ghost** [comment]
Documentation for this spike has been moved here: https://drive.google.com/file/d/14sncJ9aYzvnK9CCN6WNRKQ9_RJDrakL7/view?usp=sharing

The NodeJs script to get recommendations is here:
https://github.com/ThoughtWorks-Cleantech/green-spike/blob/trunk/gcp/recommender-api.js

Next steps:
- We should try with a service account (from a GCP account with more active services) to get more recommendations from API and see what can we do with them. We have been talked with Mark Richter to get this new service account for testing proposes.

**Comment by dtoakley** [comment]
I have updated the spike code with a WIP implementation that supports all GCP projects, Zones and Recommendations Ids. There is some serious performance tweaking to be done - currently the script takes way to long to load all projects given the rate limits for the recommendations API, but there are few ways we can improve this with throttling, etc. When it goes to implementing this in the main application however, we should consider alternative approaches, like Cloud Tasks.
