### ISSUE TITLE
[SPIKE] Azure recommendations

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#239]
#### Overview
With our ultimate aim of helping organizations to reduce their carbon impact from the cloud, we would like to begin exploring the different resources available for generating recommendations. This card explores the options for Azure.
## Checklist
- [x] Is there an Azure recommendation api?
- [ ] What options do we have - can we run it for specific accounts? specific services? regions?
- [ ] What categories of recommendations will it give us?
- [ ] Document on how we can use this recommendations API
- [ ] How can we calculate the carbon impact and cost savings?
- [ ] Are there other Azure related recommendations options?

## Review Tasks
- [ ] eg. specific QA details, update methodology, or update microsite

Documentation:
Please create a new doc in the Spikes folder (or add on to the AWS existing doc)

**Comment by ghost** [comment]
This is a work in progress.

Link to documentation:
https://docs.microsoft.com/en-us/rest/api/advisor/recommendations/list

Script to get recommendations (it's not working yet)
https://github.com/ThoughtWorks-Cleantech/green-spike/blob/trunk/azure/recommendation-api.js

**Comment by ccasher** [comment]
https://docs.microsoft.com/en-us/azure/architecture/gcp-professional/services#data-warehouse

https://docs.microsoft.com/en-us/azure/synapse-analytics/get-started
