### ISSUE TITLE
Implement Memory estimations for GCP

### ISSUE THREAD

**Issue by dtoakley** [cloud-carbon-footprint/cloud-carbon-footprint#243]
As a user of Cloud Carbon Footprint, I would like to have energy and carbon estimations for memory usage included in in my total estimates using GCP Billing Export data. 

Acceptance Criteria:
-  When I pull GCP energy and carbon emissions estimates via the API or CLI, they include estimates for memory usage, just like other cloud usage types.

Tech Tasks:
- [x] A New MemoryEstimator class is created that implements IFootprintEstimator interface
- [x] The MemoryEstimator class implements the estimate function, utilizing the current agreed coefficient of 0.000392 kWh / GB
- [x] A new MemoryUsage data class is created that extends IUsageData, that is passed to the new estimate function
- [x] MemoryEstimator object is added as a dependency to the BillingExportTable constructor 
- [x] The BillingExportTable getEstimates function is updated to handle estimates for memory, when the usage type is memory. 
- [x] Any potential re-factoring is done

**Comment by ccasher** [comment]
Want to confirm if we can update some of the unsupported usage types that might be memory-related
