### ISSUE TITLE
When no API env variables set, it writes empty data

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#246]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](../../CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - 
- **Browser:**
  - 

### Expected Behavior

- [x] When there are no env variables set and an API call is made, there is no data written to the estimates.cache.json file

### Actual Behavior

When there is no api/.env variables set, then API still writes to the estimates.cache.json file, but with empty data. So on subsequent requests, it looks like there is no data, but it's just a config issue, and you need to re-delete the estimates cache. 

### To Reproduce

Delete estimates.cache.json file, and comment out all api/.env variables, then make a request for any date range. The estimates cache will then exist, with empty data. It shouldn't be written to at all.

### Additional Information

© 2021 ThoughtWorks, Inc.

**Comment by dtoakley** [comment]
Nice looking good! Thanks @roberto-thoughtworks Closing
