### ISSUE TITLE
Implement Memory estimations for AWS

### ISSUE THREAD

**Issue by aalva05-tw** [cloud-carbon-footprint/cloud-carbon-footprint#251]
As a user of Cloud Carbon Footprint, I would like to have energy and carbon estimations for memory usage included in in my total estimates using AWS Cost and Usage Reports data. 

Acceptance Criteria:
-  When I pull AWS energy and carbon emissions estimates via the API or CLI, they include estimates for memory usage, just like other cloud usage types.

Tech Tasks:
- [ ] MemoryEstimator object is added as a dependency to the CostAndUsageReports constructor 
- [ ] The CostAndUsageReports getEstimates function is updated to handle estimates for memory, when the usage type is memory. 
- [ ] Any potential re-factoring is done

**Comment by ccasher** [comment]
Notes:
- GCP memory calculation returns very high kilowatt hours (gigabyteHours * memory coefficient)
   - update calculation
- Updated average formula in constants file
   - Add unit tests 
- Move logic from memory estimator and add PUE
