### ISSUE TITLE
Improve performance of acceptance tests for local development pre-commit hook

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#278]
#### Overview
Our tests currently take awhile to run, so we would like to reduce that time and improve the performance.
## Acceptance Criteria
- [x] When I run the tests, it takes less time than previously

## Tech Tasks
- [x] Fix integration tests
- [x] Improve integration test performance
- [x] Re add the integration test to the pre-commit hook
- [ ] Explore use of docker (see ticket #164 for details)
- [x] Run Changesets, bump any packages that have been updated/changed

## Review Tasks
- [x] eg. specific QA details, update methodology, or update microsite

**Comment by dtoakley** [comment]
I've made what I think to be some improvements and re-added the integration tests to the pre-commit hook:
- Added `await t.maximizeWindow()` to the test that kept failing. After debugging it seems testcafe couldn't find the elements in the DOM, and this seems to fix it. We can revisit if they start failing again...
- Prior to re-adding them, the pre-commit hook was taking ~1 minute, now it's ~2 minutes - so there is a performance hit from re-adding them. If this isn't performant enough, we can continue finding was to improve the tests speed.
