### ISSUE TITLE
Update methodology to use Azure convention for regions

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#280]
#### Overview
Currently our methodology appendix has the emissions factors per region for each cloud provider. Azure's does not fully match what is on their website: https://azure.microsoft.com/en-us/global-infrastructure/geographies/
We would like to make sure these match.
## Acceptance Criteria
- [ ] When I view the Azure regions on the microsite methodology writeup in the Appendix, the naming convention is the same as on Azure's website https://azure.microsoft.com/en-us/global-infrastructure/geographies/

## Tech Tasks
- [ ] Run Changesets, bump any packages that have been updated/changed

## Review Tasks
- [ ] eg. specific QA details, update methodology, or update microsite

**Comment by davidmytton** [comment]
I'm looking at this issue as potential for my first contribution to this project and just wanted to clarify what change(s) you're expecting.

Currently the Azure Region naming doesn't match, for example `US Central` as defined in the regions definition file https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/69a6e7ac49ae3d646a9747c09b912cd9bc3c762f/packages/core/src/services/azure/AzureRegions.ts#L16 is referenced by Microsoft at https://azure.microsoft.com/en-us/global-infrastructure/geographies/ as `Central US`.

Would you like those values to match as well, or just the "Region" column of the Methodology Appendix at  https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/microsite/docs/Methodology.md#azure-2 ?

**Comment by ericksod** [comment]
Hi David! For now we would just like to update the current supported regions shown in the appendix of the Methodology.md file to have the Azure naming convention used by Microsoft (we'll add additional regions in there as we add support).  The challenge with changing it in the actual codebase is that there isn't consistency in what Azure returns for the regions for different APIs and it isn't always that standard convention they show on their global infrastructure map, so rather than do a mapping, for now we'll leave that AzureRegions.ts file as is. Let us know if you have further questions!
