### ISSUE TITLE
Extract cloud providers into separate package(s)

### ISSUE THREAD

**Issue by aalva05-tw** [cloud-carbon-footprint/cloud-carbon-footprint#296]
### Context
As we look toward adding in recommendations, we will have a further need for specific treatment for each cloud providers. They all operate slightly differently, so we would like to organize the codebase to increase our separation of concerns and extensibility to add additional cloud providers or provider specific API calls or logic. 
This card will work to refactor the codebase extracting out the cloud providers into separate packages.

*Questions*
Any implications for create-app?
Any implications for guided-install?
Separate package for each? Or one package for all cloud providers together?
What changes do we need to make to our set up instructions on the microsite?

### AC's
- [ ]

**Comment by ccasher** [comment]
Todo:
- [x] Fix Cloud provider tests
- [x] Update emissions factors logic in App.ts
- [x] Update build processes with new extracted packages
- [x] Fix cli.test.ts and csv.test.ts tests in cli package
- [x] Add tests / update coverage threshold in core package

Refactor Decisions:
- Remove services directory in core package and move common files to common package
- Create new directories in core and remove domain
- Update FootprintEstimate in core (move functions and types)
- Replace cloud provider from buildComputeUsage class and add cloud constants
- Update Storage Service to instantiate with storage coefficient
- Create CloudConstantsUsage type and pass through constants and emission factors into estimator functions

**Comment by dtoakley** [comment]
Overall looking good to me. I think we can close this one off for now.
