### ISSUE TITLE
Add tests to core package to raise coverage thresholds

### ISSUE THREAD

**Issue by ccasher** [cloud-carbon-footprint/cloud-carbon-footprint#319]
After finishing the refactor to extract packages out of core, the test coverage in the core package is extremely low. Currently, the thresholds are also set low just so that we could merge in the extraction branch.

We need to add more tests/coverage to this package prior to the next app release. The goal should be to hit 80-100% coverage for branches, lines, functions and statements.

**Comment by dtoakley** [comment]
I've added additional test for all the classes that needed them, and ignored a few additional things like index.ts files and an abstract class: 

<img width="692" alt="dtoakley_danlewistoakley___repos_cloud-carbon-footprint_packages_core" src="https://user-images.githubusercontent.com/2144730/120972002-a157f600-c7b0-11eb-899c-6800d0a6d95c.png">

I've also bumped the thresholds to match this now, so we should be in a good spot. @ccasher @4upz-tw @aalva05-tw please review -- I tried to separate the commits per test class.
