### ISSUE TITLE
Missing dist directory in some NPM packages

### ISSUE THREAD

**Issue by vhiairrassary** [cloud-carbon-footprint/cloud-carbon-footprint#323]
Following latest [release](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/releases/tag/latest) (thank you!) I tried to update my packages but it seems some NPM packages do not contain the `dist` directory with compiled JS:

- ✅ for example, new version of `core` seems OK: https://cdn.jsdelivr.net/npm/@cloud-carbon-footprint/core@0.8.0/
- ❌ `app`, `aws`, `azure`, `gcp`, etc. do not contain the `dist` directory (while still being referenced as `"main": "dist/index.js",` in package.json): https://cdn.jsdelivr.net/npm/@cloud-carbon-footprint/aws@0.0.2/

Also, some files should certainly not be part of the published packages, such as `logs`, `coverage`, `estimates.cache.json`, etc. Let me know if I can help you, I am happy to participate if needed.

**Comment by ericksod** [comment]
Thanks @vhiairrassary for pointing it out! If you're willing to work on this, we would really appreciate it. We'll review what you come up with, also to prevent the same issues from happening in the future. If you do start work, please assign yourself and move this into `In Progress`. Thanks!

**Comment by vhiairrassary** [comment]
Thanks @ericksod for your answer. After digging a bit in the repository here are my understandings:
- Every time a PR is merged in `trunk` the [changeset](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/.github/workflows/changeset.yml) GitHub Action is triggered.
- This action automatically opens and manages a PR (from `trunck` to `changeset-release/trunk`), such as https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/285, which stacks the changes.
- Every time someone merge a changeset PR, an action is triggered and part of it is responsible to publish packages to NPM. Last merged changeset PR is (https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/285) and [we can see only few packages were published](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/285/checks?check_run_id=2769435872#step:9:431): api, cli, client, core. I don't know why `yarn lerna publish from-package --yes` didn't published some packages.
- Others packages seems to have been manually published by @ccasher giving the filenames in https://cdn.jsdelivr.net/npm/@cloud-carbon-footprint/aws@0.0.2/coverage/coverage-final.json.

As I said above, I don't know why `yarn lerna publish from-package --yes` didn't published some packages. The documentation is available [here](https://github.com/lerna/lerna/tree/main/commands/publish).

Hopefully the currently opened changeset PR https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/326 will automatically publish all packages but ⚠️ as some are not present in the changeset such as `aws`, `azure`, `cli` & `common` we may see them skipped again). I suspect having all the packages mentioned in the currently opened changeset PR should be enough for the next run.

Thoughts? On my side, happy to help more if needed.

**Comment by ccasher** [comment]
Hey @vhiairrassary,

Thanks for digging into this. I believe you might be correct on the fact that having them all included in the next changeset PR action will trigger the fix. I had to manually publish them initially on npm and we havent bumped since so that would hopefully explain the problem of no dist as I may not have ran a build before the publish.

We will plan to do another release on Monday and make sure to have each new package bumped to trigger the correct build/publish.

Thanks,
Cam

**Comment by vhiairrassary** [comment]
Thank you for your help!

**Comment by ccasher** [comment]
I believe this is fixed with the new release! If you want to confirm I can wait to close out this issue.

Thanks, Victor!
