### ISSUE TITLE
Automate updating coefficients

### ISSUE THREAD

**Issue by davidmytton** [cloud-carbon-footprint/cloud-carbon-footprint#331]
## Feature Suggestion
As discussed in https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/253 the process for updating the coefficients with new entries in the SPECpower results is currently quite manual, as described in https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/253#issuecomment-853231578 

This issue is to track automating that process as much as possible, requested by @dtoakley.

## Possible Implementation

I'm working on an implementation where the underlying data (SPECpower results and list of CPUs grouped by architecture) is in CSV rather than the current Google Sheets. The calculations are then performed using a Python Jupyter notebook which describes the methodology step-by-step. The goal is to make it a bit more transparent and put the data files into version control.

Hoping to share progress on this over the next couple of weeks.

**Comment by ericksod** [comment]
Awesome, thanks @davidmytton!
This is really exciting and would save us some manual effort of remembering to update them.
I'll put this card in the In Progress Column and assign it to you. Keep us updated with any questions or concerns.

**Comment by davidmytton** [comment]
The first version of this is now ready for review @ericksod @dtoakley. You can find the repo at https://github.com/davidmytton/cloud-carbon-coefficients in the form of a Python (3.9) Jupyter Notebook.

**Notes**

1. All the data used to perform the calculations is in the [data/](https://github.com/davidmytton/cloud-carbon-coefficients/tree/main/data) directory. This contains data from the various tabs from [the public Google Sheet](https://docs.google.com/spreadsheets/d/1O7Ug_eUZvbZA4dTaA-8DNhJhoZikKD2IdD8OeNQipe4/edit) extracted to CSV so they can be read into the notebook (and also kept under version control).
2. Updating the coefficients in the future will consist of updating the relevant data files e.g. new cloud instance types and associated CPU architectures, new SPECpower results, etc; then re-running [the notebook](https://github.com/davidmytton/cloud-carbon-coefficients/blob/main/coefficients.ipynb) and copying over the new constant values. 
3. The SPECpower results CSV requires minimal cleaning of the 'CPU Description' column when adding new rows. This consists of removing any info, for example `Intel Xeon E5-2470 (Intel Turbo Boost Technology up to 3.10 GHz)` should be cleaned to `Intel Xeon E5-2470`.
4. The instance lists have been split out into a line for each instance and architecture. Previously, some instances had multiple architectures listed, [such as for AWS](https://docs.google.com/spreadsheets/d/1O7Ug_eUZvbZA4dTaA-8DNhJhoZikKD2IdD8OeNQipe4/edit#gid=1756293863) `c5.large | Cascade Lake & Skylake`. In the CSV, this is now 2 lines, one for Cascade Lake and one for Skylake.
5. This notebook deals with `MEMORY_AVG`, `MEMORY_BY_COMPUTE_PROCESSOR`, `MIN_WATTS_AVG`, `MIN_WATTS_MEDIAN`,  `MIN_WATTS_BY_COMPUTE_PROCESSOR`, `MAX_WATTS_AVG`, `MAX_WATTS_MEDIAN`,  `MAX_WATTS_BY_COMPUTE_PROCESSOR` constants. I have not yet tackled the `MEMORY_COEFFICIENT` constant.
6. The calculated values don't always match the ones currently in the Google Sheet. This is mainly due to a mismatch in the groupings of the CPU architectures that we have a separate email thread discussing. Once we find the discrepancies I can re-run the numbers and see where any final mismatches are for validation.

**Questions**

1. How would you like this officially submitted to the project? You could take over the repo and keep it separate, or I could submit a PR as part of the main repo. The reasoning behind using a notebook is that each step can explained with in-line text in markdown format, followed by the code, then more text. I'm open to re-writing it in Typescript if you prefer, but since this is a methodology involving multiple steps where you want to see/verify the output at each step, using a notebook seemed like a good approach
2. Is it clear which values in the notebook match up to which constant? Or should I specifically name the constants and the value to copy/paste e.g. having the notebook ouput the names/values: `AWS_CLOUD_CONSTANTS. MEMORY_BY_COMPUTE_PROCESSOR.COMPUTE_PROCESSOR_TYPES.COFFEE_LAKE = 19.56`
3. Any thoughts on the best way to write tests for this?
4. Some CPU architectures are not used by the provider but they are still in the constants definition. For example, https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/2260f61c09c66b972d4744e76ed07babf725b1c1/packages/aws/src/domain/AwsFootprintEstimationConstants.ts#L27 has a value but Sandy Bridge is not used by any AWS instances. Where should the value for this come from?

**Comment by dtoakley** [comment]
Hey @davidmytton -- this is looking great! Apologies because this is probably assumed knowledge, but could you update the repo (or comment here) with instructions for running the notebook, including setting up the virtual environment if there is one? Before we update the coefficients in the main CCF repository I'd like to run the notebook myself and grok how it works a bit better :) 

Now for your questions:

1. I'm thinking it should at least exist within the cloud-carbon-footprint Github organization, but maybe as a separate repository for now given it's a different ecosystem with different dependencies. If we do re-write it in typescript (not required for the time being), then we could consider doing that inside the cloud-carbon-footprint monorepo. What do you think? Open to other approaches too! 
2 & 3. I think I want to run the notebook locally first and to have an opinion on these questions :) 
4. I'm thinking we should remove those from the constants file if they aren't used, because it could be confusing for users when they see the `MIN_WATTS_AVG` or `MAX_WATTS_AVG` doesn't actually equal the min/max average of the processors defined in the constants file. If a cloud provider then adds a now microarchitecture to their list of instances, we would just need to update the data file related to this and the new microarchitecture should who up in the updated coefficients. What do you think David? 

Agains, thanks so much!

**Comment by davidmytton** [comment]
https://github.com/davidmytton/cloud-carbon-coefficients/commit/5502ad08abe4d49253f5afb0a96156e367bf3106 adds instructions for running the notebook. There are lots of ways to run them but I recommend using Deepnote because it has the best UI and they provide free cloud environments. There is now a button on the readme which will auto launch an environment for the notebook, then you can open `coefficients.ipynb` file in Deepnote and press the "Run notebook" button at the top.

This button will do it too:

[<img
src="https://deepnote.com/buttons/launch-in-deepnote-white.svg">](https://deepnote.com/launch?url=https://github.com/davidmytton/cloud-carbon-coefficients)

Let me know if anything is unclear or you have feedback.

> I'm thinking it should at least exist within the cloud-carbon-footprint Github organization, but maybe as a separate repository for now given it's a different ecosystem with different dependencies. 

This sounds good to me. When you've managed to run it and are happy with how it works, I can transfer ownership.

> I'm thinking we should remove those from the constants file if they aren't used, because it could be confusing for users when they see the MIN_WATTS_AVG or MAX_WATTS_AVG doesn't actually equal the min/max average of the processors defined in the constants file. If a cloud provider then adds a now microarchitecture to their list of instances, we would just need to update the data file related to this and the new microarchitecture should who up in the updated coefficients. What do you think David?

That makes sense. A new SPECpower results-set came out yesterday - https://www.spec.org/power_ssj2008/results/res2021q3/ - so when the notebook is moved over to your org and that project is "closed", I'll re-run it for the new results and submit a PR that updates everything and removes the ones not in use. Then we can validate those changes make sense.

**Comment by dtoakley** [comment]
Thanks so much @davidmytton -- this is a lot clearer and I've been able to run the notebook and understand it a lot better :) A few comments/thoughts:

1. When I click the "Launch in Deepnote" button it initially shows an error "We are sorry, this format is not supported yet.", so I was a bit confused before realizing I had to open the file on the left then run it. Not sure if there is way to improve that, and no worries if there isn't! 
2. I think it's clear which variables match up to which constant. I think if we specified them exactly it would mean we have to update them in two places if they change, which isn't ideal. So all good on that front. 
3. Re: testing, my very initial research into this lead to testbook: https://testbook.readthedocs.io/en/latest/. I think if we utilized this tool it would mean refactoring the code a bit to encapsulate the code logic into some function that can then be imported into the test code. For example the logic to extract the min/max/memory averages for each CPU processor could be defined inside a function and the variables like `servers_amd_epyc_gen1` passed to it as an argument. The same could be true of the logic that loops through the cloud provider instances and build the constants.
4. I don't think any of the previous points should block us from migrating the repo and re-running the numbers withe the latest Spec results  though -- I'm confident enough with the logic as it is for us to proceed. Feel free to initiate the transfer whenever you get a moment, and we can create an issue with adding tests and refactoring the logic to support this!
5. And no rush on a PR to update the constants, but that would be awesome as well when you have time!

**Comment by davidmytton** [comment]
Great. I've updated the Deepnote button to link directly to the notebook: https://github.com/davidmytton/cloud-carbon-coefficients/commit/95c9f8b9646491e429f9489d27bc5afb4e33663b

I tried transferring ownership to the org but it says "You don’t have the permission to create public repositories on cloud-carbon-footprint" so I've transferred to you @dtoakley. I assume you can then move it to the org.

Once that's done I can create the issues for the tests with testbook and updating with the latest SPECpower data to submit a PR to the main project.

**Comment by dtoakley** [comment]
Awesome! I've transferred it to this organization now: https://github.com/cloud-carbon-footprint/cloud-carbon-coefficients

I think we can close this issue off now and handle the tests and SPECPower updates in other issues/PRs. Thank you so much again @davidmytton

**Comment by davidmytton** [comment]
SPECpower update issue: https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/383
