### ISSUE TITLE
Add AMD EPCY 3rd Generation to Compute Processors

### ISSUE THREAD

**Issue by dtoakley** [cloud-carbon-footprint/cloud-carbon-footprint#332]
Context: 
- After the recent update to SPECPower Database spreadsheet, we noticed a number rows for AMD EPYC 3rd generation processors: https://docs.google.com/spreadsheets/d/1O7Ug_eUZvbZA4dTaA-8DNhJhoZikKD2IdD8OeNQipe4/edit#gid=467435557
- It looks like Azure is the only Cloud Provider that offers this processors with one of their Machine Types, specifically  "HBv3" VMs https://azure.microsoft.com/en-au/pricing/details/virtual-machines/linux/
- We should update the spreadsheet with a Tab for this microarchitecture, as well as include this as an option in our processors lists.

Tech Tasks:
 -  Add a new tab in the  spreadsheet for "AMD EPCY 3rd Generation", copy the relevant rows over and calculate the min/max watts and GB/Chip like the other tabs. You may need to create a copy of the spreadsheet for this if you don't have write permission.  
 - Add this new processor type to packages/core/src/compute/ComputeProcessorTypes.ts
 - Add the new instance family and instance type "HB120rs v3" to packages/azure/src/lib/VirtualMachineTypes.ts
 - Unit test(s) added to cover this use case

**Comment by davidmytton** [comment]
I'll look at this one at the same time as https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/383

**Comment by ericksod** [comment]
Hi David - awesome work, we'll take a look at your PR!
