### ISSUE TITLE
Review yaml files and update for ease of use

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#336]
## Acceptance Criteria
- [ ] Update AWS documentation in microsite

## Tech Tasks
- [ ] Run Changesets, bump any packages that have been updated/changed
- [ ] Did you make changes to the client, api or cli package? If so, considering updating the create-app templates.

## Review Tasks
- [ ] eg. specific QA details, update methodology, or update microsite

**Comment by dtoakley** [comment]
I reviewed this, updated the yaml files and also added some additional context in the AWS instructions: https://www.cloudcarbonfootprint.org/docs/aws/

I also replied to the Google Group thread about this, with detailed instructions.
