### ISSUE TITLE
Potentially present Emissions Breakdown as a stacked bar chart

### ISSUE THREAD

**Issue by pwithnall** [cloud-carbon-footprint/cloud-carbon-footprint#354]
## Feature Suggestion

It would be helpful if the bar for (say) S3 in the ‘Emissions Breakdown’ could be split into several stacked sub-bars, one for storage emissions, one for bandwidth emissions to other data centres, one for bandwidth emissions to end users, etc. That would give users of CCF a bit more guidance about which where the main contributions to emissions for each service come from. Thanks.

This is based on my assumption that each bar in the ‘Emissions Breakdown’ incorporates several emissions factors (compute, memory, storage, bandwidth), as applicable, for each service. I might have misunderstood that, though.

Use case: knowing where to focus optimisation efforts for a particular service. For example, are the majority of my S3 emissions coming from the volume of data I’m storing, or from the bandwidth required to access it?

Here’s a (very quick!) mockup of the kind of stacked bar chart I had in mind. The total width of all the stacked bars for a particular row gives the overall emissions contribution from that service, as before. The width of each bar within the stack gives the contribution from that factor (compute, memory, storage, bandwidth) within that service. It would probably be too noisy to label all the bars with their percentages/emissions numbers, but perhaps those numbers could be in a tooltip on hovering over a bar, or clicking on it.

Colour could also be used (as in the mockup) to group bars representing the same factor in different services (for example, all the network bars could be red), although you should probably be careful to provide this information in another form as well, as communicating information via colour alone is [not accessible for those who have impared colour vision](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html) (as I’m sure you already know :slightly_smiling_face:).

![image](https://user-images.githubusercontent.com/53172/123081678-1f093c00-d416-11eb-94c8-d26bc99bdacb.png)

(Split out from #307.)

**Comment by ericksod** [comment]
Hi @pwithnall! 
This is an awesome suggestion, thanks for sharing. We've been thinking about different ways to display data that will be useful to users and it's great to get your feedback on it.
And yes, your assumption is correct that by default, this chart includes all types of usage (compute, storage, memory, networking).
I'm interested to know (coming from a user research angle), how you think you're likely to focus your optimization efforts, eg on one particular service at a time, one type of usage at a time, or account/project one at a time.
Additionally, is this sort of breakdown for you most valuable to see for the services or is it something that would also be valuable for instance in the accounts bar chart breakdown?

**Comment by pwithnall** [comment]
> I'm interested to know (coming from a user research angle), how you think you're likely to focus your optimization efforts, eg on one particular service at a time, one type of usage at a time, or account/project one at a time.

I think I’d probably:
 1. Triage the usage and work out the easy improvements to make (‘low hanging fruit’): services which are not actually necessary (someone forgot to turn them off), or usage which is unexpectedly high due to a bug in our setup (for example, data piling up in S3 because it’s not being deleted on schedule)
 2. Then work out what’s causing the remaining large sources of emissions, and work out a plan for reducing each of them, focusing on the largest ones first. The way to reduce each source would probably differ; it could be by moving from one data centre to another which is renewably powered; or by optimising bandwidth consumption or reducing the duration of file storage. Generally, being able to split the data up in multiple ways would help with this. Even if the data isn’t visualisable in every possible way in CCF, being able to export it in CSV format split up so that every factor is separated, would allow more detailed analysis in an external program where that’s useful.
 3. Once optimisation is complete, monitor usage over time to be able to spot sudden (or long-term) increases in emissions and tackle them while the changes which caused them are relatively fresh.

> Additionally, is this sort of breakdown for you most valuable to see for the services or is it something that would also be valuable for instance in the accounts bar chart breakdown?

I think this is most useful for the services. For the accounts, perhaps breaking down into stacked bar charts where each sub-bar is a service would be useful. For my use case, the accounts bar chart is not so relevant because we only have a single AWS account to monitor, so there’s only one bar.

**Comment by 4upz** [comment]
Hi @pwithnall, sorry for going quiet on this. Just wanted to follow up and at the moment, we don't plan on making significant changes to the UI's bar chart -- at least from a way of displaying additional optimizations or breakdowns. For your use case, feel free to export the data from the API (or as a CSV from the dashboard) and try making your visualization. But thank you for the suggestion!
