### ISSUE TITLE
Mock Data is duplicating GCP data into AWS

### ISSUE THREAD

**Issue by 4upz-tw** [cloud-carbon-footprint/cloud-carbon-footprint#365]
Currently, when running the app with `yarn start-with-mock-data` then looking at all of the accounts in the filter dropdown, you can see that all of the GCP account names are being duplicated as accounts in the AWS section. This causes some adverse functionality when trying to select/deselect these accounts from the account filter menu due to the keys (account names) being used twice in the list of options.

**Expected behavior**
- [ ] When I run the app with mock data, I should see only AWS accounts in the AWS section of the accounts dropdown at the top of the page
- [ ] When I run the app with mock data, I should see GCP accounts *only* in the GCP section of the accounts dropdown at the top of the page

**Current Behavior**
![Screen Shot 2021-07-02 at 12 48 46 PM](https://user-images.githubusercontent.com/81026458/124306089-efec7c00-db33-11eb-9cf5-c0f16d5fff33.png)
![Screen Shot 2021-07-02 at 12 48 57 PM](https://user-images.githubusercontent.com/81026458/124306099-f24ed600-db33-11eb-930a-1322d3dbe4b4.png)

**Comment by cfellin1** [comment]
Hello! I am a new contributor, and I can contribute a fix for this.

**Comment by cfellin1** [comment]
https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/381
