### ISSUE TITLE
Inclusion of additional unknown services using usage type cost/carbon averages AWS

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#390]
**Context**
We would like to include carbon estimations for the services we currently classify an "Unknown" to improve the applications accuracy. We suspect we are currently underestimating by some amount. 

Our approach would be to calculate the relationship between cost and carbon for each usage type
**A/Cs**
- [x] There is a new variable called 'UNKNOWN_USAGE_TYPE_UNITS' in CostAndUsageTypes.ts that includes a map of pricing units to their usage classification
- [x] AWSFootprintEstimateConstants.ts has been updated to include Co2ePerCost
- [x] The accumulator function is added to the appropriate places in CostAndUsageReport.ts to add to the Co2PerCost constant to create the usage coefficients
- [x] There are new test cases added in CostAndUsageReport.test.ts that includes tests covering Unknown usages types that have been reclassified to Compute, Networking, Storage and ones that are still Unknown

**Comment by dtoakley** [comment]
I pushed some minor refactoring, but overall looking good. We still need to align with stakeholders on the Unknown -> usage type classifications, but this a good first implementation - but that can be a separate issue. Closing this one off.
