### ISSUE TITLE
Unable to run app

### ISSUE THREAD

**Issue by chrisgreen500** [cloud-carbon-footprint/cloud-carbon-footprint#395]
Hello,

I am keen to get the app up and running, but have been unable to do so. I have tried both methods of running it but with no luck. I have the prereqs installed (Git, Nodejs, Yarn)

**Cloned repository**
The api starts ok, but I get the following error when trying to start the client:

 ./src/pages/EmissionsMetricsPage/EmissionsMetricsPage.tsx
[0] Module not found: Can't resolve 'ConfigLoader' in 'E:\Source\Green\cloudcarbonfootprint2\packages\client\src\pages\EmissionsMetricsPage'

I have had a good look into this and it is the following TypeScript module import (line 11) that appears to be the issue:
import config from 'ConfigLoader'

The ConfigLoader.ts file exists in the ..\packages\client\src folder, and looking at TypeScript documentation and as a non-relative import directive it should work. 

Line 10 of the file is:
import { FilterResultResponse } from 'Types'

and the Types.ts file, which is in the same folder as the ConfigLoader.ts file is not erroring. I have checked permissions on these files, and they are identical. I cannot figure out what is going wrong here.

**Standalone App**
The standalone app throws the following error:

Failed to compile
src\App.tsx
  Line 1:3:    Delete `␍`  prettier/prettier
  Line 2:29:   Delete `␍`  prettier/prettier
  Line 3:4:    Delete `␍`  prettier/prettier

Any suggestions you can make would be gratefully received.

**Comment by jjancek1217** [comment]
I can confirm I ran into the same issue trying to run the project with mocked data

**Comment by ghost** [comment]
You need to set the `baseUrl` property for `packages/client/tsconfig.json`.  It's been updated on trunk, but not deployed to latest npx template yet.

https://github.com/nagytech/cloud-carbon-footprint/blob/5904d3177d5a3eeb1cf20e091bac0341f7c9fcbb/packages/client/tsconfig.json#L22

**Comment by ericksod** [comment]
Thanks for bringing light to this @chrisgreen500! We'll take a look at making this fix @nagytech, and look at how we can prevent this in the future.

**Comment by ccasher** [comment]
Hello! Thanks for creating an issue for this bug! We believe this should be fixed now in our most recent [release](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/releases/tag/latest).
