### ISSUE TITLE
Filtering on Recommendations table

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#398]
**Context**
On our recommendations page we would like to present data in a way that inspires action. One essential part of this is the ability to organize and play with the data and recommendations, and that can be achieved through filtering.
We should build it closest to the first mock up provided in the comments section.

**Out of Scope**
- "Apply" and "Clean" from mock up

**A/C's**
- [ ] When I view the table on the recommendations page, I see a filter bar above the Recommendations table
- [ ] When I scroll down the page, the filter bar remains at the top
- [ ] When I view the filter bar, I see options to filter cloud provider, account, region and recommendation type in that order
- [ ] When I click on the cloud provider filter button, I see a list of all three cloud providers
- [ ] When I click on the cloud provider filter button, I can select multiple cloud providers
- [ ] When I click on the account filter, I can see all accounts separated by provider and select multiple accounts
- [ ] When I click on the region filter, I can see all the regions used in my data and can select multiple regions
- [ ] When I click on the recommendation type filter, I can select multiple recommendation types
- [ ] When I have data sorted and I apply a filter, the data remains sorted and the filter is applied
- [ ] When I have a filter applied, I can select additional filters and they are applied as well
- [ ] When I view the table, I do not have the option to filter by clicking on the headers
- [ ] When I view the table, I can still sort each column
- [ ] When I view each filter, there is an option to select all
- [ ] When I deselect all options for a given filter, I see an error message prompting me to expand my search parameters "Try adding cloud providers, accounts, regions, or recommendation types"

**Comment by aalva05-tw** [comment]
I did some research on how to implement this and there are different options we can choose from:

Option 1: Use out of the box DataGrid filtering 
    Pros: - easy and fast to incorporate in our table
              - nice CSV export feature 
              - can be customized to our needs
              - offers quick search filtering
    Cons: - does not offer multiple filters

Option 2: Use out of the box XGrid filtering 
    Pros: - easy and fast to incorporate in our table
              - cool export feature 
              - can be customized to our needs
              - offers multiple filters, you can add as many as you'd like
              - offers quick search filtering
    Cons: - we would have to install a new dependency but we could remove DataGrid since we would switch to XGrid instead

Option 3: Use the FilterBar of the Home page dashboard
    Pros: - fully customizable to our needs 
              - no need to install new dependencies
    Cons: - we would have to do a big and somewhat complex refactor to make the component reusable by a different data type because right now it accepts data of type `EstimationResult[]`, and we would need to pass data of type `ReccomendationsResult[]` 

I also worked on some designs and I added them below:
![Filters - Concept 1](https://user-images.githubusercontent.com/82478801/130265244-c24cb4a7-367d-47f9-b441-e746f8fb022f.png)
![Filters - Concept 2](https://user-images.githubusercontent.com/82478801/130265260-f527a5dc-96cc-47a5-9ff2-ea93c9c9e08a.png)
![Filters - Concept 3](https://user-images.githubusercontent.com/82478801/130265266-8462bf8a-d49f-4a7d-8b94-cc106be18575.png)
![Filters - Concept 4](https://user-images.githubusercontent.com/82478801/130464768-f1909883-93c7-4aae-913e-ba4875cfdc1a.png)
