### ISSUE TITLE
Add support for Azure Regions

### ISSUE THREAD

**Issue by ghost** [cloud-carbon-footprint/cloud-carbon-footprint#401]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - Ubuntu 18.04, Node 14
- **Browser:**
  - N/A, using CLI

- Using Azure by setting the connection details in the .env file.

### Expected Behavior

Expected to receive a report based on the Azure usage.

### Actual Behavior

Error message.

```
/home/{redacted}/cloud-carbon-footprint/packages/common/src/Errors.ts:13
    super(message)
    ^
EstimationRequestValidationError: Not a valid region for this account
    at new EstimationRequestValidationError (/home/{redacted}/cloud-carbon-footprint/packages/common/src/Errors.ts:13:5)
    at validate (/home/{redacted}/cloud-carbon-footprint/packages/app/src/CreateValidRequest.ts:66:11)
    at Object.CreateValidFootprintRequest (/home/{redacted}/cloud-carbon-footprint/packages/app/src/CreateValidRequest.ts:134:3)
    at Object.<anonymous> (/home/{redacted}/cloud-carbon-footprint/packages/cli/src/cli.ts:54:29)
    at step (/home/{redacted}/cloud-carbon-footprint/packages/cli/src/cli.ts:52:23)
    at Object.next (/home/{redacted}/cloud-carbon-footprint/packages/cli/src/cli.ts:33:53)
    at /home/{redacted}/cloud-carbon-footprint/packages/cli/src/cli.ts:27:71
    at new Promise (<anonymous>)
    at __awaiter (/home/{redacted}/cloud-carbon-footprint/packages/cli/src/cli.ts:23:12)
    at Object.cli [as default] (/home/{redacted}/cloud-carbon-footprint/packages/cli/src/cli.ts:89:12)
```

### To Reproduce

- Configure for Azure
- run `yarn start-cli --startDate 2021-08-03 --region "AustraliaEast" --groupBy service --format csv --endDate 2021-08-04`

### Additional Information

The following code in CreateValidRequest.ts shows that the system only references AWS regions.

```
  if (region && !contains(region, values(configLoader().AWS.CURRENT_REGIONS))) {
    errors.push('Not a valid region for this account')
  }
```

**Comment by ghost** [comment]
Happy to contribute, but it may take me a while to grok the code in order to do it generically.  If already has pointers on how to how to access the config object through a common interface, please let me know.

**Comment by ericksod** [comment]
Hey @nagytech! Good find - that's a little bit of tech debt we have from before we added in support for Azure and GCP. It's not one of our top priorities at the moment, so if you're willing to work on it at your leisure, that'd be awesome! For this, it'd be best however to use region constants from the various packages rather than the config object. Let us know if you plan on picking it up or have other questions!

**Comment by LvffY** [comment]
Hi @nagytech @ericksod 

I felt into the same issue. Is there any update on this ? 

*Seems like the `west-europe` or `francecentral` region fall into this issue, because it seems related to Azure Region*

**Comment by ghost** [comment]
> 

Pretty sure that I just hardcoded some values to get around this, but haven't touched the project in a long time.  Sorry I can't help further.

**Comment by LvffY** [comment]
No problem @nagytech 

This issue might be at the same time of #592

**Comment by ericksod** [comment]
Hi @LvffY !
Yes, it is the same issue as #592 , which has been added to the project and planning board with more specific requirements. I'll close this one to avoid confusion.
