### ISSUE TITLE
Make local installs consistent with production (for create-app testing)

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#403]
**Context:**
There has been difficulty making sure the create-app is working properly after getting updates in a streamlined, processed way. We would like to create a process that automates a way to build and publish the updates to create app, and then triggers a local install to test the changes. Ideally this will be done at least as often as CCF releases occur.

**Tech-Tasks**
- [x] Write a script that triggers a build/publish for create app
- [x] Create a private package to be published called `@cloud-carbon-footprint/create-app-test` that gets a patch version bump each time the script is ran
- [x] Have the script install the newly published package via `npx @cloud-carbon-footprint/create-app-test`
- [x] Have the script start the application using `yarn start-with-mock-data`

**A/C's**
- [x] Once created, the script should successfully build and publish a new package with a patched version of `@cloud-carbon-footprint/create-app-test` and then subsequently install the package and start the app with mock data
- [x] Documentation should be updated on the process of testing create-app and added to team onboarding and other relevant documents

**Notes**
- This is just one suggested method. During the kickoff for this task, there should be deliberation over the best way to go.
- The package name: create-app-test is just a suggestion and could be changed to something that might make more sense.
- There may need to be research whether the npx install command is able to install private packages.
- The script may need to time-out/wait for the package to be published before installing it.
- The testing process for create app should also manually include adding environment variables and testing/running the api and cli packages. This can be added to the documentation.

**Comment by ccasher** [comment]
https://docs.google.com/document/d/1Ei6Cb2DjwEJUNtpULJSxbOuIdAfCARERgE3BSsKWrsc/edit

**Comment by dtoakley** [comment]
This is great Nice work. My only small feedback is we probably shouldn't link to an internal document in `.github/ISSUE_TEMPLATE/story-card.md`, but it's really not a big deal. Closing this off.
