### ISSUE TITLE
Add missing unsupported regions for GCP

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#408]
**Context:**
Cloud Carbon Footprint requires each region used to be registered so that proper carbon intensity can be calculated for data stored in those regions. We have found a few missing GCP regions that we need to add support for.

Google cloud regions and carbon intensity: https://cloud.google.com/sustainability/region-carbon
**Tech Tasks:**
- [x] Update all of the GCP emissions factors to reflect the most recent Grid carbon intensity values

**A/C's:**
- [x] When I have usage in europe-central2 in Warsaw, the carbon footprint of that region should be included in the total
- [x] When I have usage in asia-south2 in Delhi, India APAC, the carbon footprint of that region should be included in the total
- [x] When I have usage in australia-southeast2 in Melbourne, Australia, APAC the carbon footprint of that region should be included in the total
- [ ] When I have usage in us-central2, APAC the carbon footprint of that region should be included in the total
- [x] When I view the carbon intensity map on the CCF homepage, I see these three regions represented with the proper color according to the scale and the region's carbon intensity 
- [ ] When I view carbon intensity on region bar chart, it should have the appropriate color 

**Tech Notes**
- [ ] us-central-2 should have the carbon intensity of us-central-1

**Comment by steren** [comment]
The carbon data of GCP regions is also available as CSV of you need to: https://github.com/GoogleCloudPlatform/region-carbon-info/blob/main/data/yearly/2020.csv
