### ISSUE TITLE
New Azure consumption types and Region Bug

### ISSUE THREAD

**Issue by ajberti** [cloud-carbon-footprint/cloud-carbon-footprint#412]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - Windows 10 (1803)
- **Browser:**
  - Firefox 

### Expected Behavior

Successfully cloned the repo and ran the app via 'yarn start'. Ran into a couple of issue. I have fixed them locally but am not great at git or how to submit PR's. So here are my fixes, use as you see fit. Great work so far all!

### Actual Behavior

New consumption types found:

[1] 2021-08-11T09:07:00.558Z [ConsumptionManagement] warn: Unexpected usage type for storage service: B DTUs
[1] 2021-08-11T09:07:00.938Z [ConsumptionManagement] warn: Unexpected usage type for storage service: Users
[1] 2021-08-11T09:07:01.576Z [ConsumptionManagement] warn: Unexpected usage type for storage service: Microsoft-hosted CI

Also when running the app a region reference error occurs as in:
packages/client/src/utils/helpers/transformData.ts
as value.region is not defined.

### To Reproduce

Here are my fixes...

transformData.ts - line 94:
  if (value.region) {
    if (
      dataType === ChartDataTypes.REGION &&
      value.region.toLowerCase() === 'unknown'
    )
      value.region = `${UnknownTypes.UNKNOWN_REGION}`
  } else {
    value.region = `${UnknownTypes.UNKNOWN_REGION}`
  }
}

and of course the consumption types to add:

export const STORAGE_USAGE_TYPES: string[] = [
  'Data Stored',
  'Metadata',
  'Registry Unit',
  'ZRS',
  'LRS',
  'GRS',
  'GZRS',
  'Data Retention',
  'Users',
  'B DTUs',
  'Microsoft-hosted CI',
]

### Additional Information

© 2021 Thoughtworks, Inc.

**Comment by ghost** [comment]
Related #401

**Comment by ericksod** [comment]
Hi @ajberti! Thanks for bringing this up.
It seems like you've worked on a solution and may have a fix - would you mind submitting this as a PR? It would be easier for us to test out your solution properly that way.
Thanks!

**Comment by 4upz** [comment]
Closing since these types were added and this bug should have been fixed. Feel free to let us know if you're still encountering it in our latest version of trunk! @ajberti
