### ISSUE TITLE
Switch between metric tons and kg for recommendations

### ISSUE THREAD

**Issue by aalva05-tw** [cloud-carbon-footprint/cloud-carbon-footprint#418]
**Context:**
Each recommendation generally pertains to a small amount of carbon reduction potential. Since it is small, it may be best to give the ability to show this in kg rather than metric tons. We would like a feature that allows the user to switch between the two.

**A/C's:**
- [x] When I view the recommendations dashboard, there is a toggle to change the carbon metric
- [x] When I view the recommendations dashboard, by default I see the carbon in kilograms and it is labeled as such
- [x] When I click the toggle when the units are currently kg, the carbon is displayed in metric tons and it is labeled as such
- [x] When I click the toggle when the units are currently metric tons, the carbon is displayed in kg and is labeled as such

<img width="1184" alt="unitToggle" src="https://user-images.githubusercontent.com/81026458/129630523-d4ee7174-deea-4b17-8c13-2c7a35621411.png">

**Comment by 4upz-tw** [comment]
![unitToggle](https://user-images.githubusercontent.com/81026458/129630451-38759553-eb5c-4268-a627-3714e816b404.png)
