### ISSUE TITLE
Online demo with mock data

### ISSUE THREAD

**Issue by steren** [cloud-carbon-footprint/cloud-carbon-footprint#423]
To play with the tool, one has to configure and start an app using npm. This can be a high barrier to entry for users who are not developers or devs who do not have a node.js local environment setup.

I would recommend running a demo instance of the project with mock data (maybe the same as `yarn start-with-mock-data`?) to better show what this project is about and link to it from the project's homepage.

**Comment by ericksod** [comment]
Hey @steren! Thanks for the suggestion, this is a really good idea.
We're going to look into logistics of how we might make this happen. Going to close this ticket and track the work with https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/428 and likely an implementation ticket afterwards.
