### ISSUE TITLE
Refactor filter components for reusability

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#425]
#### Overview
We would like to reuse our filter components on the recommendations page. To do so, we must refactor them a bit so that they can be used in a more generic sense.
## Acceptance Criteria
- [x] When I am trying to add a new filter to a page, I see there is a generic filter component that can be used with both the estimates and recommendations API responses

## Tech Tasks
- [x] Refactor Filter Bar component into a common component 
- [x] Separate filter utilities and emissions utilities 
- [x] Move any specific filters into the emissions page and extract any common filters 
- [x] Run Changesets, bump any packages that have been updated/changed
- [x] Did you make changes to the client, api or cli package? If so, considering updating the create-app templates.
- [x] If any create-app templates have been updated, make sure to run the [test-create-app script](https://docs.google.com/document/d/1Ei6Cb2DjwEJUNtpULJSxbOuIdAfCARERgE3BSsKWrsc/edit) to ensure it still works properly.

## Review Tasks
- [x] eg. specific QA details, update methodology, or update microsite

**Comment by dtoakley** [comment]
I pushed a small refactor to `packages/client/src/common/FilterBar/FilterBar.tsx` to reduce the number of props it requires, but other than that it's looking good! Closing this off.
