### ISSUE TITLE
[SPIKE] Host interactive version of app with mock data

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#428]
**Context**
As per suggestion https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/423 we want to explore hosting an interactive version of the app for folks to explore without having to go through the setup to run with mock data locally.

**A/C's**
- [x] Explore possibilities of hosting a static web page - Google?
- [x] Assess amount of work
- [x] Document recommended approach

**Tech**
- [x] Have client read from json file rather than making API requests
- [x] Or host mock data separately in bucket and make request to there - env variable to configure
- [x] 3 separate json files

**Comment by ccasher** [comment]
Created a new task to implement this ticket
