### ISSUE TITLE
Inclusion of additional unknown services using usage type cost/carbon averages Azure

### ISSUE THREAD

**Issue by ccasher** [cloud-carbon-footprint/cloud-carbon-footprint#432]
**Context**
We would like to include carbon estimations for the services we currently classify an "Unknown" to improve the applications accuracy. We suspect we are currently underestimating by some amount. 

Our approach would be to calculate the relationship between cost and carbon for each usage type
**A/Cs**
- [x] There is a new variable called 'UNKNOWN_USAGE_TO_ASSUMED_USAGE_MAPPING' in ConsumptionTypes.ts that includes a map of pricing units to their usage classification
- [x] AzureFootprintEstimateConstants.ts has been updated to include Co2ePerCost that includes memory (unlike AWS)
- [x] The accumulator function is added to the appropriate places in ConsumptionManagement.ts to add to the Co2PerCost constant to create the usage coefficients
- [x] There are new test cases added in ConsumptionManagement.test.ts that includes tests covering Unknown usages types that have been reclassified to Compute, Networking, Storage, Memory and ones that are still Unknown

**Comment by ccasher** [comment]
https://docs.google.com/spreadsheets/d/1G3SygBoiAW2XAs_JpGTfqdWIvy3vFKR-C_6rhphbArw/edit#gid=879035742

**Comment by dtoakley** [comment]
Reviewed, and pushed some updates to separate out handling of unsupported from unknown usage. Closing this off now!
