### ISSUE TITLE
Document approach for unknown usage types in Methodology

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#437]
**Context**
As we add in support for unknown usage types, we need to clearly explain how this calculation works for each cloud provider.

**A/C's**
- [ ] Introduce the concept of and how we deal with unknowns in the `holistic approach` 
- [ ] Explain further below `memory`
- [ ] Tech debt - Update this sentence to better reflect memory `We then further validate whether a line item is Compute, Storage, or Networking by looking at the more detailed usage type. E.g. if it contains content like “RAM”, it would be ignored.`

**Comment by ccasher** [comment]
https://docs.google.com/document/d/1C_ZKTNWzyQzyj7xF3n11H6DFGKhuGu7SdOXz_is-tsY/edit
