### ISSUE TITLE
Some local tests passing but failing on CI

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#446]
**Context**

**A/C's**
- [x] Tests should not fail on CI if passing locally

**Comment by dtoakley** [comment]
The best solution I found to this was to configure the AWS environment variables with test data prior to test runs, so they are consistent with local and CI test runs. This resolves the inconsistency. Commit: https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/commit/ee7357f8a1479f90796418ce30121c48814e4c51
