### ISSUE TITLE
Update usage classifications for Unknown Impl GCP and AWS

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#447]
**Context**
We've received additional feedback about how we classify unknown types to be calculated using compute/storage/memory/networking. We would like to take this into account.

**A/C's**
- [x] Line items for AWS should be classified as per feedback received
- [x] Line items for GCP should be classified with desired improvements and changes

**Comment by ccasher** [comment]
Looks good to me! 

One note:
https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/46a81181828dfcff31d2946179d852befb53b207/packages/gcp/src/lib/BillingExportTable.ts#L473
in this conditional, it will classify it as storage or memory before looking through the usage type mapping. do we want to have it check that first?
