### ISSUE TITLE
Bug: CCF is displaying different data on every restart connected to real data with AWS/Athena

### ISSUE THREAD

**Issue by jgrumboe** [cloud-carbon-footprint/cloud-carbon-footprint#457]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - macOS 11.5.2
- **Browser:**
  - Chrome

### Expected Behavior

After clearing estimates.cache.json and restarting the app locally with `yarn start`, I'd expect the dashboard to display the same numbers as a few minutes before.

### Actual Behavior

I see that the app fetches data from Athena to build up the estimates.cache.json.
Then I filter just for "Amazon ECS" service only and look at the emission breakdown by account.
Every time I see different account numbers and emissions I stop the app, delete the cache and restart the app.
Weird, the numbers just never match a manual Athena query CSV, filtered and pivoted in Excel.

### To Reproduce

I start the app multiple times after another, every time deleting the estimates.cache.json to trigger an Athena query.
Each time the numbers look different. Also, the accounts in the emission breakdown using a specific service differ from run to run.
Looks like only some part of the Athena queryresult is processed.

### Screenshots

Run 1:
![image](https://user-images.githubusercontent.com/5127047/132514359-803209c8-7c86-4095-9e1c-c042f39e1c43.png)

clean cache and restarted app

Run 2:
![image](https://user-images.githubusercontent.com/5127047/132514447-856ba643-93cc-4e39-8836-59ccb78082c8.png)

See how different account numbers are displayed in breakdown in run 2?!

### Additional Information

I also try to correlate the costs out of the estimates.cache.json with a manual downloaded Athena queryresult, but I fail.
Hard to describe, but as already said, I think that only some part of the Athena queryresult is processed and something is missed/discarded.

**Comment by jgrumboe** [comment]
I also have the Athena CSV downloaded from S3 and the estimated.cache.json available, but before uploading it here I will need to mask our account numbers a bit.

**Comment by jgrumboe** [comment]
[athena-csv-and-estimates-cache-json.zip](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/files/7129824/athena-csv-and-estimates-cache-json.zip)

I hope this data helps to debug my problem.

**Comment by dtoakley** [comment]
Thanks so much for this @jgrumboe  -- it's a really good catch and we appreciate you bringing it to our attention. I was able to replicate locally, and I just pushed a [fix](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/commit/5c753d1ac326f79aa6286fe1c556f132e09341fb) that I believe should resolve the issue.

Would you be able to pull the latest from the `trunk` branch, and re-test this on your end? If it's all looking good, I think we can close off this issue.

**Comment by jgrumboe** [comment]
Thanks, @dtoakley! 🙇‍♂️ 
The fix works, tested/restarted it multiple times and also did `GROUP_QUERY_RESULTS_BY=month` tests.
