### ISSUE TITLE
Filter bar not full width for wider screens

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#471]
**Description of issue**
When I view the CCF application on a wider screen, the filter bar does not span the whole width. 

**Out of scope**
- mobile

**Steps to reproduce**
1. Open the CCF home page on a 2560 by 1860 screen or similar
2. Notice the filter bar does not span the whole width

**Expected behavior**
1. Open the CCF home page on any desktop screen size
2. Filter bar spans the full width and filter options are in the center
3. Resizing the window, the filter bar continues to span the full width and filter options are in the center
<img width="1295" alt="Screen Shot 2021-09-16 at 4 21 47 PM" src="https://user-images.githubusercontent.com/8618241/133680621-3463e8df-f3da-4b59-b7f2-1d9e0345cbdf.png">

**Comment by aalva05-tw** [comment]
Nice work! I merged this through the cli instead of the console so I'm gonna close this pull request.
