### ISSUE TITLE
EstimationResults crash and exit if there are no estimates for a given day

### ISSUE THREAD

**Issue by MichaelHindley** [cloud-carbon-footprint/cloud-carbon-footprint#475]
Given an AWS account region that has nothing running for a particular date within a startDate and endDate span,
when trying to get estimates using https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/aws/src/application/AWSAccount.ts#L66,
the process crashes with `TypeError: Cannot read properties of undefined (reading 'kilowattHours')`,
on line https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/core/src/CloudProviderAccount.ts#L70

Potential solution is to add validation for the existence of `estimate` in the `getRegionData` function when looping over dates.

**Comment by MichaelHindley** [comment]
Given the liberal tsconfig.json settings from a distributed package perspective, 
and that the solutions deal with calculations on data supplied from external state storage like cloud accounts,
and that the nature of these state storages is dynamic with potential gaps in expected structures,
and given the optionally configurable cloud account providers and strategies for how their data is gathered based on local environment and optional constants,
then setting stricter compiler checks should decrease the amount of runtime errors.

**Comment by ericksod** [comment]
@MichaelHindley Thanks for adding these tickets - you may have seen we've moved the other two onto our board to be worked on. We'll leave this one here for now and see if perhaps updates we make on the other cards impact this.

**Comment by ericksod** [comment]
Hi @MichaelHindley!
Sorry for the delay on these, we are just getting to picking some of them up.
We realized that there might be two separate issues here, so I'll separate the first into a separate ticket https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/560

**Comment by ccasher** [comment]
HI @MichaelHindley, for now we have just decided to implement a [quick fix](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/commit/12e3e9c2295a035ea490f29ce2737703ccf39d7e) for this bug. Implementing strictNullChecks will require a lot of bandwidth from our team to make the required changes in each package, but we have created a ticket [#568](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/568) to work on it or invite contributors to as well.
