### ISSUE TITLE
Filtering, sorting and search should reset the pagination on the Recs table

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#497]
**Context**
As a user looking for specific optimizations to make
I want the table to refresh when I sort, search or filter
So that I can see my selected data holistically from start to end, without the confusion of being placed in the middle of my data

**A/C's**
- [x] When I am on a given page in the table and I sort a column, the table resets to the first page
- [x] When I am on a given page in the table and I search for a value, the table shows results starting on the first page
- [x] When I am on a given page in the table and I select filters from the top of the page, the table results show results starting on the first page
- [x] When I have a selected a filter and I apply a new filter, the table show the new results starting on the first page

**Comment by ghost** [comment]
Tested successfully on the production site:

- Sorting a column reset the pagination to the first page.
- Searching for a value in the grid reset the pagination to the first page.
- Changing the filters at the top of the page reset the pagination to the first page.
