### ISSUE TITLE
Lookup table option for Azure

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#498]
**Context**
We want to create an option for users to create a lookup table for Azure data, much in the same way it is set up for AWS and GCP.

This will allow users to create an output of data that provides the co2e per unit for every unique service and usage type for their Azure data.

**A/C's**
- [x] Given I have a CSV file in the cli package with all unique Azure region, service name, usage type and usage unit variations, I can run the command `yarn create-lookup-table <options>` to generate the lookup table for Azure
- [x] Given I am running the `create-lookup-table` command for my Azure usage, and I specify the option `--azureInput <filename>`, a lookup table will be generated based on the data in that file
- [x] Given I am running the `create-lookup-table` command for my Azure usage, and I do not specify the option `--azureInput <filename>`, I receive an error
- [x] Given I am running the `create-lookup-table` command for my Azure usage, and I specify an incorrect option (eg. `--acpInput <filename>` ) I receive an error
- [x] Given I am running the `create-lookup-table` command for my Azure usage, I can optionally specify the option `--azureOutput <filename>`  and the lookup table will be generated and populate in that file
- [x] Given I am on the microsite page `Creating a Lookup Table` I see the page updated to indicate Azure is also supported, the page includes the azure lookup table options, and a sample input api call for azure (since there is no query for the console)

**Tech Tasks**
- [x] in `packages/cli/src/CreateLookupTable/createLookupTable.ts` , there is a conditional handling and azureInputFile
- [x] in the cli, the correct options should be added for `--azureInput` and `--azureOutput`
- [x] there is a function in `App.ts` called getAzureEstimatesFromInputData that returns results from a function named `getConsumptionManagementDataFromInputData` taking the inputData as a param which will live in `AzureAccount.ts`
- [x] there is a function called `getEstimatesFromInputData` located in `consumptionManagement.ts` that looks similar to the other cloud providers.

**Comment by zhangtbj** [comment]
We also have this requirement:
https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/498

Could you please plan this feature later?

Thanks!

**Comment by 4upz-tw** [comment]
Tweaks from Review: 

- [x] add in a null check to make sure no values return null in the input data (omit rows that have any empty column)
- [x] remove vcpus and machineType from the lookup output
- [x] change console.logs to [console.info](http://console.info/)'s if you want the different coloring 
- [x] update microsite docs with new azure script name
