### ISSUE TITLE
Docs: Explain a bit better how to get AWS processor min wattage and maximum wattage

### ISSUE THREAD

**Issue by aCampello** [cloud-carbon-footprint/cloud-carbon-footprint#501]
Thank you for your great API! Very useful and very good docs. I have one suggestion for improvement.

## Feature Suggestion

I failed to understand why the docs define: 

Average Minimum Watts (0% Cpu Utilization): 0.74
Average Maximum Watts (100% Cpu Utilization): 3.5

I know it has to do with the SPECS power, but would be good if the docs included more explanation. I am not sure if it's actually a feature, but I myself would benefit from that. So maybe just responding to this ticket would be enough.

**Describe the solution you'd like**

At least mention which Processor is the one that has the minimum watts and which processor has the maximum watts. Also, I think you mean "kilowatts" ?

**Describe alternatives you've considered**
I tried to go to SPECS but could not match the provided numbers anywhre

**Comment by davidmytton** [comment]
The calculations are explained in https://github.com/cloud-carbon-footprint/cloud-carbon-coefficients - specifically in the Jupyter notebook at https://github.com/cloud-carbon-footprint/cloud-carbon-coefficients/blob/main/coefficients.ipynb

**Comment by ericksod** [comment]
Hey @aCampello! Hopefully the link that @davidmytton sent through is sufficient for now. We have added a note to our backlog though to review the docs and add in a little additional explanation https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/518. Going to close this one for now.
