### ISSUE TITLE
[SPIKE] AWS Compute Optimizer

### ISSUE THREAD

**Issue by aalva05-tw** [cloud-carbon-footprint/cloud-carbon-footprint#506]
- [x] Document approach
- [x] Align on display data for Recs Dashboard
- [x] Write implementation tickets

**Comment by dtoakley** [comment]
High level architecture diagram for this: https://app.diagrams.net/?splash=0&libs=aws4#G1dKW_gcnT40YFHXY3KOvyENxhPzojvhHc

**Comment by zhangtbj** [comment]
Hi @dtoakley ,

I found I cannot view this diagram, how can I or we view the Cloud Carbon Footprint documents publicly? (I already joined the Google group)

Thanks!

**Comment by dtoakley** [comment]
Hi @zhangtbj -- I changed the diagram permissions so that anyone with the link can view it - let me know how that goes!

**Comment by zhangtbj** [comment]
It still reports:
```
The file was not found. It does not exist or you do not have access. (Jordan (Tao Zhang), tao.zhang@nordcloud.com)
```
when I access the link https://app.diagrams.net/?splash=0&libs=aws4#G1dKW_gcnT40YFHXY3KOvyENxhPzojvhHc :(
Please help check. Thanks!

**Comment by dtoakley** [comment]
Hmm weird... Anyway, attaching here for you @zhangtbj:
![Mouse_Highlight_Overlay_and_CCF_Compute_Optimizer_drawio_-_diagrams_net](https://user-images.githubusercontent.com/2144730/142009561-c4495c63-8d91-4d17-bbbb-980cf8bcab95.png)

**Comment by zhangtbj** [comment]
Thank you so much @dtoakley !

BTW, is there any info or doc about this Compute Optimizer? And is it a new component just for AWS?

**Comment by dtoakley** [comment]
Yes, Compute Optimizer is an AWS specific service. You can read more about it here @zhangtbj : https://aws.amazon.com/compute-optimizer/
