### ISSUE TITLE
Metric tons / kg toggle applies to full recs dashboard

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#514]
**Context**
As a user looking to make small incremental improvements
I want to see recommendations data in kg
So that I can see more immediately the degree of difference I can make

**Assumptions**
- [x] When the metric tons button is highlighted and I click on the toggle, it becomes unselected and the kg button becomes highlighted
- [x] When the kg button is highlighted and I click on the toggle, it becomes unselected and the metric tons button becomes highlighted

**A/C's**
- [x] When I view the recs dashboard, I see the metric tons / kg toggle on the filter bar
- [x] When I initially land on the dashboard, I see the metric tons button highlighted by default and all data is shown in metric tons by default
- [x] When the metric tons button is highlighted, I see the carbon forecast data shown in metric tons and the carbon savings in the table shown in metric tons
- [x] When the kg button is highlighted, I see the carbon forecast data shown in kg and the carbon savings in the table shown in kg
- [x] When I view the units toggle on the filter bar, the filters are centered, and the toggles are right aligned
- [x] When I decrease the screen size, the units toggle falls below the filters
<img width="1002" alt="Screen Shot 2021-10-13 at 5 50 45 PM" src="https://user-images.githubusercontent.com/8618241/137217562-ac119d42-f844-4001-9bf1-252f3c21e3d1.png">

**Comment by ghost** [comment]
I can work on this.
