### ISSUE TITLE
Demo app has disclaimer noting intended use on desktop

### ISSUE THREAD

**Issue by aalva05-tw** [cloud-carbon-footprint/cloud-carbon-footprint#525]
- [x] When I click on the demo links from the microsite and I am on mobile, I see a pop up disclaimer "This demo is not optimized for use on mobile devices. For the best experience, please view it on a desktop."
- [x] When I see the pop up disclaimer, I can x out and proceed anyway
- [x] When I click on the demo links from the microsite and I am on desktop or ipad, I am taken directly there

![ccf-mobilewarning](https://user-images.githubusercontent.com/81026458/137360077-41c095d9-cc92-4772-8868-bfe13c5e3905.png)

**Comment by ghost** [comment]
Tested successfully on the demo site:

- While using my phone in landscape & portrait mode, the warning appeared.
- When clicking on the close button, the site loaded normally.
- When using my computer at a medium to large screen, the warning did not appear.
