### ISSUE TITLE
Can only set one filter at a time on Recommendations Dashboard

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#537]
### Preflight Checklist

- [ ] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - 
- **Browser:**
  - 

### Expected Behavior
- [ ] When I have a filter set on the recommendations page and I set an additional filter, both filters are applied to the data on the page
- [ ] When I deselect a cloud provider, the accounts, regions, and recommendation types for that cloud provider are deselected
- [ ] When I select an account for a cloud provider that was deselected, the cloud provider is reselected, as well as the regions and recommendation types for that cloud provider
- [ ] When I select a region for a cloud provider that was deselected, the cloud provider is reselected, as well as the accounts and recommendation types for that cloud provider
- [ ] When I select a recommendation type for a cloud provider that was deselected, the cloud provider is reselected, as well as the regions and accounts for that cloud provider
- [ ] When I deselect the last account filter set for a given cloud provider, then the cloud provider is deselected as well as its associated regions or recommendation types
- [ ] When I deselect the last region filter set for a given cloud provider, then the cloud provider is deselected as well as its associated accounts or recommendation types
- [ ] When I deselect the last recommendation type filter set for a given cloud provider, then the cloud provider is deselected as well as its associated regions or accounts

### Actual Behavior
- [ ] When I have a filter set for accounts and then select a new filter for the same cloud provider for regions or recommendation type, the accounts filter is removed and all accounts are once again selected
- [ ] When I have a filter set for regions and then select a new filter for the same cloud provider for accounts or recommendation type, the accounts filter is removed and all regions are once again selected
- [ ] When I have a filter set for recommendation type and then select a new filter for the same cloud provider for regions or accounts, the accounts filter is removed and all recommendation types are once again selected

### To Reproduce
* Apply a filter for accounts, 

### Additional Information

© 2021 Thoughtworks, Inc.

**Comment by ghost** [comment]
Unless I'm missing something, it looks like the expected behavior has already been met, at least on demo and prod.

I did notice that when I deselected everything, selected a single account, then deselected a region associated with the account, all the accounts that were associated with the remaining enabled regions were selected even though they weren't before.
