### ISSUE TITLE
Minor enhancement: Update theme-color to match header for the browsers that support it.

### ISSUE THREAD

**Issue by ghost** [cloud-carbon-footprint/cloud-carbon-footprint#541]
## Feature Suggestion
**Is your feature request related to a problem? Please describe.**
When loading the page in Safari, the theme-color being black causes the browser menu to be black as well.

**Describe the solution you'd like**
Updating theme-color to match the header color will cause the browser to match as well.

**Additional context**
Before:
![Before](https://user-images.githubusercontent.com/92883874/138497351-5adf31b1-ce58-48b0-9d74-faa70daf6c79.png)
After:
![After](https://user-images.githubusercontent.com/92883874/138497378-49e7e24d-5452-4187-9bd7-dc94f012b58b.png)

## Possible Implementation
This can be done by altering the "theme-color" meta tag in index.html:
`<meta name="theme-color" content="#3f51b5"/>`

**Comment by ghost** [comment]
Only downside is that it doesn't look great on mobile (due to the right/left padding for the notch on iOS devices), but that's a moot point since mobile isn't supported.
![IMG_CFF3C0EF00CB-1](https://user-images.githubusercontent.com/92883874/138500835-d4547cfd-b61e-45ae-bd80-cb069b3f4684.jpeg)

**Comment by drscarbrotw** [comment]
This seems like a great first item for me to work on. Thanks for the opportunity.

**Comment by drscarbrotw** [comment]
Read through the docs and watched the vids from wwdc and mdn.
Unable to change Safari browser theme color using the meta tag on macos 12.3 and safari 15.4 and tech preview 141.
Will continue working toward changing the meta theme-color tag to the header color.

refs
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
https://caniuse.com/meta-theme-color
https://css-tricks.com/meta-theme-color-and-trickery/
https://developer.apple.com/forums/thread/683403

**Comment by drscarbrotw** [comment]
Updated the theme-color meta prop to match PrimaryBlue color theme and submitted pull request.
