### ISSUE TITLE
Add support for GCP Tau T2D (AMD EPYC Gen 3) instance types

### ISSUE THREAD

**Issue by davidmytton** [cloud-carbon-footprint/cloud-carbon-footprint#548]
Following https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/332 GCP now also has support for AMD EPYC Gen 3 with their Tau T2D instance types: https://cloud.google.com/blog/products/compute/compute-engine-tau-t2d-vms-now-available-for-scale-out-workloads

This ticket is to add support for that instance type.

**Comment by 4upz-tw** [comment]
Hi @davidmytton, thanks for being so on top of this! Were you thinking of submitting a pull request for this? Otherwise, we'd be happy to prioritize it and get it done!

**Comment by davidmytton** [comment]
Could you assign to me please - I'll get it done in the next few days. Should be quite a small fix!

**Comment by 4upz-tw** [comment]
Sounds good! I went ahead and assigned you.

**Comment by davidmytton** [comment]
2 PRs opened:

1. Updated coefficient calculations: https://github.com/cloud-carbon-footprint/cloud-carbon-coefficients/pull/10
2. Updated coefficients, tests and GCP instance reference: https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/555

**Comment by ericksod** [comment]
Awesome @davidmytton - we'll review soon!
