### ISSUE TITLE
Minor refactor: Replace "useKilograms" boolean with enum or union type

### ISSUE THREAD

**Issue by ghost** [cloud-carbon-footprint/cloud-carbon-footprint#550]
## Feature Suggestion
**Is your feature request related to a problem? Please describe.**
The variable "useKilograms" is actually a choice between Kilograms and Metric Tons. While having only 2 states makes it easy to justify using a boolean, it's a little ambiguous what is meant if useKilograms is false.

**Describe the solution you'd like**
Instead of a boolean, use an enum or union type.

## Possible Implementation
In addition to the type itself, move the associated multiplier and labels to a mapping or function that takes in an instance of that type. Back this mapping/function up with a unit test so that if a new unit of measure is added to the type, the build fails until the mapping/function has been added for the new entry.

**Comment by camtittle** [comment]
Hey could I work on this issue @ericksod? :)

**Comment by ericksod** [comment]
Yes please, @camtittle! I will assign you and move to in progress
@4upz for visibility

**Comment by 4upz** [comment]
@camtittle Thanks for taking this on! Feel free to let us know if you have any questions or need any direction/support

**Comment by Ankitchaudharyy** [comment]
Can I work on this issue?

**Comment by 4upz** [comment]
Hi @Ankitchaudharyy , I believe that @camtittle is still working on this since he is assigned. Unless he says differently, I'd recommend taking a look at our [project board's](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/projects/1) "Ready to Do" column for a contributor issue that isn't assigned

**Comment by camtittle** [comment]
Hey, yeah I'm still working on this @Ankitchaudharyy

**Comment by camtittle** [comment]
PR opened for this issue https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/962

**Comment by 4upz** [comment]
@camtittle Thanks! Will give it a look
