### ISSUE TITLE
[SPIKE] Automatic refresh of permissions token AWS

### ISSUE THREAD

**Issue by ccasher** [cloud-carbon-footprint/cloud-carbon-footprint#551]
https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html
^ java not javascript, whoops!

- [ ] Discover potential path(s) forward for automatic refresh of tokens
- [ ] Work in Spike repo

**Comment by pcanham** [comment]
Just checking would this spike ticket, help with deploying ccf using AWS ECS and using IAM roles?

**Comment by dtoakley** [comment]
Hi @pcanham I started looking into this today, but realized I don't quite have enough context on when and how this issue occurs. I've asked one of our teams at Thoughtworks for more information, but I'm also interested in your use case, and how it might relate to this issue. 

Could you say more about how you're trying to deploy CCF using ECS, and any problems that have come up with IAM roles?

**Comment by dtoakley** [comment]
Spent some more time looking into this and it seems there are two potential use cases:
1. For local development when there is a custom authentication mechanism that requires manual refreshing of tokens, we could add support to CCF to automate that process. However in given use case it was a custom internal auth process, so we're not able to do so at the time being. 
2. When deploying to an AWS EC2 instance -- but the `EC2-METADATA` credentials option has already been added to support this, along with corresponding Terraform modules to automate the deployment. 

For now, I'm moving this back to analysis and we can re-prioritize as we learn more about other use cases.

**Comment by pcanham** [comment]
Hi @dtoakley sorry in the slow reply back, I have been looking into deploying the ccf API and the ccf client into two containers running on ECS fargate so I don't have any infrastructure to maintain. But I have been seeing issues around the container being able to either automatically get access keys or finding out what IAM role has been assigned to the task definition.

I am no javascript developer but I found the following bug report, where it look like you have to add in something very similar to the EC2 implementation (EC2-METADATA) but called ECS-METADATA

https://github.com/aws/aws-sdk-js/issues/1878

I can provide an example task definition and example IAM roles which i have assigned to them if it will help? 

Within the task definition i set the environment variable "AWS_TARGET_ACCOUNT_ROLE_NAME" so the application was aware of what role it should be assuming, the only part i have been having issues with without having to hard code the keys is how i can automatically pass over temporary keys

**Comment by amberstarlight** [comment]
@pcanham yes, the AWS authentication would need to also support the ECS credentials that containers get. I've added this to the AWS package in #849, this should let the task in the container auth with AWS.
