### ISSUE TITLE
[SPIKE] Decouple client and api for performance

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#556]
**Context**
As a user of CCF
I want to experience quicker loading times
So that I have trust in the application and it is more realistic for me to use on a daily basis

**A/C's**
- [x] Consider current and future architecture
- [x] Make spike branch or document possible solutions

**Comment by 4upz-tw** [comment]
I've found a few approaches we could use and compiled some notes within this Google Doc: https://docs.google.com/document/d/1iBe5ztuPyedZHjXFV6Iz1dngAprlNI1epr8mAzcm3y8/edit?usp=sharing

**Comment by 4upz-tw** [comment]
After aligning with the devs on the noted approaches in the Google Doc, we're going to move forward with doing a code spike on approach 3 surrounding operation polling to see if it's a good approach to take.

**Comment by dtoakley** [comment]
Finally got around to reviewing this -- and it's a solid write up. Thanks @4upz-tw! 

Closing this spike ticket off.
