### ISSUE TITLE
Any plan to add Azure support for the CCF Lookup Table?

### ISSUE THREAD

**Issue by zhangtbj** [cloud-carbon-footprint/cloud-carbon-footprint#570]
## Feature Suggestion
**Is your feature request related to a problem? Please describe.**
I saw CCF currently supports **AWS** and **GCP** in 
https://www.cloudcarbonfootprint.org/docs/creating-a-lookup-table

But there is no support for Microsoft Azure.

Is there any plan to add Azure support in the future?

Thanks!

**Comment by zhangtbj** [comment]
Duplicated as https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/498

Let us monitor by that issue.

**Comment by dtoakley** [comment]
Thanks @zhangtbj -- I'm going to close this issue if that is okay, as we'll track it in #498

**Comment by zhangtbj** [comment]
Sure, @dtoakley 

BTW, do you know what is the plan for #498 and when you plan to achieve that?

Thanks!
