### ISSUE TITLE
Calculate Total Embodied Emissions in Coefficients Repo

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#579]
Data source: https://docs.google.com/spreadsheets/d/1XPHG0ta7Jlaawfr2bLS3Xj8xyLxqJskhmwVPiQygFM8/edit#gid=224728652

A/C
- [x] Add calculations for AWS Total embodied emissions
- [x] Add calculations for GCP Total embodied emissions  
- [x] Add calculations for Azure Total embodied emissions

**Comment by davidmytton** [comment]
Implementation notes:

### [Scope 3 Ratios](https://docs.google.com/spreadsheets/d/1YhtGO_UU9Hc162m7eQKYFQOnV4_yEK5_lgHYfl02JPE/edit#gid=2090774556)

Metric | Value
-- | --
Manufacturing emissions for a mono socket, low DRAM, no local storage commodity rack server | 1000 kgCO₂eq
Commodity rack server lifespan | 4 years
Hourly manufacturing emissions conversion factor - linearly amortised | 0.0289 gCO₂eq/hour[^1]
DRAM Threshold to unlock additional Scope 3 emissions | 16 GB
Manufacturing emissions for the threshold DRAM amount | 22 kgCO₂eq[^2]
Manufacturing emissions per additional CPU | 100 kgCO₂eq
Manufacturing emissions per additional HDD | 50 kgCO₂eq
Manufacturing emissions per additional SSD | 100 kgCO₂eq
Manufacturing emissions per additional GPU Card | 150 kgCO₂eq

[^1]: `[Manufacturing emissions for a mono socket, low DRAM, no local storage commodity rack server = 1000 kgCO₂eq]/[Commodity rack server lifespan = 4 years]/12/30/24`
[^2]: Based on [Dell PowerEdge R740 Life-Cycle Assessment](https://docs.google.com/spreadsheets/d/1YhtGO_UU9Hc162m7eQKYFQOnV4_yEK5_lgHYfl02JPE/edit#gid=954946016). 533 kgCO₂eq for 12*32GB DIMMs Memory = 384 GB. `(533 / 384) * [DRAM Threshold to unlock additional Scope 3 emissions = 16 GB]`

### [EC2 Instances](https://docs.google.com/spreadsheets/d/1YhtGO_UU9Hc162m7eQKYFQOnV4_yEK5_lgHYfl02JPE/edit#gid=504755275)

Calculation is made up of 4 components:

#### `AG`: Platform Additional Memory Scope 3 Emissions

If `Platform Memory` greater than `DRAM Threshold to unlock additional Scope 3 emissions`:

`AG = (Platform Memory - DRAM Threshold to unlock additional Scope 3 emissions) * (Manufacturing emissions for the threshold DRAM amount / DRAM Threshold to unlock additional Scope 3 emissions)`

else

`AG = 0`

####  `AH`: Platform Additional Storage Scope 3 Emissions

If `Storage Type` = `SSD`, `Storage Emissions Factor` = `Manufacturing emissions per additional SSD`
else, `Storage Emissions Factor` = `Manufacturing emissions per additional HDD`

`AD = Platform Storage Drive Quantity * Storage Emissions Factor`

####  `AI`: Platform Additional GPU Scope 3 Emissions

If `Platform GPU Quantity` is not `N/A`

`AI = Platform GPU Quantity * Manufacturing emissions per additional GPU Card`

####  `AJ`: Platform Additional CPU Scope 3 Emissions

[Lookup CPU count for platform](https://docs.google.com/spreadsheets/d/1YhtGO_UU9Hc162m7eQKYFQOnV4_yEK5_lgHYfl02JPE/edit#gid=1695769209) = `Platform Number of CPU Socket(s)`.

`AJ = (Platform Number of CPU Socket(s) - 1) * Manufacturing emissions per additional CPU`

####  `AK`: Total Platform Scope 3 Emissions  (kgCO₂eq)

`AK = [Manufacturing emissions for a mono socket, low DRAM, no local storage commodity rack server] + AG + AH + AI + AJ`

**Comment by davidmytton** [comment]
Work begun in https://github.com/davidmytton/cloud-carbon-coefficients/tree/579-embodied

Started with tidying up the notebook with [`nbdev`](https://nbdev.fast.ai/) which strips metadata so commit can be diffed better. Also implemented basic unit tests (closes https://github.com/cloud-carbon-footprint/cloud-carbon-coefficients/issues/3 when merged).

Next: update AWS instances data from Google Sheet, then implement calculations.

**Comment by davidmytton** [comment]
Some AWS CPU platforms listed against instances in [the EC2 Sheet](https://docs.google.com/spreadsheets/d/1YhtGO_UU9Hc162m7eQKYFQOnV4_yEK5_lgHYfl02JPE/edit#gid=504755275) are missing from the current list of CPUs.

Added into the list of instances:

* E5-2651 v2 = Ivybridge, as per https://hwbot.org/hardware/processor/xeon_e5_2651_v2/
* E5-2666 v3 = Haswell, as per https://www.cpu-world.com/CPUs/Xeon/Intel-Xeon%20E5-2666%20v3.html
* 8124M = Skylake, as per https://en.wikichip.org/wiki/intel/xeon_platinum/8124m
* 8275CL = Cascade Lake, as per https://www.cpu-world.com/CPUs/Xeon/Intel-Xeon%208275CL.html
* EPYC 7R32 = AMD EPYC 2nd Gen, as per https://www.anandtech.com/tag/epyc-7r32
* E5-2676 v3 = Haswell, as per https://www.cpu-world.com/CPUs/Xeon/Intel-Xeon%20E5-2676%20v3.html
* 8259CL = Cascade Lake, as per https://www.cpu-world.com/CPUs/Xeon/Intel-Xeon%208259CL.html
* E5-2686 v4 = Broadwell, as per https://en.wikichip.org/wiki/intel/xeon_e5/e5-2686_v4
* 8175M = Skylake, as per https://www.cpu-world.com/CPUs/Xeon/Intel-Xeon%208175M.html
* EPYC 7571 = AMD EPYC 1st Gen, as per https://en.wikipedia.org/wiki/Epyc#First_generation_Epyc_(Naples)
* 8252C = Cascade Lake, as per https://browser.geekbench.com/v5/cpu/5544326
* Core i7-8700B = Coffee Lake, as per https://ark.intel.com/content/www/us/en/ark/products/134905/intel-core-i78700b-processor-12m-cache-up-to-4-60-ghz.html
* 8176M = Sky Lake, as per https://www.intel.com/content/www/us/en/products/sku/120505/intel-xeon-platinum-8176m-processor-38-5m-cache-2-10-ghz/specifications.html
* 8151 - Sky Lake, as per https://serverfault.com/questions/974865/information-about-intelr-xeonr-platinum-8151-cpu-3-40ghz-used-in-some-aws

Excluded 

* 8375C = Ice Lake. We do not have performance stats for this CPU architecture.

**Comment by davidmytton** [comment]
Azure coefficients have changed. This is due to the addition of new Skylake models that now get included in the calculation:

Before:

```
Average: Min Watts = 0.74
Average: Max Watts = 3.54
Average: GB/Chip = 80.47
```

After

```
Average: Min Watts = 0.73
Average: Max Watts = 3.53
Average: GB/Chip = 80.36
```

AWS coefficients have also changed. This is due to including many more instance types that were previously not covered from [the EC2 sheet](https://docs.google.com/spreadsheets/d/1YhtGO_UU9Hc162m7eQKYFQOnV4_yEK5_lgHYfl02JPE/edit#gid=504755275)

Before:

```
Average: Min Watts = 0.74
Average: Max Watts = 3.50
Average: GB/Chip = 80.69
```

After:

```
Average: Min Watts = 1.24
Average: Max Watts = 5.00
Average: GB/Chip = 61.89
```

GCP coefficients have changed. This is due to new Skylake models as well.

Before:

```
Median: Min Watts = 0.68
Median: Max Watts = 4.11
```

After:

```
Median: Min Watts = 0.68
Median: Max Watts = 4.08
```

**Comment by davidmytton** [comment]
AWS coefficients are now implemented. For discussion: the export format.

**Comment by davidmytton** [comment]
@ericksod @dtoakley @camcash17 I've implemented the calculations for AWS. Before I finish with Azure and GCP, could you let me know how you want the factors exported? There's a long table of ~620 AWS instances with the values, as in [the Google Sheet](https://docs.google.com/spreadsheets/d/1YhtGO_UU9Hc162m7eQKYFQOnV4_yEK5_lgHYfl02JPE/edit#gid=504755275), so it's not practical to output them in the notebook. How will CCF import them? CSV?

**Comment by ccasher** [comment]
Hi @davidmytton, awesome work! Currently, we are just importing the values manually into CCF, so until we have a more automated process, the output as CSV should be fine.

**Comment by davidmytton** [comment]
Ready for review in https://github.com/cloud-carbon-footprint/cloud-carbon-coefficients/pull/11

**Comment by ccasher** [comment]
Very nice work @davidmytton! I just reviewed and it looks good to me. We really appreciate your work and will get that spreadsheet updated.

**Comment by dtoakley** [comment]
LGTM!
