### ISSUE TITLE
Create separate cache files for each groupBy

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#580]
**Context**

**A/C's**
- [x] Given I specify a particular groupBy, I see a new file created for that particular groupBy time period
- [x] When the cache file is created, I want to see the name of the grouping in the file
- [x] Given I have already loaded with groupBy=Day, when I update the API config to groupBy=month, then it reloads it by month, and a cache file for month is created (each combination)
- [x] Given I am a user viewing the graph on the UI, I see nothing weird on it (eg vertical points, things that don't match the grouping)
- [x] Given I load up the recs page before the emissions page, when I go to the emissions page, I see what I expect
- [ ] Given the api is set to groupBy=Month/week/quarter, the start and end date will be automatically set to the start of the month/week/quarter 

**Testing**
- [x] (test dates not at start of month)

**Tech Notes**
- cache file name - use string interpolation instead of all new constants

**Comment by dtoakley** [comment]
This is working as expected now -- only usage within the start and end dates requested are set back in the API response, and the timestamps are set to the first day of the group by period (week, month, etc). Closing this one out - we will have a another ticket to improve the time periods shown on the front-end.
