### ISSUE TITLE
[SPIKE] Investigate Replacing the Cache with a Database

### ISSUE THREAD

**Issue by ghost** [cloud-carbon-footprint/cloud-carbon-footprint#583]
**Is your feature request related to a problem? Please describe.**
The current implementation of getting the data from the server to the client involves:
1. Loading the raw data from the cloud providers into the backend.
2. Transforming that data into usable estimations data.
3. Caching the estimations data for steps 1 and 2 into a JSON file.
4. Sending the estimations data to the client.
5. Parsing, filtering, and displaying the estimations data on the client.

This poses a few problems, namely the memory footprint on the backend and client in steps 3 and 5, the payload size in step 4, and the processing footprint in step 5.

**Describe the solution you'd like**
I propose utilizing a database in place of a JSON cache.

1. The database would be updated daily with the previous day's usage after being converted into estimations. Because this call is only for a single day instead of a year, both the memory footprint and call duration should be much smaller in scope.
2. The filters would move into where clauses on the select statement we use to fetch data.
    * A read-only user for the database should be employed when generating such a query, for security purposes.
3. A materialized view (cached representation of a query) would be maintained for the initial state of the Home and Recommendations page.
    * Because data is updated once a day, the view would be refreshed once a day. This would allow for nearly instantaneous display of the full overview of data.
    * Subsequent filters would take longer, but the overview would be ready for the user instantaneously.
4. The data that the client needs would be generated on the backend with queries against the database, instead of using TypeScript on the frontend.
    * This will take advantage of every performance improvement the chosen database has ever made.
    * This will cut the memory footprint on the frontend and backend to as small as it can be.

The database can be maintained through a tool such as FlyWay or Liquibase, and we can provide a docker compose file for spinning up a container for developers to use for housing their own database for local testing.

**Describe alternatives you've considered**
NoSQL is a possibility for data with higher granularity (or more numerous accounts), but for now a relational database performs adequately with the dataset I tested with. It also presents issues with how we aggregate data in a non-relational database.

**Additional context**
I tested this out locally to get an idea of what kind of performance increases we should get.

- The database of choice was Postgres.
- Data entered was daily data for a year from nearly 200 accounts, totaling in a little over 3 million rows.
- A single select query against the entire dataset grouped by timestamp (the data needed for the graph on the home page) took between 1 and 1.5 seconds. Comparatively, the current non-database implementation was taking over 10 minutes, even with the cached JSON.
- A single select query against a materialized view generated from the previous query took between 50 and 100 milliseconds. Considering this is in effect a cache on top of something replacing a cache, this is expected.

**Comment by ghost** [comment]
Below are the SQL queries I used to generate the table for my test, not including the actual dataset.
* I think that account should have a foreign key on cloud_provider, instead of estimations. This was more of a rough draft than a final result.

[SQL Used (without actual data).zip](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/files/7542289/SQL.Used.without.actual.data.zip)
![Table Layout](https://user-images.githubusercontent.com/92883874/141870960-cf325194-eba2-40a2-8133-25cc8eabfddd.png)

**Comment by ccasher** [comment]
Hello! We have since made updates to integrate MongoDB, please review our [documentation](https://www.cloudcarbonfootprint.org/docs/data-persistence-and-caching)! Thanks for contributing!
