### ISSUE TITLE
AWS Embodied Emissions

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#588]
**Context**
We would like to comply with the SCI standard, and to do so, we will implement embodied emissions for each cloud provider.

**Related Issues**
https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/524

**A/C's**
- [ ] AWS embodied emissions should be included in compute estimates
- [ ] (After QA) Update Methodology to explain the inclusion of embodied emissions, the calculation, include public spreadsheet, and any AWS specific knowledge

**Tech Tasks**
- [x] Include total embodied emissions mapping to instance type (family) in AWS package
- [x] TR will be usage time period (group by)
- [x] EL may be constant in core package? Maybe you can change this given the cloud provider - possibly put in AWS cloud constants eg. serverExpectedLifespan
- [x] RR will be # of vCPUs, which we have
- [x] TR will be vCPUs over largest instance of that family
- [x] Can use estimator inside CostAndUsageReports class to estimate embodied emissions when the usage row includes a machine type that is in the list in the [spreadsheet](https://docs.google.com/spreadsheets/d/1k-6JtneEu4E9pXQ9QMCXAfyntNJl8MnV2YzO4aKHh-0/edit#gid=0)

**Comment by davidmytton** [comment]
How will this link to https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/579 ?

**Comment by dtoakley** [comment]
This is looking good. I pushed a small commit to removed unused code in `packages/aws/src/lib/AWSInstanceTypes.ts` - but other than that it's looking good. Moving this to done as the methodology write up will be handled in other ticket. 

@davidmytton -- I think Cam will follow up with you within #579
