### ISSUE TITLE
Azure Embodied Emissions

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#589]
**Context**
We would like to comply with the SCI standard, and to do so, we will implement embodied emissions for each cloud provider.

**Related Issues**
https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/524

**A/C's**
- [x] Azure embodied emissions should be included in compute estimates
- [x] (After QA) Update Methodology to explain the inclusion of embodied emissions, the calculation, include public spreadsheet, and any Azure specific knowledge

**Tech Tasks**
- [x] Include total embodied emissions mapping to instance type (family) in Azure package
- [x] TR will be usage time period (group by)
- [x] EL may be constant in core package? Maybe you can change this given the cloud provider - possibly put in Azure cloud constants eg. serverExpectedLifespan
- [x] RR will be # of vCPUs, which we have
- [x] TR will be vCPUs over largest instance of that family
- [x] Can use estimator inside ConsumptionManagement class to estimate embodied emissions when the usage row includes a machine type that is in the list in the [spreadsheet](https://docs.google.com/spreadsheets/d/1k-6JtneEu4E9pXQ9QMCXAfyntNJl8MnV2YzO4aKHh-0/edit#gid=0)

**Comment by dtoakley** [comment]
I reviewed this and it look good to me!
