### ISSUE TITLE
Data points on graph UI should update to reflect the groupBy period

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#591]
#### Overview
With an improvement to the cache structure and making separate cache files for each groupBy option, we updated how the API functions, and now we need to update how the UI displays the information. Because the API will return data points based on calendar month, week or year, regardless of whether the data selected starts at the 1st of the month or another day. Therefore, the UI for week, month or year should not indicate the exact date.

#### Related issues/Dependencies:
Dependent on https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/529
Dependent on https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/580

## Acceptance Criteria
- [x] When I view the emissions graph and my data is grouped by year, I see a data point for each year with the year listed for all the years that are included in the date range I specified
- [x] When I view the emissions graph and my data is grouped by month, I see a data point for each month and no day number specified (January 2021, February 2021, March 2021...) for all the months that are included in the date range I specified
- [ ] When I grouped by month and select a date range mid month to mid month, eg Oct 12-Nov 14, I see a data point for October with the total from Oct 12-Oct 31, and a data point for November with the total from Nov 1 - 14
- [ ] When I view the emissions graph and my data is grouped by week, I see a data point for each week by week and month(s) (Week 1, Jan; Week 5, Jan/Feb; Week 52, Dec/Jan) for all the weeks that are included in the date range I specified
- [x] When I view the emissions graph and my data is grouped by day, I see a data point for each day with the date indicated for the date range I have selected. (eg. November 8, 2021)
- [x] * I'm not sure the current x axis labels for group by week or day, but let's decide on this after seeing what current behavior is
- [x] When I view grouped by quarter, I see a data point for each quarter, labeled Quarter 1, Quarter 2, etc.

## Tech Tasks
- [x] Add appropriate test coverage, including edge cases.
- [x] Run Changesets, bump any packages that have been updated/changed
- [ ] Did you make changes to the client, api or cli package? If so, considering updating the create-app templates.
- [x] If any create-app templates have been updated, make sure to run the [test-create-app script](https://docs.google.com/document/d/1Ei6Cb2DjwEJUNtpULJSxbOuIdAfCARERgE3BSsKWrsc/edit) to ensure it still works properly.

### Tech Notes
Add this object into the FootprintEstimates object and handle the display name on the client based on the options given

serviceEstimates: [{cloudProvider: "AWS", accountName: "aws account 0", serviceName: "ebs",…},…]
periodStartDate: "2021-03-25T00:00:00.000Z"
periodEndDate: "2021-04-25T00:00:00.000Z"
groupBy: "week"
timestamp: ""2021-03-25T00:00:00.000Z" // phase out later
## Review Tasks
- [ ] eg. specific QA details, update methodology, or update microsite

**Comment by dtoakley** [comment]
I've QA'd this locally and checked it in staging too -- all looking good! Closing.
