### ISSUE TITLE
Azure - multiple subscriptions fails due to running in parallel

### ISSUE THREAD

**Issue by cliftonc** [cloud-carbon-footprint/cloud-carbon-footprint#610]
## Feature Suggestion
I am pulling in a lot of Azure subscriptions (like 50+) and the current implementation attempts to get them all in parallel, which causes lots of issues like rate limiting and out of memory.

**Describe the solution you'd like**
Re-configure it to work in series (slower, but works).

**Describe alternatives you've considered**
None

**Additional context**
None

## Possible Implementation
I will submit a PR.

**Comment by dtoakley** [comment]
Closing this for now, as we have implemented back-off and retry logic that helps resolve this. We'll still look for further performance improvements though, e.g. via a different API or scope of the current API.
