### ISSUE TITLE
Dedicated Host footprint calculation double counts the host and instance

### ISSUE THREAD

**Issue by mfulleratlassian** [cloud-carbon-footprint/cloud-carbon-footprint#635]
### Issue Details

Looking at the carbon allocations for AWS I can see that HostUsage (dedicated host lines) and the HostBoxUsage (Instances on the dedicated hosts) both get a kilowatt consumption value. I am trying to understand how the Carbon Footprint calculation works here as having the Dedicated host allocation and the instance that runs on the dedicated host have a kilowatt allocation would mean we are double counting the kilowatt hrs.

### Expected Behavior

Underlying HostUsage is allocated kilowatt hours equal to the whole dedicated host, Instances running on that dedicated host have no kilowatt allocations as the carbon impact was calculated at the dedicated host level.

### Actual Behavior

Underlying HostUsage is allocated kilowatt hours, Instances running on that dedicated host are allocated kilowatt hours also.

### To Reproduce

Run carbon estimates over AWS usage including dedicated host usage. Review carbon footprint total for dedicated hosts.

### Screenshots
![Screen Shot 2021-12-15 at 11 19 05 am](https://user-images.githubusercontent.com/3432067/146099939-d9581246-8b35-4e96-9a82-2d77d11fc987.png)

### Additional Information

I have had a private chat with Dan Lewis-Toakley who has a little more context to our usecase.

© 2021 Thoughtworks, Inc.

**Comment by ccasher** [comment]
Hi Mike, this should be updated and fixed now with our latest release!
