### ISSUE TITLE
CLI generates an empty CSV.

### ISSUE THREAD

**Issue by gregoryb** [cloud-carbon-footprint/cloud-carbon-footprint#636]
### Preflight Checklist

- [x ] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

OSX 11.4
NodeJS 16.13

### Expected Behavior

A non empty CSV file.

### Actual Behavior

TABLE or CSV is empty using cli.

### To Reproduce
```
$ yarn start-cli --startDate "2021-12-01" --endDate "2021-12-14" --groupBy "day" --format "table"
```

### Additional Information

Dashboard is working.

**Comment by ericksod** [comment]
Hi @gregoryb!
Could you possibly share which cloud providers you are using and confirm you have set the appropriate config options for each provider?

**Comment by gregoryb** [comment]
I'm using Azure only. AWS is disabled because i'm not able to configure it (permission issue on my side)

```
AWS_TARGET_ACCOUNT_ROLE_NAME=ccf-athena
AWS_USE_BILLING_DATA=false
AWS_ATHENA_DB_NAME=xxxxxx
AWS_ATHENA_DB_TABLE=carbonfootprint
AWS_ATHENA_REGION=eu-west-3
AWS_ATHENA_QUERY_RESULT_LOCATION=s3://xxxx
AWS_BILLING_ACCOUNT_ID=xxxxx
AWS_BILLING_ACCOUNT_NAME=carbonfootprint
AWS_ACCOUNTS=[]
AWS_AUTH_MODE=default
AWS_PROXY_ACCOUNT_ID=your-proxy-account-id # Only needed for AWS_AUTH_MODE 'GCP' (e.g. deploying to GCP)
AWS_PROXY_ROLE_NAME=your-proxy-role-name # Only needed for AWS_AUTH_MODE 'GCP' (e.g. deploying to GCP)
GCP_USE_BILLING_DATA=false
GOOGLE_APPLICATION_CREDENTIALS=/path/to/your/credentials.json
GCP_BIG_QUERY_TABLE=your-billing-export-table
GCP_BILLING_PROJECT_ID=your-billing-account-id
GCP_BILLING_PROJECT_NAME=your-billing-account-name
GCP_PROJECTS=[]
AZURE_USE_BILLING_DATA=true
AZURE_CLIENT_ID=e823b43f-c740-xxxxxxx
AZURE_CLIENT_SECRET=~Qy7Q~OD1OnHxxxxxxxxx
AZURE_TENANT_ID=554fa9dxxxxxx
AZURE_AUTH_MODE=default
```

**Comment by dtoakley** [comment]
Hey @gregoryb -- is you `.env` config file inside your `packages/cli` directory? 

I just tested on my side with Azure, and your example command worked okay, once I copied my `.env` file from the `packages/api` directory.

**Comment by gregoryb** [comment]
@dtoakley It works now with your "tips".

**Comment by dtoakley** [comment]
Great to hear thanks @gregoryb -- closing this issue off for now!
