### ISSUE TITLE
Update Azure consumption management get estimates method to filter dates for modern channel usage

### ISSUE THREAD

**Issue by ccasher** [cloud-carbon-footprint/cloud-carbon-footprint#648]
**CONTEXT**
For the consumption management usage details list API, $filter is only supported for legacy Azure channels (Enterprise Agreement, Web Direct) - NOT for modern channels.

Any modern channel usage does is not captured within the filtered date range (ie, if you only request data for a specific week, the api with fetch data for that entire month regardless)

Using TDD, we should filter the usageRows in the getEstimates method before mapping over them. The filter applied to the usageRows array should be for the same data range.

**Comment by dtoakley-tw** [comment]
So this look good, but I question whether the endDate filtering should be exclusive -- I'm currently of the opinion it should be inclusive :) But that doesn't need to block this ticket - we can handle that after aligning on the behavior of the API.

**Comment by dtoakley** [comment]
QA tested as well. Closing this one off!
