### ISSUE TITLE
Some usage types cause "Cannot convert undefined or null to object" with create-lookup-table cli

### ISSUE THREAD

**Issue by mfulleratlassian** [cloud-carbon-footprint/cloud-carbon-footprint#650]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - macOS 11.6.1
 
### Expected Behavior

All usage types work without errors

### Actual Behavior

List of usage types that cause error "Something went wrong: Cannot convert undefined or null to object":

serviceName,region,usageType,usageUnit,vCpus
AmazonES,eu-west-1,EU-HeavyUsage:t3.medium.elasticsearch,Hrs,
AmazonES,us-west-2,USW2-HeavyUsage:r5.4xlarge.elasticsearch,Hrs,
AmazonES,eu-central-1,EUC1-HeavyUsage:c5.xlarge.search,Hrs,
AmazonES,us-east-1,HeavyUsage:i3.4xlarge.elasticsearch,Hrs,
AmazonES,ap-southeast-1,APS1-HeavyUsage:c5.2xlarge.elasticsearch,Hrs,
AmazonES,us-east-1,HeavyUsage:r5.4xlarge.search,Hrs,
AmazonES,us-east-1,HeavyUsage:r4.xlarge.elasticsearch,Hrs,
AmazonES,us-west-1,USW1-HeavyUsage:m5.large.elasticsearch,Hrs,
AmazonEC2,us-east-1,BoxUsage:c6i.large,Hrs,2
AmazonES,us-west-2,USW2-HeavyUsage:c5.2xlarge.elasticsearch,Hrs,
AmazonES,us-east-1,HeavyUsage:r5.2xlarge.elasticsearch,Hrs,
AmazonES,us-east-1,HeavyUsage:m5.large.elasticsearch,Hrs,
AmazonES,us-east-1,HeavyUsage:c5.xlarge.search,Hrs,
AmazonES,us-west-2,USW2-HeavyUsage:c5.9xlarge.elasticsearch,Hrs,
AmazonES,eu-central-1,EUC1-HeavyUsage:r5.4xlarge.search,Hrs,
AmazonES,us-east-1,HeavyUsage:r5.xlarge.elasticsearch,Hrs,
AmazonEC2,us-east-1,BoxUsage:m6a.xlarge,Hrs,4
AmazonES,us-west-2,USW2-HeavyUsage:i3.8xlarge.elasticsearch,Hrs,
AmazonES,ap-southeast-2,APS2-HeavyUsage:i3.xlarge.elasticsearch,Hrs,
AmazonEC2,us-west-2,USW2-BoxUsage:m6a.large,Hrs,2
AmazonEC2,us-west-2,USW2-BoxUsage:c6i.large,Hrs,2
AmazonES,eu-west-1,EU-HeavyUsage:m5.2xlarge.elasticsearch,Hrs,
AmazonES,us-west-1,USW1-HeavyUsage:m5.2xlarge.elasticsearch,Hrs,
AmazonES,us-east-1,HeavyUsage:m5.4xlarge.elasticsearch,Hrs,
AmazonES,eu-west-1,EU-HeavyUsage:c5.9xlarge.elasticsearch,Hrs,
AmazonES,us-east-1,HeavyUsage:t3.medium.elasticsearch,Hrs,
AmazonES,eu-west-1,EU-HeavyUsage:c5.2xlarge.elasticsearch,Hrs,
AmazonES,us-west-2,USW2-HeavyUsage:r5.xlarge.elasticsearch,Hrs,
AmazonES,us-east-1,HeavyUsage:c5.xlarge.elasticsearch,Hrs,
AmazonES,us-west-2,USW2-HeavyUsage:c5.xlarge.search,Hrs,
AmazonES,us-west-2,USW2-HeavyUsage:c5.large.elasticsearch,Hrs,
AmazonES,ap-southeast-2,APS2-HeavyUsage:r5.2xlarge.elasticsearch,Hrs,
AmazonES,ap-southeast-1,APS1-HeavyUsage:c5.9xlarge.elasticsearch,Hrs,
AmazonES,us-west-2,USW2-HeavyUsage:c5.xlarge.elasticsearch,Hrs,
AmazonEC2,us-west-2,USW2-BoxUsage:g5.xlarge,Hrs,4
AmazonES,eu-west-1,EU-HeavyUsage:c5.xlarge.elasticsearch,Hrs,
AmazonES,us-east-1,HeavyUsage:c5.large.elasticsearch,Hrs,
AmazonES,us-west-2,USW2-HeavyUsage:i3.2xlarge.elasticsearch,Hrs,
AmazonES,us-east-1,HeavyUsage:c5.2xlarge.elasticsearch,Hrs,
AmazonES,us-west-2,USW2-HeavyUsage:c5.large.search,Hrs,
AmazonES,us-west-2,USW2-HeavyUsage:i3.large.elasticsearch,Hrs,
AmazonES,us-east-1,HeavyUsage:m6g.xlarge.elasticsearch,Hrs,
AmazonES,us-west-1,USW1-HeavyUsage:m5.xlarge.elasticsearch,Hrs,
AmazonEC2,us-east-1,SpotUsage:c6i.xlarge,Hrs,4
AmazonEC2,ap-southeast-2,APS2-BoxUsage:c6i.2xlarge,Hrs,8
AmazonES,us-west-2,USW2-HeavyUsage:r5.2xlarge.elasticsearch,Hrs,
AmazonES,eu-central-1,EUC1-HeavyUsage:m5.xlarge.elasticsearch,Hrs,
AmazonEC2,eu-west-1,EU-BoxUsage:m6a.large,Hrs,2
AmazonES,us-east-1,HeavyUsage:c5.9xlarge.elasticsearch,Hrs,
AmazonES,us-west-2,USW2-HeavyUsage:m5.large.elasticsearch,Hrs,
AmazonES,us-west-2,USW2-HeavyUsage:i3.xlarge.elasticsearch,Hrs,
AmazonES,ap-southeast-2,APS2-HeavyUsage:c5.xlarge.search,Hrs,
AmazonES,ap-southeast-1,APS1-HeavyUsage:t3.medium.elasticsearch,Hrs,
AmazonES,eu-central-1,EUC1-HeavyUsage:t3.medium.elasticsearch,Hrs,
AmazonEC2,us-east-1,BoxUsage:m6a.large,Hrs,2
AmazonES,us-east-1,HeavyUsage:m4.xlarge.elasticsearch,Hrs,
AmazonES,us-west-2,USW2-HeavyUsage:m5.xlarge.elasticsearch,Hrs,
AmazonES,us-east-1,HeavyUsage:m5.xlarge.elasticsearch,Hrs,
AmazonES,us-west-2,USW2-HeavyUsage:i3.4xlarge.elasticsearch,Hrs,
AmazonEC2,us-west-2,USW2-BoxUsage:m6a.xlarge,Hrs,4
AmazonES,us-west-2,USW2-HeavyUsage:i3.16xlarge.elasticsearch,Hrs,
AmazonES,ap-southeast-2,APS2-HeavyUsage:r5.2xlarge.search,Hrs,
AmazonES,us-east-1,HeavyUsage:i3.2xlarge.elasticsearch,Hrs,
AmazonES,us-west-2,USW2-HeavyUsage:r5.2xlarge.search,Hrs,
AmazonES,eu-central-1,EUC1-HeavyUsage:m5.2xlarge.elasticsearch,Hrs,
AmazonEC2,us-east-1,BoxUsage:m6a.2xlarge,Hrs,8
AmazonES,us-west-2,USW2-HeavyUsage:i3.8xlarge.search,Hrs,
AmazonEC2,us-east-1,BoxUsage:m6a.4xlarge,Hrs,16
AmazonES,ap-southeast-2,APS2-HeavyUsage:c5.9xlarge.elasticsearch,Hrs,
AmazonEC2,us-west-2,USW2-BoxUsage:c6i.2xlarge,Hrs,8
AmazonES,ap-southeast-1,APS1-HeavyUsage:c5.xlarge.elasticsearch,Hrs,
AmazonES,ap-southeast-2,APS2-HeavyUsage:c5.2xlarge.elasticsearch,Hrs,
AmazonES,eu-west-1,EU-HeavyUsage:r5.4xlarge.search,Hrs,
AmazonEC2,us-east-1,BoxUsage:c6i.4xlarge,Hrs,16
AmazonES,us-east-1,HeavyUsage:r6g.4xlarge.elasticsearch,Hrs,
AmazonES,us-east-1,HeavyUsage:r5.4xlarge.elasticsearch,Hrs,
AmazonEC2,ap-southeast-2,APS2-BoxUsage:c6i.large,Hrs,2
AmazonES,ap-southeast-1,APS1-HeavyUsage:c5.xlarge.search,Hrs,
AmazonES,us-east-1,HeavyUsage:c6g.large.elasticsearch,Hrs,
AmazonES,ap-southeast-1,APS1-HeavyUsage:i3.xlarge.elasticsearch,Hrs,
AmazonES,eu-west-1,EU-HeavyUsage:c5.xlarge.search,Hrs,
AmazonES,ap-southeast-2,APS2-HeavyUsage:c5.xlarge.elasticsearch,Hrs,
AmazonES,ap-southeast-1,APS1-HeavyUsage:r5.2xlarge.search,Hrs,
AmazonES,ap-southeast-2,APS2-HeavyUsage:t3.medium.elasticsearch,Hrs,
AmazonES,us-west-2,USW2-HeavyUsage:m5.2xlarge.elasticsearch,Hrs,
AmazonES,us-east-1,HeavyUsage:i3.xlarge.elasticsearch,Hrs,
AmazonES,eu-west-1,EU-HeavyUsage:i3.xlarge.elasticsearch,Hrs,
AmazonES,us-west-2,USW2-HeavyUsage:r5.4xlarge.search,Hrs,
AmazonES,us-west-2,USW2-HeavyUsage:r5.xlarge.search,Hrs,
AmazonES,us-west-2,USW2-HeavyUsage:t3.medium.elasticsearch,Hrs,
AmazonES,us-east-1,HeavyUsage:m4.large.elasticsearch,Hrs,
AmazonES,us-east-1,HeavyUsage:i3.8xlarge.elasticsearch,Hrs,
AmazonES,us-east-1,HeavyUsage:m6g.large.elasticsearch,Hrs,
AmazonES,eu-west-1,EU-HeavyUsage:m5.xlarge.elasticsearch,Hrs,
AmazonES,ap-southeast-2,APS2-HeavyUsage:m5.large.elasticsearch,Hrs,

### To Reproduce

Use the list above and run:

```
cd ./cloud-carbon-footprint/packages/cli
yarn run create-lookup-table --awsInput input.csv
````

© 2021 Thoughtworks, Inc.

**Comment by ccasher** [comment]
Thanks for submitting this issue! We will add it to our project board to work on.

**Comment by ccasher** [comment]
Hi Mike, this should be updated and fixed now with our latest release!
