### ISSUE TITLE
Error messages should show in client side logs

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#651]
**Context**
We've gotten feedback that currently, error messages do not show up in the logs. We would like to include them for easier debugging.

**A/C's**
- [ ] When a 500 error occurs, I can see the error code and message in the client side logs
- [ ] When a 400 error occurs, I can see the error code and message in the client side logs
- [ ] When an error occurs, I can see the error code and message in the client side logs

**Comment by akhil-ghatiki** [comment]
I can sign up for this issue

**Comment by akhil-ghatiki** [comment]
are there any specific routes or files that I need to look up for ? or this has to be implemented for the whole client level. I am able to see the error logs for 500. Am I missing anything ? 
@ericksod @4upz 

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/3032101/194927820-41db1606-f6de-4f46-b8b0-c372a6989859.png">

**Comment by 4upz** [comment]
Hi @akhil-ghatiki , thanks for volunteering to take this on! The idea of this ticket is to include a better description of the error inside of the logs. So this involved including the error message with details of the error in addition to the status code. Ex: `Error: Status Code 500 - Incorrect startDate provided for Footprint Request`

Also, if you'd like, it would also be awesome to explore replacing the client's `Something has gone wrong, please try again later` with those details as well. However, the logs are the primary focus.

Let me know if that doesn't make sense or if you have any other questions! I'll go ahead and assign you and move this to in progress.

**Comment by akhil-ghatiki** [comment]
@4upz I created above PR for a faster feedback. If the changes look good, I will go ahead and do them for the rest of the client code.

**Comment by akhil-ghatiki** [comment]
@ericksod @4upz any updates on this ?

**Comment by akhil-ghatiki** [comment]
@4upz @ericksod  I have raised a new PR for this. Also included the implementation to show the error message in error page UI. Can you please take a look ?
