### ISSUE TITLE
Is there any Slack channel or Google group for CCF?

### ISSUE THREAD

**Issue by zhangtbj** [cloud-carbon-footprint/cloud-carbon-footprint#655]
Hi all,

I don't know where should I ask this question. So I open an issue with this question.

Is there any Slack channel or Google group for cloud carbon footprint related discussion?

Thanks a lot!

**Comment by 4upz-tw** [comment]
Hi @zhangtbj 

Thanks for reaching out! We actually do have a Google Group for CCF! You can join us here: https://groups.google.com/g/cloud-carbon-footprint

We often provide support/troubleshooting, answers to questions, and even take feedback about the app within that group. So feel free to reach out to us about anything there!

**Comment by zhangtbj** [comment]
Thank you!
