### ISSUE TITLE
Documentation for Compute Optimizer

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#702]
**A/C's**

- [x] Given I am on the `Get Recommendations` page on the microsite, I see a section under `AWS Recommendations` for `Compute Optimizer Recommendations`
- [x] Given I am viewing the `Compute Optimizer Recommendation` section, I see a description of the architecture and an explanation on why it was chosen
- [x] Given I am viewing the `Compute Optimizer Recommendation` section, I see instructions on how to set up my own compute optimizer recommendations
- [x] Given I am viewing the `Compute Optimizer Recommendation` section, I can see the cloud formation template
- [x] Given I am viewing the `Compute Optimizer Recommendation` section, I see an architecture diagram for Compute Optimizer
- [x] Notes on how to resolve error messages?

**Comment by dtoakley** [comment]
Compute Optimizer write up [here](https://docs.google.com/document/d/1VANR5cak4iySf09lDK2xITtltCVbOmgmbfqQ4iqYtJE/edit#). Once we align on the text, we can then implement it into the right section on the microsite.

**Comment by ericksod** [comment]
I think we're ready on this - the best place would likely be on the "Get Recommendations" page in the `AWS` section below the `Rightsizing Recommendations` section. https://www.cloudcarbonfootprint.org/docs/get-recommendations#rightsizing-recommendations

**Comment by dtoakley** [comment]
Deployed, see here: https://www.cloudcarbonfootprint.org/docs/get-recommendations/?bustcache
