### ISSUE TITLE
Unable to run with mock data after Create App

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#703]
**Describe the issue**
Run `yarn start-with-mock-data`

It seems to lauch ok,  I get a couple of Deprecation warnings (onAfterSetupMiddleware option is deprecated).
It then gets to "starting the development server..." and seems top hang. I can't access it from a webpage  and get ERR_CONNECTION_REFUSED.

**A/C's**
- [ ] Try to reproduce issue `run_with_mock_data`
- [ ] Consider if templates are not up to date

**Expected Behavior**
- [ ] I should be able to install with create-app and run `run_with_mock_data` and see an app spun up with sample data

**Comment by dtoakley** [comment]
We should test again after a release, but this [commit](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/commit/aed91d0ec33a78bb64f1a93f93cdb2c578fc5e8a) should fix the compilation errors.
