### ISSUE TITLE
Update documentation to indicate no IAM user role needed to run the app

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#705]
**Context:**
As per a discussion group question, we noticed it was unclear that iAm permissions were not required to start up the app. 
[Discussion group thread](https://groups.google.com/g/cloud-carbon-footprint/c/Ft-VvHDhIMI/m/xKTf1iiPAgAJ)
"So actually to run the app, you do not need to create a new IAM User so we should actually update that documentation."

**A/C's:**
- [ ] Update wording that may be misleading around when it is necessary to create a new IAM User  [here](https://www.cloudcarbonfootprint.org/docs/aws))
"You will need an [IAM](https://aws.amazon.com/premiumsupport/knowledge-center/create-access-key/) user that can create access-keys and modify your billing settings." should not be there.

**Comment by ashutoshkrris** [comment]
Hi @ericksod 
I'd like to work on this issue

**Comment by ashutoshkrris** [comment]
Hi @ericksod @4upz 
I want to work on this issue

**Comment by 4upz** [comment]
@ashutoshkrris thanks for volunteering! I'll assign you to this issue. It should be a straightforward documentation change, but feel free to let me know if you have any questions or need any support.
