### ISSUE TITLE
Remove double counting of memory GCP

### ISSUE THREAD

**Issue by dtoakley** [cloud-carbon-footprint/cloud-carbon-footprint#737]

**Comment by dtoakley** [comment]
Methodology write up for how we could handle this: https://docs.google.com/document/d/14LuFV74Ai6mkRXJJ_UMhT8lQ7MkK7fJqFR_NSZO05n8/edit

**Comment by dtoakley** [comment]
@davidmytton would be great for you to review this when/if you have a moment. Assuming this is a valid approach, we will likely want to implement these changes in the coefficients repo.

**Comment by davidmytton** [comment]
@dtoakley Looks good to me. If you want to assign to me I can update the coefficients repo.

**Comment by dtoakley** [comment]
Sorry for the delay @davidmytton -- I wanted to run the calculations for all the rows in the SPECPower database before we implement this, in case there were any weird results. This spreadsheet might be missing some of the more recents rows in the SPECPower database, but I have done this [here](https://docs.google.com/spreadsheets/d/1O7Ug_eUZvbZA4dTaA-8DNhJhoZikKD2IdD8OeNQipe4/edit#gid=1041929699). See column T in all the tabs. 

Looking at this, it seems fairly reasonable - except for the last row in the Cascade Lake tabs - it is a negative number. It doesn't overly affect the average for that micro architecture, but In cases like this, we should probably not factor in the memory reduction. What do you think?

I'm thinking we should implement this in the coefficients repo, but return both values for GCP: the existing coefficients per microarchitecture, and the coefficients with memory removed. It will make it easier for us to compare the two, and make a decision about what to default to in CCF. Would that be something you can could @davidmytton? Assigning this to you based on your last comment :)

**Comment by davidmytton** [comment]
I've implemented this, but there is a discrepancy in the figures compared to what you @dtoakley calculated

In the original methodology writeup at https://docs.google.com/document/d/14LuFV74Ai6mkRXJJ_UMhT8lQ7MkK7fJqFR_NSZO05n8/edit the calculation is

`Adjusted = avg. watts @ 100% - (Total memory * memory coefficient)`

I implemented this first in https://github.com/davidmytton/cloud-carbon-coefficients/commit/2dc2373884f025d3b974689b69d8d65d57d71ef8#diff-c3dec88cb2a130b8414da55dec155c11db5de618d9688d2da7bf350c8ffd9f9d but then noticed in your sheet at https://docs.google.com/spreadsheets/d/1O7Ug_eUZvbZA4dTaA-8DNhJhoZikKD2IdD8OeNQipe4/edit that you use

`Adjusted = (avg. watts @ 100% - (Total memory * memory coefficient) / Total Threads)`

With that change at https://github.com/davidmytton/cloud-carbon-coefficients/commit/50082b15e3207041ee48653e699fb88de2c1f683#diff-c3dec88cb2a130b8414da55dec155c11db5de618d9688d2da7bf350c8ffd9f9d compared to the original there is almost no difference.

The calculations in the coefficients repo already divides avg. watts @ 100% by Total Threads so I'm not sure if it's needed again. Or it needs to be:

`Adjusted = avg. watts @ 100% - ((Total memory * memory coefficient) / Total Threads)`

Any suggestions?

**Comment by 4upz-tw** [comment]
Hi @davidmytton, thanks for your help on this! I think the mixup in the addition of dividing the total threads is that we may have been assuming it was necessary to do it again to address potential differences in the frequency of the CPUs in the SpecPower database in comparison to those actually used in GCP. After looking at the differences between your calculations, I think it's better if we stick to the calculation in the original methodology writeup: ```Adjusted = avg. watts @ 100% - (Total memory * memory coefficient) ```

Feel free to let me know when the PR with that original calculation is ready for review, and I'd be happy to take a look at it and merge it in! Thanks again for your help on this! I'll try to dive deeper into Dan's calculations in the spreadsheet to make sure they properly reflect the correct formula.

**Comment by davidmytton** [comment]
Pull request for these changes: https://github.com/cloud-carbon-footprint/cloud-carbon-coefficients/pull/24

**Comment by 4upz** [comment]
Thanks, @davidmytton! We'll make sure to look over it
