### ISSUE TITLE
Map for dark theme

### ISSUE THREAD

**Issue by ilchenkoArtem** [cloud-carbon-footprint/cloud-carbon-footprint#743]
## Feature Suggestion
**Is your feature request related to a problem? Please describe.**
Unread map with dark theme

**Describe the solution you'd like**
Add image for dark theme

## Possible Implementation
Now I created map only for AWS 
[Check](https://dropmefiles.com.ua/ru/yWeP56H)

**Comment by ericksod** [comment]
Hi @tema1411. Thanks for reaching out!
As of now, we are not supporting dark theme, but if you'd like to contribute to that, feel free to make a PR!
