### ISSUE TITLE
Tables in methodology docs should fit text

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#744]
**Context:**
When reading through the methodology docs, there are a few tables that have large amounts of text. For these tables, it would be ideal to not have side scrolling.
The primary example is on https://www.cloudcarbonfootprint.org/docs/configurations-glossary

**A/C's:**
- [ ] When I view the tables on the config glossary on the microsite,  I can view all the text in each box without having to scroll sideways through the table

**Tasks:**
- [ ] Explore the `microsite` folder and find ways to incorporate better text wrapping for the tables used in `microsite/docs/ConfigurationsGlossary.md`

**Comment by ashutoshkrris** [comment]
Hi @ericksod and @4upz 
If we want to remove the horizontal scrollbar, the long variable names have to be split. Please find attached the screenshots of the table for more reference.
![Screenshot 2022-10-04 at 4 36 51 PM](https://user-images.githubusercontent.com/47353498/193804116-4c4df352-0eba-426e-bfbd-29705ac34208.png)
![Screenshot 2022-10-04 at 4 37 03 PM](https://user-images.githubusercontent.com/47353498/193804125-f6ca8fcb-0b98-4027-8ccf-312d9d4e4e68.png)

Let me know if this looks good to you.

**Comment by ashutoshkrris** [comment]
@4upz Are the tables in the above screenshot fine?

**Comment by 4upz** [comment]
Hi @ashutoshkrris , thanks for hopping on this! It would be preferable if there was a way to do some css-related or natural text wrapping. So rather than splitting the variable names, they just start on the line that fits. However if that isn't possible to do because of the markdown formatting, then splitting them is totally fine 🙂

**Comment by ashutoshkrris** [comment]
Sure, @4upz, got it!
Here's how the tables would look in three different screen sizes:
![Screenshot 2022-10-05 at 9 33 49 AM](https://user-images.githubusercontent.com/47353498/193979123-b98e1190-285c-4103-9adb-09b1f784f7d8.png)
![Screenshot 2022-10-05 at 9 34 31 AM](https://user-images.githubusercontent.com/47353498/193979130-e9e68cfe-c9ad-4631-89f9-d644de62ccaf.png)
![Screenshot 2022-10-05 at 9 35 01 AM](https://user-images.githubusercontent.com/47353498/193979135-01bacd2c-6e99-4f4b-828e-2afde5688074.png)

Let me know if this is fine.

**Comment by 4upz** [comment]
Hi @ashutoshkrris these are great! Thanks!
