### ISSUE TITLE
Update mock data to have more current dates

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#745]
**Context:**
If you visit our [public demo](demo.cloudcarbonfootprint.org), you can view an example of our dashboard with generated mock data that allows you to explore CCF's features. We currently have mock data in our `packages/client/stub-server` folder that is used to seed the demo app and mock the api routes. 

To improve this experience, we should use more current dates for the mock data.

**A/C's:**
- [ ] When I go to demo.cloudcarbonfootprint.org, I see data from Jan 2021 to Sept 2022

**Tasks:**
- [ ] Update the dates of the footprint data in the `mockData.json` package to have more recent dates.

**Out of Scope**
- Changing or modifying the estimations, names, or other information of the footprint data as that is covered in https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/532

**✨Bonus✨**
It would be great to have the dates generated upon deployment of the app so that they are always up to date. This would be getting a jump start on this issue: https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/749
*Hint:* Our application is deployed using Github Actions. You can view the `.github/workflows/demo-app.yml` for an idea on how to go about this.

**Comment by ashutoshkrris** [comment]
Hi @ericksod and @4upz 
I can work on the issue.
As a part of this issue, #749 will also get resolved.

**Comment by 4upz** [comment]
Resolved as part of #749's pull request
