### ISSUE TITLE
Instructions on client docker file

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#746]
**Context:**
As per [this discussion group thread](https://groups.google.com/g/cloud-carbon-footprint/c/VjdFI-IV7mw) we should mention the client docker file in the documentation, and how to use it.

You can view the current documentation on Docker via our [microsite](https://www.cloudcarbonfootprint.org/docs/run-with-docker), and that it only include instructions for running the API with Docker. It would be good to have a section on how to separately run the client as a container using its docker file as well.

**A/C's:**
- [x] When I go to the `Run with Docker` page on the microsite, I see a mention of the client docker file and the options I have to use it.

**Tasks**
- [x] Review and update `microsite/docs/RunWithDocker.md` with necessary instructions for how to individually run the `packages/client/Dockerfile`

**Comment by saranya2293** [comment]
Hi @ericksod @4upz , 
I would like to contribute to this task. Please assign this task to me.

**Comment by 4upz** [comment]
Hi @saranya2293 , thanks for taking a look at this issue! We'll review your PR shortly
