### ISSUE TITLE
Option for specifying domain name

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#748]
**Context:**
As per [this discussion group thread](https://groups.google.com/g/cloud-carbon-footprint/c/VjdFI-IV7mw) it would be helpful to allow inputting an option to allow a different domain name for the CORS policy (as an environment variable for example) 

(Consider if related to setting base url for api and client)

**A/C's:**
- [ ] Given I am setting up CCF, I can specify a different domain name
- [ ] Given I have specified a custom domain name and have run the app, then I can navigate to that domain and see my ccf instance

**Comment by camtittle** [comment]
Hey @ericksod I'd be happy to pick up this issue :) My understanding is that we need an environment variable in the API package such as `CLIENT_DOMAIN` which will be used to set CORS headers on the API responses - is this right?

**Comment by 4upz** [comment]
Hi @camtittle , thanks for being willing to work on this! You are correct, this will most likely involve an API-side env variable where it sets the `Access-Control-Allow-Origin` as part of the [request header](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#access-control-allow-origin). I would recommend looking into seeing how to set this as a default header for express whenever this env variable is present when the api kicks off. Let us know if you need any support or have other questions! I'll go ahead and assign you this issue 🎉

**Comment by camtittle** [comment]
@4upz PR opened for this issue :) https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/991
