### ISSUE TITLE
Dynamically update mock data dates when deploy to demo app

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#749]
## Context
Currently, the dates for our demo app on [https://demo.cloudcarbonfootprint.org/](https://demo.cloudcarbonfootprint.org/) are outdated. As part of issue https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/745 , we have indicated a manual task of updating these dates. It would be helpful to have a way to dynamically update the mock dates within the same 15-month range of the current dates each time the app is deployed.

**Acceptance Criteria**
- [ ] Given I deploy the app, the demo app is updated and the dates displayed are current

**Tech Tasks**
- Create a script that populates footprint dates of the `packages/client/stub-server/mockData.json` file using the current date as the start date.
- Our application is deployed using Github Actions. For info on how to possibly include this in the deployment pipeline, you can view the .github/workflows/demo-app.yml for an idea on how to go about this.

**Comment by ashutoshkrris** [comment]
Hi @ericksod and @4upz 
I would like to sign up for this issue.

**Comment by 4upz** [comment]
Hi @ashutoshkrris, thanks for taking a look at this! We'll review your PR shortly
