### ISSUE TITLE
Update AWS S3 Standard replication factor

### ISSUE THREAD

**Issue by github-benjamin-davy** [cloud-carbon-footprint/cloud-carbon-footprint#755]
Update the AWS S3 Standard replication factor

## Feature Update
Today both S3 Standard and S3 Standard IA use the same replication factor (3) however S3 standard offers a 99.99% availability when Standard IA offers a 99.9% availability.

### Context
Our hypothesis is that for S3 Standard data is replicated in 2 other AZs but it is also mirrored locally (in each AZ) to achieve better availability in case of failure (avoid having to reach another AZ).

We could consider that in that case the replication factor is 6 (3 AZs + mirror).

**Tech Tasks**
- [ ] Update `packages/aws/src/domain/AwsFootprintEstimationConstants.ts` to include a replication factor of *6* for  standard S3 services.
- [ ] Run and update the necessary tests to ensure that they reflect the new replication factor
- [ ] Run Changesets, bump any packages that have been updated/changed

**Comment by akhil-ghatiki** [comment]
I can sign up to solve this issue.

**Comment by 4upz** [comment]
Thanks @akhil-ghatiki ! We'll review your PR shortly
