### ISSUE TITLE
Card text on homepage not good for small mobile

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#757]
Contributor
![IMG_2C963B4F684F-1](https://user-images.githubusercontent.com/62668140/159973555-4f94224d-f0e1-4c16-8526-43104d743063.jpeg)
?

**Comment by nallammai-maruthappan** [comment]
can you assign this issue to me?

**Comment by ericksod** [comment]
Sorry for the delay @nallammai-maruthappan! Assigning you now

**Comment by 4upz** [comment]
This issue was fixed with PR https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/953 

@nallammai-maruthappan Apologies if you were still working on this. Please do take a look at our project board's "Ready to Do" list and see if there's something else you'd like to tackle!
