### ISSUE TITLE
[SPIKE] Additional Cache Work / Refactors

### ISSUE THREAD

**Issue by ccasher** [cloud-carbon-footprint/cloud-carbon-footprint#776]
Potential solution instead of JSON.stringify: https://github.com/dominictarr/JSONStream

Ideas - using lambda, distributing the data
how do we scale indefinitely?

Related issue:
https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/583

**Comment by drscarbrotw** [comment]
this looks like another fun one.
