### ISSUE TITLE
Upgrade Client to React 18

### ISSUE THREAD

**Issue by 4upz-tw** [cloud-carbon-footprint/cloud-carbon-footprint#813]
## Feature Suggestion
**Is your feature request related to a problem? Please describe.**
React 18 has [released](https://reactjs.org/blog/2022/03/29/react-v18.html) and it contains a plethora of enhancements that could be valuable to bring to our client, with the most notable being: concurrent rendering and automatic batching for state updates. These improvements could bring immediate performance enhancements to our client app by reducing unnecessary re-renders and allowing for other performance enhancements through the new hooks that are available.

**Scope**
Updating to React 18 is a surprisingly quick task , as you just have to run the `yarn up` command for `react` and `react-dom`, then change the `index.tsx` file to use the new rendering API. Any additional features are optional and can be implemented on an as-needed basis.

**Additional context**
Updating to React 18 does have a slight styling affect on the dashboard has Material UI has yet to release an update to make it fully compatible. We'll have to wait for them to do a new release to make it compatible with React 18's changes. Their roadmap and milestone tracker can be viewed here: https://github.com/mui/material-ui/milestone/45

## Before Implementation

- [ ] Use React Devtools' Profiler to measure performance improvements of state batching. A good example would be to record the render time after selecting/deselecting one of the filters.
- [ ] Take screenshot comparisons of React 18 vs React 17 improvements and add to this issue
- [ ] Confirm that MUI is compatible and upgrade to new `mui-core` package with the React 18 changes

## Possible Implementation

- [ ] Run `yarn up react react-dom` to update to the latest version of React
- [ ] In the client package, make the following change to the root `index.tsx` file:
``` diff

- import React from 'react'
- import ReactDOM from 'react-dom'
+ import { createRoot } from 'react-dom/client'
import { Root } from './Root'

- ReactDOM.render(<Root />, document.getElementById('root'))

+ const container = document.getElementById('root')
+ const root = createRoot(container)
+ root.render(<Root />)

```

**Comment by 4upz-tw** [comment]
Dependabot PR for version bump: https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/800

**Comment by Samridhi-98** [comment]
Hey @4upz-tw , I would like to work on it.

**Comment by 4upz** [comment]
Hi @Samridhi-98 sounds great! I'll go ahead and assign you. Feel free to let us know if you need support or have any questions. One thing to look out for when doing the upgrade, is to make sure that all of the Material UI components that are used behave correctly. This may also include upgrading MUI to the latest version to ensure compatibility

**Comment by Samridhi-98** [comment]
> Hi @Samridhi-98 sounds great! I'll go ahead and assign you. Feel free to let us know if you need support or have any questions. One thing to look out for when doing the upgrade, is to make sure that all of the Material UI components that are used behave correctly. This may also include upgrading MUI to the latest version to ensure compatibility

Sure Arik 😊

**Comment by 4upz** [comment]
Hey @Samridhi-98 , just doing a friendly check-in to see how things are going! Are you still working on this issue and do you need any support?

**Comment by Samridhi-98** [comment]
> Hey @Samridhi-98 , just doing a friendly check-in to see how things are going! Are you still working on this issue and do you need any support?

Hey @4upz , Yeah working on it soon I'll open draft PR.

**Comment by Samridhi-98** [comment]
Hey @4upz, I am not able to commit my changes.

**Scrrenshot for reference:**

<img width="812" alt="Screenshot 2022-12-21 at 9 08 31 PM" src="https://user-images.githubusercontent.com/54466041/208944193-1277b6fb-7f43-4c9b-90d5-7ba411705147.png">

**Comment by 4upz** [comment]
Hey @Samridhi-98 sorry about that! You're probably seeing this error either because you're a TWer and it's expecting you to have [Talisman](https://github.com/thoughtworks/talisman), or [you've installed Talisman](https://www.cloudcarbonfootprint.org/docs/getting-started#optional-prerequisites) but haven't saved the path to your `.zshrc` file.

If you're not interested in using Talisman, you should be able to disable it by commenting/removing line 12 in your `.husky/pre-commit` file:
```
 ./scripts/copyright_check.sh && ./scripts/branch_warning.sh && $TALISMAN_HOME/talisman_hook_script pre-commit || exit 1
```

Let me know if that works!

**Comment by Samridhi-98** [comment]
> Hey @Samridhi-98 sorry about that! You're probably seeing this error either because you're a TWer and it's expecting you to have [Talisman](https://github.com/thoughtworks/talisman), or [you've installed Talisman](https://www.cloudcarbonfootprint.org/docs/getting-started#optional-prerequisites) but haven't saved the path to your `.zshrc` file.
> 
> If you're not interested in using Talisman, you should be able to disable it by commenting/removing line 12 in your `.husky/pre-commit` file:
> 
> ```
>  ./scripts/copyright_check.sh && ./scripts/branch_warning.sh && $TALISMAN_HOME/talisman_hook_script pre-commit || exit 1
> ```
> 
> Let me know if that works!

Ohh, got it.
I forgot to run `yarn test`, few tests are failing need to fix those.

**Comment by 4upz** [comment]
> > Hey @Samridhi-98 sorry about that! You're probably seeing this error either because you're a TWer and it's expecting you to have [Talisman](https://github.com/thoughtworks/talisman), or [you've installed Talisman](https://www.cloudcarbonfootprint.org/docs/getting-started#optional-prerequisites) but haven't saved the path to your `.zshrc` file.
> > If you're not interested in using Talisman, you should be able to disable it by commenting/removing line 12 in your `.husky/pre-commit` file:
> > ```
> >  ./scripts/copyright_check.sh && ./scripts/branch_warning.sh && $TALISMAN_HOME/talisman_hook_script pre-commit || exit 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Let me know if that works!
> 
> Ohh, got it. I forgot to run `yarn test`, few tests are failing need to fix those.

Sounds good! Let me know if you need anything else

**Comment by Samridhi-98** [comment]
> > > Hey @Samridhi-98 sorry about that! You're probably seeing this error either because you're a TWer and it's expecting you to have [Talisman](https://github.com/thoughtworks/talisman), or [you've installed Talisman](https://www.cloudcarbonfootprint.org/docs/getting-started#optional-prerequisites) but haven't saved the path to your `.zshrc` file.
> > > If you're not interested in using Talisman, you should be able to disable it by commenting/removing line 12 in your `.husky/pre-commit` file:
> > > ```
> > >  ./scripts/copyright_check.sh && ./scripts/branch_warning.sh && $TALISMAN_HOME/talisman_hook_script pre-commit || exit 1
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Let me know if that works!
> > 
> > 
> > Ohh, got it. I forgot to run `yarn test`, few tests are failing need to fix those.
> 
> Sounds good! Let me know if you need anything else

Yeah, I am still facing issue with pre-commit, though I have talisman configured in my system  and also I tried commenting/removing line 12 in `.husky/precommit` still unable to commit. 


![image](https://user-images.githubusercontent.com/54466041/209075989-56a4b856-1b74-473b-90ff-65d45f2e50a8.png)

**Comment by 4upz** [comment]
@Samridhi-98 Ahhh those don't seem to be Talisman. Those are the integration tests that are failing and seem to be halting your pre-commit. It may be due to some of the client changes you've had to make. For now, I think it's fine to ignore them and we can make a separate issue to fix them. You can add the `--no-verify` flag to your commit command so that it skips the pre-commit checks. Just make sure that all of the other tests, specifically the unit tests are passing before you do.

**Comment by Samridhi-98** [comment]
> @Samridhi-98 Ahhh those don't seem to be Talisman. Those are the integration tests that are failing and seem to be halting your pre-commit. It may be due to some of the client changes you've had to make. For now, I think it's fine to ignore them and we can make a separate issue to fix them. You can add the `--no-verify` flag to your commit command so that it skips the pre-commit checks. Just make sure that all of the other tests, specifically the unit tests are passing before you do.

Also, getting error while switching the routes, needs to refresh the page. I found [this](https://stackoverflow.com/questions/71975875/react-dependency-conflict-version-18-0-with-material-ui), mui is still not fully compatible with v18.

![image](https://user-images.githubusercontent.com/54466041/209291745-29070636-47b1-4bf8-ae76-8758046f1f61.png)

**Comment by Samridhi-98** [comment]
> > @Samridhi-98 Ahhh those don't seem to be Talisman. Those are the integration tests that are failing and seem to be halting your pre-commit. It may be due to some of the client changes you've had to make. For now, I think it's fine to ignore them and we can make a separate issue to fix them. You can add the `--no-verify` flag to your commit command so that it skips the pre-commit checks. Just make sure that all of the other tests, specifically the unit tests are passing before you do.
> 
> Also, getting error while switching the routes, needs to refresh the page.  I found [this](https://stackoverflow.com/questions/71975875/react-dependency-conflict-version-18-0-with-material-ui).
> 
> ![image](https://user-images.githubusercontent.com/54466041/209291745-29070636-47b1-4bf8-ae76-8758046f1f61.png)

**Comment by 4upz** [comment]
@Samridhi-98 Seems to be related to MUI styles. Did you happen to update any of the Material UI packages in the process? You may need to update to their latest `mui-core` version if you haven't and make some tweaks there. As mentioned in the issue description, they've had to apply some updates to make their packages compatible with React 18.

**Comment by Samridhi-98** [comment]
> 

I didn't update any material ui packages yet, I'll try that.
