### ISSUE TITLE
Questions: Methodology for storage

### ISSUE THREAD

**Issue by ghost** [cloud-carbon-footprint/cloud-carbon-footprint#817]
Hi, I am working on a tool to calculate the CO2 emissions of **storage** on the Cloud, how would I calculate this and what parameters would be appropriate?

### Thing I don't understand.
Cloud Providers like AWS and GCP keep backups in order to never loose user data, in the Energy Coefficients, it says the watt hours for HDD is 0.65 WH. Does that account for storing backups or literally storing the files in object storage? Also, regarding networking, how do we know how many times the Data moves between geographical locations? Please be more detailed with what the numbers mean. Thank you in advance.

**Comment by 4upz-tw** [comment]
Hi @ziadomalik, thanks for your question! 

Have you taken a look at our deep dive into the storage methodology? You can find details on how we go about calculating storage usage [here](https://www.cloudcarbonfootprint.org/docs/methodology/#storage).

We also do account for storage backups across cloud providers. We refer to these number of backups created as replication factors and it represents the amount of replicated instances that is created by default for that service across regions. Some of these can be cross-located or co-located depending on the approach. The energy coefficient for HDD and SDD devices is for storing on a single instance, and we multiply the emissions for that single instance by the matching replication factor to get the total emissions across each backups for that service.  Our [section on replication factors](https://www.cloudcarbonfootprint.org/docs/methodology/#replication-factors) in the storage methodology goes over this in more detail and includes a linked spreadsheet of what factors we use for each supported service. 

As for networking, we currently aren't exposed to how many times data moves between geographical locations. Instead, we're utilize how much data (in gigabytes) has been transferred in egress. This information is included as part of the usage that we pull from the billing data of each cloud provider. We then multiply this quantity by our chosen coefficient [0.001 kWh/Gb](https://www.cloudcarbonfootprint.org/docs/methodology/#chosen-coefficient) and the [PUE (Power Usage Effectiveness)](https://www.cloudcarbonfootprint.org/docs/methodology/#chosen-coefficient) of that cloud provider. There's a lot of ongoing studies on the best way to go about this, so much like the rest of our methodology we're open to feedback or contributions to improve it.

Hopefully this helps! I'm going to close this issue for now, but feel free to reply with any additional questions and I'm happy to reopen it and address them.

**Comment by ghost** [comment]
Thank you bro @4upz-tw U a real one.
