### ISSUE TITLE
"Costing" AWS export CSV file

### ISSUE THREAD

**Issue by ghost** [cloud-carbon-footprint/cloud-carbon-footprint#827]
## Feature Suggestion
We use a lot AWS tags, so we built reporting using quite the same data as the one used by CCF. But actually we can't consolidate our cloud impact on tags. (Useful for responsibility sharing).

**Describe the solution you'd like**
Using CLI, I would love to be able to compute for each line of the AWS CSV file the GHG emissions associated, in order to put it into our analysis tool. 

**Describe alternatives you've considered**
Using https://github.com/Boavizta/boaviztapi to do it

Thank you for answers and/or pointers !

**Comment by ericksod** [comment]
Hi @jeromemoly. Thanks for your suggestion. From your description, we're not crystal clear on exactly what you are hoping for in a solution, but perhaps taking a look at our documentation on the [lookup table approach](https://www.cloudcarbonfootprint.org/docs/creating-a-lookup-table) could be interesting to you.
If that is not in the correct direction for your solution, feel free to elaborate a bit more and we can provide thoughts or feedback.

**Comment by ghost** [comment]
Exactly what I looked for, thank you !
