### ISSUE TITLE
Ability to filter response to API /footprint by subscription id (s)

### ISSUE THREAD

**Issue by nilshedstrom** [cloud-carbon-footprint/cloud-carbon-footprint#828]
When making a call /footprint in the API I would like to be able to send one or more Azure subscription ids as a parameter.
The response from /footprint should only contain results for the subscriptions specified in the input parameter
## Feature Suggestion
I work in a company that has a lot of Azure resources. I have an app registration that has access to 268 subscriptions.
My goal is to create a widget for Azure Devops that will display a graph of cloud carbon footprint.
The widget would call the Cloud Carbon Footprint API to get the data.
The problem with the current API is that it is really hard to start it with 268 subscriptions (there is a limit in Azure on how many requests you can make to get data) and after the timeout the request limit is hit again. The other problem is that it would take a long time to return the data.

**Describe the solution you'd like**
I would like a parameter to the /footprint-endpoint that contains the subscription ids that we want data from.
I could then specify the subscriptions when calling the API from the widget. After that the widget could display the cloud carbon footprint from the subscriptions that are relevant for a team. 
As a result a team that wants to know the cloud carbon footprint for their subscriptions could add the widget to a dashboard in their Azure Devops project (and specifying the subscription ids that are relevant for that team).

**Describe alternatives you've considered**
It would be possible to create an app registration that only has access to a limited number of subscriptions and then create an API instance that uses that app registration and then call that API instance from the widget.
That solution would not be optiomal for me since we have many teams and if all teams have to create Azure resources to be able to see the Cloud Carbon Footprint for their subscriptions that would take a lot of effort but also increase the Cloud Carbon Footprint that we would like to reduce.

**Additional context**

## Possible Implementation

- Add subscriptionIds to FootprintEstimatesRawRequest (could be comma separated)
- Add subscriptionIds to EstimationRequest
- Modify App.ts so that subscriptionIds are sent to AzureAccount.getDataFromConsumptionManagement
- Modify getDataFromConsumptionManagement so that we only call getDataForSubscription if the subscription is in subscriptionIds

I realize that this suggestion will only work for Azure resources.

**Comment by ericksod** [comment]
HI @nilshedstrom.
Thanks for the suggestions - we think this option to specify subscription (or account, project) is a good one. We would ideally have this option for each of the cloud providers supported by Cloud Carbon Footprint. We will create an issue for this and comment here with it. You're more than welcome to work on this if you have capacity.

Also worth noting - we are currently prioritizing improvements on the performance of Cloud Carbon Footprint by adding an option to use mongoDB instead of a cache file. Perhaps this could also work to solve your root issue of accessing the estimates.

**Comment by nilshedstrom** [comment]
Hi!
I will start working on this (Azure resources to start with). Is it ok if I name the parameter to the API subscriptionIds or do you have another name that could work for multiple providers in the future?

**Comment by 4upz** [comment]
Closing as this feature is now possible (via API and Mongo) in the newest release as detailed in https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/853
