### ISSUE TITLE
Queries taking too long to load

### ISSUE THREAD

**Issue by rafaelsilvaaa10** [cloud-carbon-footprint/cloud-carbon-footprint#830]
Hello, 

My environment:

Backend and FrontEnd running in Ec2 32Gib 8vCpu

running via yarn start

----

We started testing the tool.

At first we have 3 clouds connected (azure, aws and GCP) and the next step is to connect our Onpremisse environment.

Everything works so far, however my environment is very large, about 144 accounts.

Queries take a long time to load, sometimes it doesn't even load. It's a little confusing for me to improve performance.

I already tried to put the cache in the GCS, and it did not work, nor did it load anything.

now I'm retrying the local cache, and using the following envs :

packages/client/.env
REACT_APP_PREVIOUS_YEAR_OF_USAGE=true
REACT_APP_DATE_RANGE_VALUE=2
REACT_APP_DATE_RANGE_TYPE=months
REACT_APP_GROUP_BY=month

packages/api/.env
GROUP_QUERY_RESULTS_BY=week

Could someone share an edited .env with the best performance related values.

We are willing to chat with the development team.

Thanks alot.

**Comment by ericksod** [comment]
Hi @rafaelsilvaaa10,
Thanks for your message.
We are currently in the process of refactoring the cache, and adding an option to use a mongoDB as a cache instead which should relieve some of the pain you are feeling. Please see the ticket here: [#837](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/837)
We are not, however at this time, refactoring the apis. Perhaps you can try out the [`seed-cache-file` command](https://www.cloudcarbonfootprint.org/docs/performance-considerations#seeding-cache-file) for the time being.
