### ISSUE TITLE
Update Cache file

### ISSUE THREAD

**Issue by rafaelsilvaaa10** [cloud-carbon-footprint/cloud-carbon-footprint#831]
Hello there,

I don't know if I'm understanding correctly.
Are carbon use estimates made only at application startup?

I noticed that the cache is not updated, it is only updated after deleting the estimates.....json file.

**Comment by ccasher** [comment]
Hi @rafaelsilvaaa10, so sorry for missing this issue. We have made quite a few updates since then. Please view our [documentation section](https://www.cloudcarbonfootprint.org/docs/data-persistence-and-caching) on this and please let us know if your issue persists and we will create a new issue.
