### ISSUE TITLE
Intermittent test hang when running e2e integration tests locally

### ISSUE THREAD

**Issue by c-mcraeolson** [cloud-carbon-footprint/cloud-carbon-footprint#832]
### Preflight Checklist

- [ x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  -  macOS 12.4
- **Browser:**
  - Chrome

### Expected Behavior

I expect the integration tests to run consistently, or have a clear error if something has changed to cause them to fail.

### Actual Behavior

Perhaps 1/3 of the time, the integration tests simply hang right after starting.

The hang, when it occurs, always happens at the same place - right after printing "Cloud Carbon Footprint"  - and (in a headed test) before the page actually loads (the testCafe "connected" icon is still in the center of the page.)

This appears to be an error state, not purely random chance - either it's happening every time, or it isn't happening at all. Sometimes simply closing and re-opening VSCode will fix it.

It seems to be some kind of connection issue with TestCafe, it may be a bug on their side or some small configuration issue with our site (I did some googling for similar errors and found their team responding to somewhat similar things but no smoking gun).

### To Reproduce

Unfortunately it's inconsistent. When it occurs for me it's on normal test runs, so just 
$ yarn headless 
or
$ yarn headed 
from packages/integration tests.

### Additional Information

On my system there is also a similar intermittent hang at the end of the Talisman flow, after it has run all test suites, including the integration tests. In the cases where this error does occur, it seems to trigger the error state described in this ticket.

I reported this it TestCafe's team here, so they may have suggestions.
https://stackoverflow.com/questions/72465806/intermittent-testcafe-hang-issue

© 2021 Thoughtworks, Inc.

**Comment by tinamthomas** [comment]
I believed this is due to an issue mentioned on https://github.com/jeffbski/wait-on/issues/116. Looking into it as part of trying to get the integration tests run on CI (https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/818)
