### ISSUE TITLE
Onpremisse on Client Fronted

### ISSUE THREAD

**Issue by rafaelsilvaaa10** [cloud-carbon-footprint/cloud-carbon-footprint#833]
Hello there, 

Is it possible to put my ompremisse environment data on the client frontend?

I saw that it is possible to do the calculation via the cli, but I didn't see any session referring to an ad in the frontend.

<img width="279" alt="image" src="https://user-images.githubusercontent.com/82902516/171489433-7a3a9d0f-f620-4523-8640-b091621aca20.png">

Thanks

**Comment by 4upz-tw** [comment]
Hi @rafaelsilvaaa10, as of right now we have yet to implement viewing on-premise estimations in the client dashboard. The CLI is currently the only wait to calculate on-premise data. However, we do have this in our backlog so make sure to keep an eye on our [Google Group](https://groups.google.com/g/cloud-carbon-footprint) or releases for updates!
