### ISSUE TITLE
[BACKSTAGE] Unable to see Backstage side bar through CCF Plugin

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#864]
Please see details in original bug ticket: https://github.com/cloud-carbon-footprint/ccf-backstage-plugin/issues/11#issue-1282033770

Remaining issue on https://github.com/cloud-carbon-footprint/ccf-backstage-plugin/issues/9 may also be resolved here.

**Comment by 4upz** [comment]
Resolved replicable issues by upgrading backstage and other dependencies to latest versions (1.7.0), and fixing outdated commands/scaffolding. Closed the two issues as the user will retest after migrating, which any further issues can be tracked in a new ticket
