### ISSUE TITLE
can't get more than a year of data

### ISSUE THREAD

**Issue by falcocoris** [cloud-carbon-footprint/cloud-carbon-footprint#873]
Hi

using the AWS conf here and not sure if it's a bug, a missing feature or a miss usage, but I can only get one year of data on the interface, while the data on my s3 bucket is 2 years.
Is there a way ?
I'd like to get the data from january 2021 to january 2022

**Comment by ericksod** [comment]
Hi @falcocoris, thanks for reaching out.
Did you by chance mean Jan 2020-Jan 2022 (this would be 2 years)?
We don't allow you to set a specific date range as a configuration, but you can do that via URL params.
Feel free to send any more details about what you are trying to do if you're comfortable.

**Comment by falcocoris** [comment]
I did mean january 2021 to january 2022, 1 year.
I manage to get the json by using curl with the url params, like so : 
`localhost:3000/api/footprint?start=2021-01-01&end=2021-12-31`
but is there a way to get the "cloud usage" graph work ? and all of the dashboard actually ?
I did try `localhost:3000/?start=2021-01-01&end=2021-12-31` but it doesn't work
Also tried selecting the date from the date picker, but somehow it picks today minus 1 year till the end of the interval.
For exemple today, it goes from july 29th till december 31th
I guess that's a bug.
I gotta be able to provide the json or more if you need to reproduce

**Comment by ericksod** [comment]
Hi @falcocoris, would you be able to provide us your config, especially date range type and date range value? 
https://www.cloudcarbonfootprint.org/docs/configurations-glossary/#client-package---all-variables-are-optional
For the dashboard to work properly, the range needs to be set as an env variable for the dashboard. Also worth noting, the value for minimal date age will mean that data showing up will be at least that old (this combats partial data and could cause inaccuracy when using the date picker)
