### ISSUE TITLE
Question : Why are AWS "In-Bytes" not weighted but "Out-Bytes" are ?

### ISSUE THREAD

**Issue by ghost** [cloud-carbon-footprint/cloud-carbon-footprint#885]
Hi there, 

I'm using successfully lookup tables in order to do some custom computations, and i noticed that all the "In-Bytes" are not found from my lookup tables (like `EUW3-USW2-AWS-In-Bytes` for example), but "Out-Bytes" are weighted (for example `AmazonEC2,eu-west-1,EU-LAX1-AWS-Out-Bytes,GB,,,0.001135,3.5865999999999996e-7` in my lookup CSV).

In my mind, "In-Bytes" traffic has the same impact than "Out-Bytes" traffic, but maybe there's another reason ?

Thank you !

**Comment by ericksod** [comment]
@jeromemoly thanks for reaching out! We aren't very familiar with "In-Bytes" - do you know if this is related to data between data centers? This is the only networking piece we are able to consider at the moment.
If so, you could add it to this list:
https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/3cd5b023d7f79b58043398aea298752c9b7ae6f2/packages/aws/src/lib/CostAndUsageTypes.ts#L102 - here you can see we do have out-bytes covered, so it could be an issue of just not yet supporting that usage type.

**Comment by ghost** [comment]
Ok ! I looked to AWS documentation, and according to according to https://docs.aws.amazon.com/AmazonS3/latest/userguide/aws-usage-report-understand.html it is incoming and outgoing traffic so I think it is safe to add it.

`
region1-region2-AWS-In-Bytes | GB | Hourly | The amount of data transferred to AWS Region1 from AWS Region2
region1-region2-AWS-Out-Bytes | GB | Hourly | The amount of data transferred from AWS Region1 to AWS Region2
`

I'm not familiar with the process of making a change in Github, but I'll giv it a try !

**Comment by ericksod** [comment]
@jeromemoly Great! Thanks for sharing that documentation, very helpful.
Feel free to give it a try and submit a PR. We can review when you think you have something and provide any feedback you might need. 
Here is the contributing doc if you need any help getting started https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md
Thanks!
