### ISSUE TITLE
Problem in setting up using AWS and AZURE 

### ISSUE THREAD

**Issue by Anushas42** [cloud-carbon-footprint/cloud-carbon-footprint#914]
1. AWS

-    Facing an Error of 500  while launching CCF app, as its taking only  the failed executions from ATHENA DB.

2. AZURE

- Data's are not getting populated in CCF dashboard after launching app successfully. 
![image](https://user-images.githubusercontent.com/113912279/191027534-91912dea-25b9-4815-946c-6a665efbad2c.png)

© 2021 Thoughtworks, Inc.

**Comment by ericksod** [comment]
Hi @Anushas42! Thanks for reaching out. Have you checked out our [mailing list](https://groups.google.com/g/cloud-carbon-footprint) yet? There have been similar discussions in that group, which may be helpful to get you started.
