### ISSUE TITLE
Which AWS IAM permissions are needed?

### ISSUE THREAD

**Issue by zackriso** [cloud-carbon-footprint/cloud-carbon-footprint#915]
There are 2 main requirements in terms of Cloud Carbon Footprint (CCF) for AWS: 
1) User 1:  The AWS resources which need to be deployed, such as: the CUR report, the CloudFormation Stack to get Athena/Glue working 
2) User 2:  needed to run the tool itself (yarn start) through an EC2 or local terminal  

When deploying CCF in any organization or production environment, we need to provide the 2 users specific permissions. We cannot (and in most places) wont have the luxury to assign both of them "admin" access: such is not a good idea from a security point of view. 

Can we have an idea which AWS IAM actions are needed for the two users above? 
Thank you

**Comment by zackriso** [comment]
Any updates on this please?

**Comment by 4upz** [comment]
Hi @zackriso apologies for the delayed response. I'd recommend referring to our [Cloud Formation Templates](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/cloudformation) as a guide for what exact permissions the CCF app's role needs along with what a user setting up and deploying it will need access to. Both the `ccf-app` and `ccf` templates should also point to permissions needed to run the app locally and in an EC2 instance, with our [Authentication Documentation](https://www.cloudcarbonfootprint.org/docs/aws#options-for-aws-authentication) pointing to how to authenticate using that created role when running the application.

Let us know if this helps. Alternatively, I'd recommend bringing this to our [Discussion Group](https://groups.google.com/g/cloud-carbon-footprint) where we have an active community that may be able to assist some more and share their setups.

**Comment by 4upz** [comment]
Hi @zackriso , going to close this since there's no work to be done on our end. But feel free to leave another message or to hop into our discussion board if you're still having issues with this.

**Comment by zackriso** [comment]
Hi, 
The cloudformation template in itself does not list or provide a list of IAM permissions needed. Also, it is not the only thing that is needed to deploy the entire tool. For example, CUR access is needed, as well as S3, and so on. Lastly, the tool itself (which will produce the graphs) also needs IAM permissions and access. 

All these permissions have to be listed and known, not everyone has an admin role in AWS :) 

For simplicity, imagine that we have to list and specify every single IAM permission needed to run the Cloud Carbon Footprint tool as a whole (CUR, S3, CloudFormation, the yarn tool itself, and so on). This is what I referred to in the first post.

**Comment by 4upz** [comment]
@zackriso Hi there! I understand what you mean now. The CF templates only provide permissions to create a role needed for the CCF app to get the data it needs, but not the permissions needed for setup/deployment from a user perspective. Unfortunately, we do not have a list of these exact permissions at the moment. An account admin usually either deploys these resources or has the knowledge to derive any necessary permissions from the actions needed for the tool (billing data access, S3 access, etc). 

We can look into improving our documentation to include these permissions, including tutorials on how to run CCF in different environments (i.e. EC2 instance). This will take some time on our end, unless someone is kind enough to contribute this information 😃. For the moment, we'd recommend bringing this to our [discussion board](https://groups.google.com/g/cloud-carbon-footprint) where hopefully someone else in the community that encountered similar use cases can provide you a faster answer.

**Comment by shuknk8s** [comment]
Hi , I have a follow up question on list AWS services that need to be setup and configured ahead of CCF deployment for example on AWS EC2 instance. The documentation does not refer to have AWS Glue setup as a prerequisite  unlike AWS Athena, S3 and AWS CUR but the cloud formation and terraform template in the Gihub repo clearly references AWS Glue. Is AWS Glue service is mandatory prerequisite for CCF deployment and operation?
