### ISSUE TITLE
Update unknown estimator and documentation to return no carbon/energy estimates if usageUnit/service do not exists in the dynamic coefficients

### ISSUE THREAD

**Issue by camcash17** [cloud-carbon-footprint/cloud-carbon-footprint#920]
Currently, if the unknown estimation does not have a similar estimate with the same usageUnit or serviceName in the dynamic coefficients mapping, it will grab the average total values of all estimates to calculate an energy estimation.

We want to update this logic to return 0 instead, as we do not want to estimate energy for services/usageUnits that have no previous estimations and may not have a carbon impact.

We need to update the documentation on the microsite to capture this as well.

**Comment by ghost** [comment]
[All units found in Athena grouped by items](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/files/9698789/46b3f994-590d-409f-9c43-a399f5b0c5dd.csv)

**Comment by 4upz** [comment]
Has this microsite been updated to reflect these changes? I don't think I saw anything in the tagged commit
