### ISSUE TITLE
Add new AWS region to CCF

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#929]
Middle East (UAE) Region
Availability Zones: 3
Launched 2022

**Comment by akhil-ghatiki** [comment]
How are these numbers calculated ? 
https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/ad113025e47ffb1a040e2792c08933dc6ff32269/packages/aws/src/domain/AwsFootprintEstimationConstants.ts#L180 

@ericksod @4upz

**Comment by 4upz** [comment]
Hi @akhil-ghatiki , thanks for being willing to help out with this! These constants come from publicly published emission factors for that country/region. For AWS, we usually use one of the following:
- https://www.carbonfootprint.com/docs/2022_03_emissions_factors_sources_for_2021_electricity_v11.pdf
- https://www.epa.gov/egrid/egrid-related-materials
- https://www.eea.europa.eu/data-and-maps/daviz/co2-emission-intensity-9/#tab-chart_2

For the Middle East region, it is most likely located in the EEA or EPA links, but feel free to take a look and let us know if you need anymore support!

**Comment by ericksod** [comment]
@akhil-ghatiki We believe the two missing are Jakarta and UAE

**Comment by akhil-ghatiki** [comment]
> @akhil-ghatiki We believe the two missing are Jakarta and UAE

I will add both

**Comment by 4upz** [comment]
Need to add emissions factors
