### ISSUE TITLE
Incorrect package name in README files

### ISSUE THREAD

**Issue by gbhasha** [cloud-carbon-footprint/cloud-carbon-footprint#954]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Incorrect package name in README file heading. Issue found in below files

- packages/aws/README.md
- packages/azure/README.md
- packages/common/README.md
- packages/gcp/README.md

### Expected Behavior

Package name mentioned in the title of the readme file should be correctly pointing to the respective package name.

example: 
The title in `packages/aws/README.md#1`  should be `# @cloud-carbon-footprint/aws`

### Actual Behavior

Package name mentioned in the title of the readme file was wrongly pointing to the 'core' package.

example: 
The title in `packages/aws/README.md#1`  was pointing to  `# @cloud-carbon-footprint/core`

### To Reproduce

check below files

- packages/aws/README.md
- packages/azure/README.md
- packages/common/README.md
- packages/gcp/README.md

-->

### Screenshots

<img width="826" alt="image" src="https://user-images.githubusercontent.com/501794/198508886-f9724725-c3b5-4f2d-9022-dc4376a39461.png">

© 2021 Thoughtworks, Inc.

**Comment by 4upz** [comment]
Fixed with PR https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/955

Thanks again for catching this! @gbhasha
