### ISSUE TITLE
Add technical API documentation

### ISSUE THREAD

**Issue by ghost** [cloud-carbon-footprint/cloud-carbon-footprint#963]
CCF doesn't have technical API documentation to allow developers to implement their interfaces. After spikes in #944, we can implement `tsoa` into CCF.

The current issue is that our current implementation of `api.ts` is function-based and TS does not allow decorators on these. So we need to refactor `api.ts` to expose classes and methods which then can be annotated with `tsoa` for proper documentation. 

References: 

https://tsoa-community.github.io/docs/getting-started.html

api-docs branch: https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/tree/api-docs

**Comment by melaniesarah** [comment]
Implementing using openapi and swagger for express/typescript
