### ISSUE TITLE
Add support for Azure Tags

### ISSUE THREAD

**Issue by 4upz** [cloud-carbon-footprint/cloud-carbon-footprint#964]
#### Overview
We currently have the ability to make tags visible for CCF API results as detailed in our [Tagging Documentation](https://www.cloudcarbonfootprint.org/docs/tagging). Currently, this solution is only supported in AWS and we'd like to bring this functionality for Azure estimates as well. The goal is to modify the consumption management API query for Azure and other relevant areas in the `Azure` package to include both `resourceGroups` and `tags` for every resource in the `tags` field of the resulting `EstimationResult`. 

To keep consistent with the AWS implementation, desired tags should be specified via environment variable in the `.env` file of the `API` or `CLI` package. The variable should be named `AWS_RESOURCE_TAG_NAMES` and take an array of strings representing each tag name to include.

_Note:_ It may be worth considering adding a value for this config variable that can be used to include all tags for a resource.

#### Out of Scope:

- Adding any filtering for Azure tags outside of existing filters
- Displaying tags on the UI
- Adding tags for other packages (i.e. GCP)

#### Related issues/Dependencies:
- AWS Implementation: https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/904
- Original API Filtering (includes existing tag filters): https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/911

## Tech Tasks
- [ ] Add appropriate test coverage, including edge cases.
- [ ] Run Changesets, bump any packages that have been updated/changed
- [ ] Did you make changes to the client, api or cli package? If so, considering updating the create-app templates. You can use the `./scripts/update_templates.sh [package-name]` command from the root of the package to do so.
- [ ] If any create-app templates have been updated, make sure to run the [test-create-app script](https://docs.google.com/document/d/1Ei6Cb2DjwEJUNtpULJSxbOuIdAfCARERgE3BSsKWrsc/edit) to ensure it still works properly.

## Review Tasks
- [ ] Add Azure-specific tagging documentation to microsite (for CCF team)

**Comment by 4upz** [comment]
A great follow-up to this Feature Request https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/625, will begin analysis soon

**Comment by NicolasBissig** [comment]
Hey, I've taken a look at the original ticket, and maybe have a solution / approach for it. I am working on expanding the CCF Azure support for my company, and we needed the ability to group estimations per resource group and tags. 

The solution I came up with would add all azure tags in the `tags` field of a `BillingDataRow` and also includes the `resourceGroup` as a tag. I have not yet tested filtering with API parameters, as I am doing the filtering myself somewhere else.

If you are interested in this solution, I would be willing to contribute it in a pull request.

**Comment by 4upz** [comment]
Hey @NicolasBissig thanks for reaching out about this issue! The solution definitely sounds like what we're looking for, as we're hoping to fulfill the same level of tagging for Azure that we currently have implemented for [AWS](https://www.cloudcarbonfootprint.org/docs/tagging).

This would mostly follow the way we implemented tags for AWS in PR https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/904. So adding necessary information to the existing `tags` field as you mentioned is the way to go. 

Also, no need to worry about filtering, as we currently have a filtering method implemented that includes tags as noted in Issue https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/911. If any changes are needed to get them working for Azure, we're happy to implement them

I'll add more details to this issue's description surrounding task, scope, tech, etc just to formally have it documented. But feel free to leave any questions or reach out here for support if you need it 😄

**Comment by 4upz** [comment]
Issue description has been updated and should be good to go! @NicolasBissig 👍🏽  Feel free to let me know if you have any questions
