### ISSUE TITLE
Mismatch between CLI data and the LookUp table approach (GCP)

### ISSUE THREAD

**Issue by gsuresh92** [cloud-carbon-footprint/cloud-carbon-footprint#966]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - macOS 12.5.1

### Expected Behavior
Expecting that the numbers should match between the CLI approach and the Look Up data approach. 

### Actual Behavior

Kwh seems to match but not the Co2E 

### To Reproduce

1. Created a CO2e data extract using the command `yarn start-cli --startDate 2022-09-01 --endDate 2022-09-30 --groupBy dayAndService --format csv`
2. Generated the Lookup table for GCP using the command `yarn create-lookup-table --gcpInput gcpInput.csv --gcpOutput gcp_lookup_data.csv`
3. Tried to compare the output from the 1st command with the calculated output using the lookup data. The Kwh seems to match exactly but CO2e are higher in the lookup based approach by a factor of ~2.  Did this comparison for Cloud Storage & Cloud SQL Services..

### Additional Information

© 2021 Thoughtworks, Inc.

**Comment by ccasher** [comment]
Hello, thank you very much for adding this issue! We currently have a separate issue in progress #839 so I will mark this as duplicate and close. Please feel free to comment if you feel there is more to consider!
