### ISSUE TITLE
Improve logs for Azure rate limit retry

### ISSUE THREAD

**Issue by 4upz** [cloud-carbon-footprint/cloud-carbon-footprint#982]
Currently, the logs print the same repeated rate limit error message whenever rate limits are hit for a consumption detail request. This is due to all subscription requests running async simultaneously. We need to either print one log when all subscriptions are in timeout, or print more specific logs so that it provides more useful information on the progress of the given usage row

**Comment by ericksod** [comment]
This issue should not be needed given the planned implementation in #1175
