### ISSUE TITLE
EU-ColdStorage-ByteHrs-DynamoDB usage type

### ISSUE THREAD

**Issue by karmankertesz** [cloud-carbon-footprint/cloud-carbon-footprint#992]
## Feature Suggestion
**Is your feature request related to a problem? Please describe.**

Missing usage type reported in the log.

**Describe the solution you'd like**

Add it to CostAndUsageTypes.ts in 

HDD_USAGE_TYPES as 'EU-ColdStorage-ByteHrs-DynamoDB' and in  BYTE_HOURS_USAGE_TYPES as 'ByteHrs-DynamoDB' 

**Additional context**

Log entry:

`2022-11-28T15:49:53.660Z [CostAndUsageReports] warn: Unexpected usage type for storage estimation. Usage type: EU-ColdStorage-ByteHrs-DynamoDB 
`

**Comment by ericksod** [comment]
Hi @karmankertesz!
Nice find - would you be interested in making that update in a PR?
